const EP='https://demo.connect.easyparcel.my/?ac=';
function denyProduction(){if(process.env.VERCEL_ENV==='production')throw Object.assign(new Error('Staging EasyParcel adapter is disabled in production'),{statusCode:403})}
function env(){const e={sbUrl:process.env.STAGING_SUPABASE_URL,pub:process.env.STAGING_SUPABASE_PUBLISHABLE_KEY,service:process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY,epKey:process.env.EASYPARCEL_DEMO_API_KEY};if(!e.sbUrl||!e.pub||!e.service)throw new Error('Staging Supabase server credentials are not configured');if(!e.epKey)throw new Error('EasyParcel demo API key is not configured');return e}
function parseBody(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return Object.fromEntries(new URLSearchParams(req.body));return{}}
async function authAdmin(req,e){const h=String(req.headers.authorization||''),m=/^Bearer\s+(.+)$/i.exec(h);if(!m)throw Object.assign(new Error('Authenticated staging admin required'),{statusCode:401});const ur=await fetch(`${e.sbUrl}/auth/v1/user`,{headers:{apikey:e.pub,authorization:`Bearer ${m[1]}`}}),u=await ur.json();if(!ur.ok||!u?.id)throw Object.assign(new Error('Invalid staging admin session'),{statusCode:401});const rows=await serviceGet(e,`admin_users?user_id=eq.${encodeURIComponent(u.id)}&active=eq.true&select=user_id,role,active`),admin=rows?.[0];if(!admin||!['super_admin','order_manager'].includes(admin.role))throw Object.assign(new Error('Staging shipping admin permission required'),{statusCode:403});return u}
async function serviceGet(e,path){const r=await fetch(`${e.sbUrl}/rest/v1/${path}`,{headers:{apikey:e.service,authorization:`Bearer ${e.service}`}}),j=await r.json();if(!r.ok)throw new Error(j?.message||'Staging Supabase read failed');return j}
async function serviceRpc(e,name,body){const r=await fetch(`${e.sbUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:e.service,authorization:`Bearer ${e.service}`,'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw new Error(j?.message||j?.error||`Staging RPC ${name} failed`);return j}
async function postEasyParcel(e,action,bulk){const p=new URLSearchParams();p.set('api',e.epKey);for(const [k,v] of Object.entries(bulk||{})){if(v===undefined||v===null)continue;p.set(`bulk[0][${k}]`,String(v))}const r=await fetch(EP+action,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:p}),text=await r.text();let j;try{j=JSON.parse(text)}catch{throw new Error(`EasyParcel returned invalid JSON: ${text.slice(0,180)}`)}if(!r.ok||String(j.api_status||'').toLowerCase()==='error')throw new Error(j.error_remark||`EasyParcel ${action} failed`);return j}
async function getIntegration(e){const rows=await serviceGet(e,'integration_configs?integration_key=eq.easyparcel&select=enabled,mode,status,config'),x=rows?.[0];if(!x||!x.enabled||x.status!=='ready')throw new Error('EasyParcel integration is not enabled and ready in Operations');return x.config||{}}
async function getOrderContext(e,orderId){const orders=await serviceGet(e,`orders?id=eq.${encodeURIComponent(orderId)}&select=*`),order=orders?.[0];if(!order)throw new Error('Order not found');const items=await serviceGet(e,`order_items?order_id=eq.${encodeURIComponent(orderId)}&select=variant_id,quantity,product_name`),ids=[...new Set((items||[]).map(x=>x.variant_id).filter(Boolean))];let variants=[];if(ids.length)variants=await serviceGet(e,`variants?id=in.(${ids.map(encodeURIComponent).join(',')})&select=id,weight_grams`);const wm=new Map((variants||[]).map(v=>[v.id,Number(v.weight_grams||0)]));return {order,items:items||[],weightGrams:(items||[]).reduce((s,x)=>s+(wm.get(x.variant_id)||0)*Number(x.quantity||0),0)}}
function parcel(cfg,ctx){const fallback=Number(cfg.default_weight_kg||0),kg=ctx.weightGrams>0?Math.max(.01,ctx.weightGrams/1000):fallback;if(!(kg>0))throw new Error('Parcel weight is missing. Set variant weight_grams or EasyParcel default_weight_kg.');return {weight:kg.toFixed(2),width:Number(cfg.default_width_cm||0),length:Number(cfg.default_length_cm||0),height:Number(cfg.default_height_cm||0),content:String(cfg.default_content||'Research supplies').slice(0,35)}}
function sender(cfg){for(const k of ['pick_name','pick_contact','pick_addr1','pick_city','pick_state','pick_code'])if(!String(cfg[k]||'').trim())throw new Error(`EasyParcel sender configuration missing ${k}`);return {pick_point:String(cfg.pick_point||''),pick_name:String(cfg.pick_name).slice(0,35),pick_company:String(cfg.pick_company||'').slice(0,35),pick_contact:String(cfg.pick_contact).slice(0,16),pick_mobile:String(cfg.pick_mobile||cfg.pick_contact).slice(0,16),pick_addr1:String(cfg.pick_addr1).slice(0,35),pick_addr2:String(cfg.pick_addr2||'').slice(0,35),pick_addr3:String(cfg.pick_addr3||'').slice(0,35),pick_addr4:String(cfg.pick_addr4||'').slice(0,35),pick_city:String(cfg.pick_city).slice(0,35),pick_state:String(cfg.pick_state).slice(0,35),pick_code:String(cfg.pick_code).slice(0,10),pick_country:String(cfg.pick_country||'MY').slice(0,35)}}
function receiver(order){const a=order.shipping_address||{};for(const k of ['recipient_name','phone','line1','city','state','postcode'])if(!String(a[k]||'').trim())throw new Error(`Shipping address missing ${k}`);return {send_point:'',send_name:String(a.recipient_name).slice(0,35),send_company:'',send_contact:String(a.phone).slice(0,16),send_mobile:String(a.phone).slice(0,16),send_addr1:String(a.line1).slice(0,35),send_addr2:String(a.line2||'').slice(0,35),send_addr3:'',send_addr4:'',send_city:String(a.city).slice(0,35),send_state:String(a.state).slice(0,35),send_code:String(a.postcode).slice(0,10),send_country:String(a.country||'MY').slice(0,35)}}
module.exports={env,denyProduction,parseBody,authAdmin,serviceGet,serviceRpc,postEasyParcel,getIntegration,getOrderContext,parcel,sender,receiver};