const EP='https://api.easyparcel.com/open_api/2026-06';
const EP_TOKEN='https://api.easyparcel.com/oauth/token';

function denyProduction(){if(process.env.VERCEL_ENV==='production')throw Object.assign(new Error('Staging EasyParcel adapter is disabled in production'),{statusCode:403})}
function env(){const e={sbUrl:process.env.STAGING_SUPABASE_URL,pub:process.env.STAGING_SUPABASE_PUBLISHABLE_KEY,service:process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY,epClientId:process.env.EASYPARCEL_CLIENT_ID,epClientSecret:process.env.EASYPARCEL_CLIENT_SECRET,epRedirectUri:process.env.EASYPARCEL_REDIRECT_URI||defaultRedirectUri()};if(!e.sbUrl||!e.pub||!e.service)throw new Error('Staging Supabase server credentials are not configured');if(!e.epClientId||!e.epClientSecret)throw new Error('EasyParcel OAuth client credentials are not configured');return e}
function defaultRedirectUri(){const host=String(process.env.VERCEL_URL||'').trim();return host?`https://${host}/api/easyparcel/callback`:''}
function parseBody(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return Object.fromEntries(new URLSearchParams(req.body));return{}}
async function authAdmin(req,e){const h=String(req.headers.authorization||''),m=/^Bearer\s+(.+)$/i.exec(h);if(!m)throw Object.assign(new Error('Authenticated staging admin required'),{statusCode:401});const ur=await fetch(`${e.sbUrl}/auth/v1/user`,{headers:{apikey:e.pub,authorization:`Bearer ${m[1]}`}}),u=await ur.json();if(!ur.ok||!u?.id)throw Object.assign(new Error('Invalid staging admin session'),{statusCode:401});const rows=await serviceGet(e,`admin_users?user_id=eq.${encodeURIComponent(u.id)}&active=eq.true&select=user_id,role,active`),admin=rows?.[0];if(!admin||!['super_admin','order_manager'].includes(admin.role))throw Object.assign(new Error('Staging shipping admin permission required'),{statusCode:403});return u}
async function serviceGet(e,path){const r=await fetch(`${e.sbUrl}/rest/v1/${path}`,{headers:{apikey:e.service,authorization:`Bearer ${e.service}`}}),j=await r.json();if(!r.ok)throw new Error(j?.message||'Staging Supabase read failed');return j}
async function serviceRpc(e,name,body={}){const r=await fetch(`${e.sbUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:e.service,authorization:`Bearer ${e.service}`,'content-type':'application/json'},body:JSON.stringify(body)}),text=await r.text();let j=null;try{j=text?JSON.parse(text):null}catch{}if(!r.ok)throw new Error(j?.message||j?.error||`Staging RPC ${name} failed`);return j}
async function getOauthTokens(e){const t=await serviceRpc(e,'easyparcel_get_oauth_tokens',{});if(!t?.access_token)throw Object.assign(new Error('EasyParcel OAuth is not connected. Use Connect EasyParcel in Operations first.'),{statusCode:409});return t}
async function storeOauthTokens(e,t){return serviceRpc(e,'easyparcel_store_oauth_tokens',{p_access_token:t.access_token,p_refresh_token:t.refresh_token||null,p_expires_at:t.expires_at||isoFromSeconds(t.expires_in),p_refresh_expires_at:t.refresh_token_expires_at||isoFromSeconds(t.refresh_token_expires_in)})}
async function refreshOauthTokens(e,refreshToken){if(!refreshToken)throw Object.assign(new Error('EasyParcel access token expired and no refresh token is available. Reconnect EasyParcel in Operations.'),{statusCode:401});const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshToken});if(e.epRedirectUri)body.set('redirect_uri',e.epRedirectUri);const basic=Buffer.from(`${e.epClientId}:${e.epClientSecret}`).toString('base64');const r=await fetch(EP_TOKEN,{method:'POST',headers:{Authorization:`Basic ${basic}`,'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body}),text=await r.text();let j=null;try{j=JSON.parse(text)}catch{}if(!r.ok||!j?.access_token)throw Object.assign(new Error('EasyParcel OAuth refresh failed. Reconnect EasyParcel in Operations.'),{statusCode:401});await storeOauthTokens(e,j);return j}
async function postEasyParcelOpenApi(e,path,payload){let tokens=await getOauthTokens(e);let r=await epFetch(path,payload,tokens.access_token);if(r.response.status===401){tokens=await refreshOauthTokens(e,tokens.refresh_token);r=await epFetch(path,payload,tokens.access_token)}if(!r.response.ok||Number(r.json?.status_code||r.response.status)>=400)throw Object.assign(new Error(r.json?.message||`EasyParcel ${path} failed`),{statusCode:r.response.status||502,detail:r.json});return r.json}
async function epFetch(path,payload,accessToken){const response=await fetch(`${EP}${path}`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(payload||{})}),text=await response.text();let json=null;try{json=JSON.parse(text)}catch{throw new Error(`EasyParcel returned invalid JSON: ${text.slice(0,180)}`)}return{response,json}}
function isoFromSeconds(seconds){const n=Number(seconds||0);return n>0?new Date(Date.now()+n*1000).toISOString():null}
async function getIntegration(e){const rows=await serviceGet(e,'integration_configs?integration_key=eq.easyparcel&select=enabled,mode,status,config'),x=rows?.[0];if(!x||!x.enabled||!['healthy','connected'].includes(x.status)||!x.config?.oauth_connected)throw new Error('EasyParcel OAuth integration is not connected in Operations');return x.config||{}}
async function getOrderContext(e,orderId){const orders=await serviceGet(e,`orders?id=eq.${encodeURIComponent(orderId)}&select=*`),order=orders?.[0];if(!order)throw new Error('Order not found');const items=await serviceGet(e,`order_items?order_id=eq.${encodeURIComponent(orderId)}&select=variant_id,quantity,product_name,unit_price,line_total`),ids=[...new Set((items||[]).map(x=>x.variant_id).filter(Boolean))];let variants=[];if(ids.length)variants=await serviceGet(e,`variants?id=in.(${ids.map(encodeURIComponent).join(',')})&select=id,weight_grams`);const wm=new Map((variants||[]).map(v=>[v.id,Number(v.weight_grams||0)]));return {order,items:items||[],weightGrams:(items||[]).reduce((s,x)=>s+(wm.get(x.variant_id)||0)*Number(x.quantity||0),0)}}
function parcel(cfg,ctx){const fallback=Number(cfg.default_weight_kg||0),kg=ctx.weightGrams>0?Math.max(.01,ctx.weightGrams/1000):fallback;if(!(kg>0))throw new Error('Parcel weight is missing. Set variant weight_grams or EasyParcel default_weight_kg.');const width=Number(cfg.default_width_cm||0),length=Number(cfg.default_length_cm||0),height=Number(cfg.default_height_cm||0);if(!(width>0&&length>0&&height>0))throw new Error('Parcel dimensions are missing. Configure EasyParcel default width, length and height.');return {weight:Number(kg.toFixed(2)),width,length,height,content:String(cfg.default_content||'Research supplies').slice(0,35)}}
function sender(cfg){for(const k of ['pick_name','pick_contact','pick_addr1','pick_city','pick_state','pick_code'])if(!String(cfg[k]||'').trim())throw new Error(`EasyParcel sender configuration missing ${k}`);const country=String(cfg.pick_country||'MY').toUpperCase();return {name:String(cfg.pick_name).slice(0,80),company:String(cfg.pick_company||'').slice(0,80),phone_number_country_code:country,phone_number:phoneNumber(cfg.pick_mobile||cfg.pick_contact,country),email:String(cfg.pick_email||'').slice(0,120),address_1:String(cfg.pick_addr1).slice(0,120),address_2:String(cfg.pick_addr2||'').slice(0,120),postcode:String(cfg.pick_code).slice(0,10),city:String(cfg.pick_city).slice(0,80),subdivision_code:subdivisionCode(cfg.pick_state,country),country_code:country}}
function receiver(order,email=''){const a=order.shipping_address||{};for(const k of ['recipient_name','phone','line1','city','state','postcode'])if(!String(a[k]||'').trim())throw new Error(`Shipping address missing ${k}`);const country=String(a.country||'MY').toUpperCase();return {name:String(a.recipient_name).slice(0,80),company:String(a.company||'').slice(0,80),phone_number_country_code:country,phone_number:phoneNumber(a.phone,country),email:String(email||'').slice(0,120),address_1:String(a.line1).slice(0,120),address_2:String(a.line2||'').slice(0,120),postcode:String(a.postcode).slice(0,10),city:String(a.city).slice(0,80),subdivision_code:subdivisionCode(a.state,country),country_code:country}}
function quoteAddress(address){return {postcode:address.postcode,subdivision_code:address.subdivision_code,country:address.country_code}}
function subdivisionCode(value,country='MY'){const raw=String(value||'').trim();if(!raw)return'';if(/^[A-Z]{2}-[A-Z0-9]{1,3}$/i.test(raw))return raw.toUpperCase();if(country!=='MY')return raw;const key=raw.toLowerCase().replace(/[._-]/g,' ').replace(/\s+/g,' ').trim();const map={'johor':'MY-01','kedah':'MY-02','kelantan':'MY-03','melaka':'MY-04','malacca':'MY-04','negeri sembilan':'MY-05','pahang':'MY-06','penang':'MY-07','pulau pinang':'MY-07','perak':'MY-08','perlis':'MY-09','selangor':'MY-10','terengganu':'MY-11','sabah':'MY-12','sarawak':'MY-13','kuala lumpur':'MY-14','wilayah persekutuan kuala lumpur':'MY-14','wp kuala lumpur':'MY-14','labuan':'MY-15','wilayah persekutuan labuan':'MY-15','putrajaya':'MY-16','wilayah persekutuan putrajaya':'MY-16'};const code=map[key];if(!code)throw new Error(`Unsupported Malaysia state for EasyParcel: ${raw}`);return code}
function phoneNumber(value,country){let s=String(value||'').replace(/\D/g,'');if(country==='MY'){if(s.startsWith('60'))s=s.slice(2);if(s.startsWith('0'))s=s.slice(1)}if(!s)throw new Error('Shipping phone number is invalid');return s.slice(0,20)}
function shipmentItem(cfg,ctx,p){return {content:p.content,weight:p.weight,height:p.height,length:p.length,width:p.width,currency_code:'MYR',value:Number(ctx.order.grand_total||0),quantity:1}}
module.exports={env,denyProduction,parseBody,authAdmin,serviceGet,serviceRpc,getOauthTokens,postEasyParcelOpenApi,getIntegration,getOrderContext,parcel,sender,receiver,quoteAddress,shipmentItem,subdivisionCode};
