// Targeted runtime fixes layered on top of admin.js without touching database contents.
window.nav=function(){const el=document.getElementById('nav');if(!el)return;el.innerHTML=modules.map(([k,n])=>`<button class="${k===current?'active':''}" onclick="openModule('${k}')">${n}</button>`).join('')};
window.adjustWallet=async function(i){const r=rows[i];let raw=prompt('Adjustment amount. Positive adds credit, negative deducts.','0');if(raw===null)return;const signed=Number(raw);if(!signed)return flash('Enter a non-zero amount');const reason=prompt('Reason for wallet adjustment');if(!reason||reason.trim().length<3)return flash('A reason of at least 3 characters is required');const type=signed>0?'credit':'debit',amount=Math.abs(signed),key='admin-'+crypto.randomUUID();const {error}=await sb.rpc('adjust_wallet',{p_user_id:r.user_id,p_type:type,p_amount:amount,p_reason:reason.trim(),p_idempotency_key:key,p_order_id:null});if(error)return flash(error.message);flash('Wallet adjusted');wallet()};
window.products=async function(){try{rows=await q('products','*',{order:'updated_at'});content.innerHTML=`<div class="panel card"><div class="toolbar"><button class="btn primary" onclick="newProduct()">New product</button><button class="btn" onclick="products()">Refresh</button></div>${table(rows,['name','slug','product_type','featured','published','status','updated_at'],(r,i)=>`<button class="btn" onclick="editProduct(${i})">Edit</button>`)}</div>`}catch(e){content.innerHTML=`<div class="notice bad">${esc(e.message)}</div>`}};
window.wallet=async function(){try{const [wa,cp]=await Promise.all([q('wallet_accounts','*'),q('customer_profiles','user_id,name,email')]);rows=wa.map(x=>({...x,customer:cp.find(c=>c.user_id===x.user_id)}));content.innerHTML=`<div class="panel card">${table(rows,['user_id','balance'],(r,i)=>`<div>${esc(r.customer?.name||r.customer?.email||'')}</div><button class="btn" onclick="adjustWallet(${i})">Adjust</button>`)}</div>`}catch(e){content.innerHTML=`<div class="notice bad">${esc(e.message)}</div>`}};
window.orders=async function(){rows=await q('orders','*',{order:'created_at'});content.innerHTML=`<div class="panel card">${table(rows,['order_number','customer_email','status','grand_total','created_at'],(r,i)=>`<button class="btn" onclick="manageOrder(${i})">Manage</button> <button class="btn" onclick="makeInvoice(${i})">Invoice</button> <button class="btn" onclick="addTracking(${i})">Tracking</button>`)}</div>`};
window.manageOrder=async function(i){const r=rows[i],status=prompt('New order status',r.status);if(!status||status===r.status)return;const note=prompt('Internal note','')||'';const {error}=await sb.rpc('admin_update_order_status',{p_order_id:r.id,p_status:status,p_note:note});if(error)return flash(error.message);flash('Order status updated');orders()};
window.makeInvoice=async function(i){const r=rows[i];const {data,error}=await sb.rpc('admin_generate_invoice',{p_order_id:r.id});if(error)return flash(error.message);flash('Invoice generated: '+(data?.invoice_number||'ready'));orders()};
window.addTracking=async function(i){const r=rows[i],courier=prompt('Courier','SPX Express');if(!courier)return;const tracking=prompt('Tracking number','');if(!tracking)return;const url=prompt('Tracking URL (optional)','')||null;const {error}=await sb.rpc('admin_add_tracking',{p_order_id:r.id,p_courier:courier,p_tracking_number:tracking,p_tracking_url:url});if(error)return flash(error.message);flash('Tracking added');orders()};
window.media=async function(){rows=await q('media_assets','*',{order:'created_at'});const active=t=>rows.find(x=>x.asset_type===t&&!x.archived);content.innerHTML=`<div class="panel card"><h2>Master Placeholders</h2><p class="muted">Upload replacement master artwork. Existing catalog data is not changed.</p><div class="form-grid">${[['master_vial','Vial'],['master_pen','Pen'],['master_cartridge','Cartridge']].map(([t,n])=>{const a=active(t);return `<div class="field"><label>${n} master</label>${a?.public_url?`<img class="thumb" src="${esc(a.public_url)}" alt="${n}">`:''}<input type="file" accept="image/*" id="file-${t}"><button class="btn primary" onclick="uploadMaster('${t}')">Upload ${n}</button><small>${esc(a?.public_url||'Not uploaded')}</small></div>`}).join('')}</div></div><div class="panel card"><h2>Media Library</h2>${table(rows,['asset_type','public_url','alt_text','archived','created_at'],(r,i)=>r.public_url?`<a class="btn" target="_blank" href="${esc(r.public_url)}">Open</a>`:'')}</div>`};
window.uploadMaster=async function(type){const input=document.getElementById('file-'+type),file=input?.files?.[0];if(!file)return flash('Choose an image first');if(!file.type.startsWith('image/'))return flash('Image files only');const base=type.replace('master_',''),path=`masters/${base}-master`,bucket='catalog-media';const {error:upErr}=await sb.storage.from(bucket).upload(path,file,{upsert:true,contentType:file.type,cacheControl:'0'});if(upErr)return flash(upErr.message);const {data:urlData}=sb.storage.from(bucket).getPublicUrl(path);const public_url=urlData.publicUrl+'?v='+Date.now();await sb.from('media_assets').update({archived:true,archived_at:new Date().toISOString()}).eq('asset_type',type).eq('archived',false);const {error}=await sb.from('media_assets').insert({bucket,object_path:path,public_url,asset_type:type,alt_text:`AI BioTech ${base} master`,used_by:{type:'master_placeholder'},archived:false});if(error)return flash(error.message);flash('Master artwork uploaded');media()};
window.invoices=async function(){rows=await q('invoices','*',{order:'generated_at'});content.innerHTML=`<div class="panel card">${table(rows,['invoice_number','order_id','version','generated_at'],(r,i)=>`<button class="btn" onclick="navigator.clipboard?.writeText('${esc(r.invoice_number)}');flash('Invoice number copied')">Copy #</button>`)}</div>`};
window.shipments=async function(){rows=await q('shipments','*',{order:'updated_at'});content.innerHTML=`<div class="panel card">${table(rows,['order_id','courier','tracking_number','manual_status','live_status','updated_at'],(r,i)=>r.tracking_url?`<a class="btn" target="_blank" href="${esc(r.tracking_url)}">Track</a>`:'')}</div>`};
window.scan=async function(){const paths=['/','/admin','/admin.html','/member','/member.html','/checkout','/checkout.html','/calculator','/peptide-calculator.html','/product/cagri','/app.js','/store-fixes.js','/admin.js','/admin-fixes.js','/admin.css','/member.js','/member.css','/checkout.js','/product-page.js','/style.css','/product-detail.js','/research.js','/guides.js','/faq.js'];content.innerHTML=`<div class="panel card"><h2>Website Scan</h2><p class="muted">Checks the live domain for broken pages, scripts, styles and core permalinks.</p><button class="btn primary" onclick="runScan()">Run scan</button><div id="scanOut"></div></div>`;window._scanPaths=paths};
