const SB_URL='https://yjauxyvtrmdriwtmckkl.supabase.co',SB_KEY='sb_publishable_xib7Xo5_y1G75gSAmkW9QQ__H5-mgZF';
const csb=supabase.createClient(SB_URL,SB_KEY);
let cart=JSON.parse(localStorage.getItem('aibt_cart')||'[]'),me=null,addresses=[],wallet=0,newAddress=null,cartIssues=[],shippingRates=[],selectedShipping=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[m]));
const money=v=>'RM '+Number(v||0).toFixed(2);
function msg(t){checkoutMessage.textContent=t||''}
function addressMsg(t){if(window.addressMessage)addressMessage.textContent=t||''}
function subtotal(){return cart.reduce((s,x)=>s+Number(x.price||0)*Number(x.qty||0),0)}
function shippingFee(){return selectedShipping?Number(selectedShipping.price||0):0}
function totals(){const sub=subtotal(),shipping=shippingFee(),walletUse=Math.max(0,Number(walletAmount?.value||0)),total=Math.max(0,sub+shipping-walletUse);return{sub,shipping,walletUse,total}}
function renderTotals(){const t=totals();checkoutSubtotal.textContent=money(t.sub);checkoutShipping.textContent=selectedShipping?money(t.shipping):'Select EasyParcel service';checkoutGrandTotal.textContent=money(t.total);const max=Math.min(wallet,t.sub+t.shipping);walletAmount.max=String(max);if(Number(walletAmount.value||0)>max)walletAmount.value=String(max);refreshPlaceOrderState()}
function refreshPlaceOrderState(){if(!window.placeOrderBtn)return;placeOrderBtn.disabled=!cart.length||cart.some(x=>x.unavailable)||!selectedShipping}
function renderCart(){checkoutItems.innerHTML=cart.map(x=>`<div class="order"><b>${esc(x.name)}</b><div>${esc(x.strength)} · ${esc(x.form)}</div><small>${money(x.price)} × ${x.qty}</small>${x.unavailable?'<div class="notice">This variant is unavailable or out of stock.</div>':''}</div>`).join('')||'<p>Your cart is empty.</p>';renderTotals();if(cartIssues.length)msg(cartIssues.join(' '))}
function addressText(a){return `${a.label||'Address'} — ${a.recipient_name}, ${a.line1}${a.line2?' '+a.line2:''}, ${a.postcode} ${a.city}, ${a.state}`}
function renderAddresses(){checkoutAddress.innerHTML=addresses.map((a,i)=>`<option value="${i}">${esc(addressText(a))}</option>`).join('')+(newAddress?`<option value="new" selected>${esc(addressText(newAddress))}</option>`:'');if(!addresses.length&&!newAddress)checkoutAddress.innerHTML='<option value="">No saved address</option>'}
function currentAddress(){return checkoutAddress.value==='new'?newAddress:addresses[Number(checkoutAddress.value)]||null}
async function ensureOwnProfile(){const {error}=await csb.rpc('ensure_my_customer_profile');if(error)throw new Error('We could not prepare your member profile. Please sign out and sign in again.')}
async function paymentSession(){const {data:{session}}=await csb.auth.getSession();if(!session?.access_token)throw new Error('Please sign in again before payment.');return session}
async function ensureSandboxPaymentReady(){const session=await paymentSession();const r=await fetch('/api/toyyibpay-create',{method:'GET',headers:{Authorization:`Bearer ${session.access_token}`}});const data=await r.json().catch(()=>({}));if(!r.ok||data.mode!=='sandbox')throw new Error(data.error||'Main-store sandbox payment is not configured yet.');return session}
async function startSandboxPayment(orderId,session){const r=await fetch('/api/toyyibpay-create',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({orderId})});const data=await r.json().catch(()=>({}));if(!r.ok||data.mode!=='sandbox'||!data.paymentUrl)throw new Error(data.error||'Could not start ToyyibPay sandbox payment.');return data}
async function syncCart(){cartIssues=[];const ids=[...new Set(cart.map(x=>x.variantId).filter(Boolean))];if(!ids.length)return;const {data,error}=await csb.from('variants').select('id,product_id,strength_label,format,price,stock_quantity,reserved_quantity,active,archived_at,products(name)').in('id',ids);if(error){cartIssues.push('Could not refresh live stock. Please refresh again before ordering.');return}const map=new Map((data||[]).map(v=>[v.id,v]));cart=cart.map(item=>{const v=map.get(item.variantId);if(!v||v.active===false||v.archived_at)return {...item,unavailable:true};const available=Math.max(0,Number(v.stock_quantity||0)-Number(v.reserved_quantity||0));let qty=Math.max(1,Number(item.qty||1));if(available>0&&qty>available){qty=available;cartIssues.push(`Quantity adjusted to live stock for ${v.products?.name||item.name}.`)}return {...item,name:v.products?.name||item.name,strength:v.strength_label,form:v.format,price:Number(v.price||0),qty,unavailable:available<=0}});localStorage.setItem('aibt_cart',JSON.stringify(cart))}
function renderShippingRates(){if(!shippingRates.length){easyParcelRates.innerHTML='';return}easyParcelRates.innerHTML=shippingRates.map((r,i)=>`<label class="order" style="display:block;cursor:pointer"><input type="radio" name="easyparcelRate" value="${i}" ${selectedShipping?.serviceId===r.serviceId&&selectedShipping?.price===r.price?'checked':''}> <b>${esc(r.courierName||r.serviceName)}</b>${r.serviceName&&r.serviceName!==r.courierName?` — ${esc(r.serviceName)}`:''}<div>${esc(r.delivery||r.serviceDetail||'Delivery service')}</div><small>${money(r.price)}</small></label>`).join('');easyParcelRates.querySelectorAll('input[name="easyparcelRate"]').forEach(el=>el.addEventListener('change',()=>{selectedShipping=shippingRates[Number(el.value)]||null;easyParcelMessage.textContent=selectedShipping?`${selectedShipping.courierName||selectedShipping.serviceName} selected.`:'Select a courier service.';renderTotals()}))}
async function refreshShippingRates(){const address=currentAddress();selectedShipping=null;shippingRates=[];renderShippingRates();renderTotals();if(!address||!/^\d{5}$/.test(String(address.postcode||''))||!address.state){easyParcelMessage.textContent='Choose a complete Malaysia shipping address first.';return}refreshShippingBtn.disabled=true;refreshShippingBtn.textContent='LOADING RATES…';easyParcelMessage.textContent='Checking EasyParcel rates…';try{const session=await paymentSession();const r=await fetch('/api/easyparcel-rates',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({postcode:address.postcode,state:address.state,parcelValue:subtotal()})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Could not get EasyParcel rates.');shippingRates=Array.isArray(data.rates)?data.rates:[];if(!shippingRates.length)throw new Error('No EasyParcel courier rates are available for this address.');easyParcelMessage.textContent=`${shippingRates.length} courier option${shippingRates.length===1?'':'s'} available. Select one below.`;renderShippingRates()}catch(e){easyParcelMessage.textContent=e.message||String(e)}finally{refreshShippingBtn.disabled=false;refreshShippingBtn.textContent='CHECK SHIPPING RATES';refreshPlaceOrderState()}}
async function init(){const {data:{user}}=await csb.auth.getUser();if(!user){checkoutLogin.hidden=false;checkoutApp.hidden=true;return}me=user;checkoutLogin.hidden=true;checkoutApp.hidden=false;try{await ensureOwnProfile()}catch(e){msg(e.message)}await syncCart();const [{data:a},{data:w}]=await Promise.all([csb.from('addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}),csb.from('wallet_accounts').select('balance').eq('user_id',user.id).maybeSingle()]);addresses=a||[];wallet=Number(w?.balance||0);checkoutWallet.textContent=money(wallet);renderAddresses();renderCart();if(!addresses.length)useNewAddress();else refreshShippingRates()}
function useNewAddress(){newAddressForm.hidden=false;addressMsg('');shipRecipient.focus()}
function collectNewAddress(){const a={label:'Checkout',recipient_name:shipRecipient.value.trim(),phone:shipPhone.value.trim(),line1:shipLine1.value.trim(),line2:shipLine2.value.trim(),postcode:shipPostcode.value.trim(),city:shipCity.value.trim(),state:shipState.value,country:'MY'};if(!a.recipient_name||!a.phone||!a.line1||!a.city||!a.state||!/^[0-9]{5}$/.test(a.postcode))return null;return a}
async function applyNewAddress(){const a=collectNewAddress();if(!a)return addressMsg('Please complete all required fields. Postcode must be 5 digits.');newAddress=a;renderAddresses();checkoutAddress.value='new';addressMsg('Address ready for this order.');await refreshShippingRates();if(!saveAddressBook.checked)return;try{await ensureOwnProfile()}catch(e){addressMsg(e.message+' The address can still be used for this order.');return}const row={...a,user_id:me.id,is_default:addresses.length===0};const {data,error}=await csb.from('addresses').insert(row).select('*').single();if(error){addressMsg('Address is ready for this order, but saving failed. Please try again.');return}addresses=[data,...addresses];newAddress=null;renderAddresses();checkoutAddress.value='0';newAddressForm.hidden=true;addressMsg('Address saved to your address book.');await refreshShippingRates()}
function shippingNote(){if(!selectedShipping)return'';return `[EasyParcel] service_id=${selectedShipping.serviceId}; rate_id=${selectedShipping.rateId||''}; courier=${selectedShipping.courierName||''}; service=${selectedShipping.serviceName||''}; price=${Number(selectedShipping.price||0).toFixed(2)}; delivery=${selectedShipping.delivery||''}`}
async function placeOrder(){if(!cart.length)return msg('Your cart is empty.');if(cart.some(x=>x.unavailable))return msg('Remove unavailable items before checkout.');const address=currentAddress();if(!address)return msg('Choose or enter a shipping address.');if(!selectedShipping)return msg('Select an EasyParcel courier service before placing your order.');const t=totals();if(t.walletUse>wallet)return msg('Wallet amount is higher than your available balance.');if(t.walletUse>t.sub+t.shipping)return msg('Wallet amount cannot exceed the order total.');placeOrderBtn.disabled=true;placeOrderBtn.textContent='Preparing sandbox payment…';msg('');try{await ensureOwnProfile();const session=await ensureSandboxPaymentReady();const items=cart.map(x=>({variant_id:x.variantId,quantity:Number(x.qty)})),key='web-'+crypto.randomUUID(),voucher=voucherCode.value.trim()||null,userNote=checkoutNote.value.trim(),notes=[shippingNote(),userNote].filter(Boolean).join('\n');const {data,error}=await csb.rpc('create_order',{p_items:items,p_checkout_key:key,p_voucher_code:voucher,p_shipping_fee:t.shipping,p_wallet_amount:t.walletUse,p_shipping_address:address,p_billing_address:address,p_notes:notes});if(error)throw error;const payment=await startSandboxPayment(data,session);msg('Redirecting to ToyyibPay sandbox…');location.href=payment.paymentUrl}catch(e){msg(e.message||String(e))}finally{placeOrderBtn.disabled=false;placeOrderBtn.textContent='PLACE ORDER';refreshPlaceOrderState()}}
walletAmount.addEventListener('input',renderTotals);checkoutAddress.addEventListener('change',refreshShippingRates);document.addEventListener('DOMContentLoaded',init);
