(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseKey);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const money=v=>'RM'+Number(v||0).toFixed(0);
const MASTER={Vial:'/assets/vial-master-approved.webp',Pen:'/assets/pen-master-approved.webp',Cartridge:'/assets/cartridge-master-approved.webp'};
let products=[],categories=[],cart=JSON.parse(localStorage.getItem('aibt_staging_cart')||'[]');
let featuredOnly=true,selectedCategory='All',selectedFormat='All',stockFilter='All',sortMode='Featured';
const selections=new Map();
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});closeMobileMenu()} window.scrollToId=scrollToId;
function strengthNumber(v){const m=String(v||'').match(/([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):999999}
function byStrength(a,b){return strengthNumber(a)-strengthNumber(b)||String(a).localeCompare(String(b))}
function productSelection(p){let s=selections.get(p.id);const active=(p.variants||[]).filter(v=>v.active!==false);const strengths=[...new Set(active.map(v=>v.strength_label))].sort(byStrength);if(!s||!strengths.includes(s.strength)){const first=active.find(v=>v.format==='Vial')||active[0];s={strength:first?.strength_label||strengths[0],format:first?.format||'Vial'};selections.set(p.id,s)}let compatible=active.filter(v=>v.strength_label===s.strength);if(!compatible.some(v=>v.format===s.format))s.format=(compatible.find(v=>v.format==='Vial')||compatible[0])?.format||s.format;return s}
function selectedVariant(p){const s=productSelection(p);return (p.variants||[]).find(v=>v.strength_label===s.strength&&v.format===s.format&&v.active!==false)||null}
function available(v){return !!v&&v.active!==false&&Number(v.stock_quantity||0)-Number(v.reserved_quantity||0)>0}
function imageFor(v){return v?.image_url||MASTER[v?.format]||MASTER.Vial}
function renderHeroAssets(){for(const [id,f] of [['heroVial','Vial'],['heroPen','Pen'],['heroCartridge','Cartridge']]){const e=document.getElementById(id);if(e)e.src=MASTER[f]}}
function renderCategories(){const all=[{name:'All',color:'#0d2e63'},...categories];$('#categoryChips').innerHTML=all.map(c=>`<button class="chip ${selectedCategory===c.name?'active':''}" onclick="setCategory('${esc(c.name)}')">${esc(c.name)}</button>`).join('');$('#sideCategories').innerHTML=all.map(c=>`<button class="side-cat ${selectedCategory===c.name?'active':''}" onclick="setCategory('${esc(c.name)}')"><span class="dot" style="background:${c.color||'#0d2e63'}"></span>${esc(c.name)}</button>`).join('');$('#categoryFilter').innerHTML=all.map(c=>`<option ${selectedCategory===c.name?'selected':''}>${esc(c.name)}</option>`).join('')}
function filtered(){const q=($('#searchInput')?.value||'').trim().toLowerCase();let a=products.filter(p=>{const variants=(p.variants||[]).filter(v=>v.active!==false);return (selectedCategory==='All'||p.categories?.name===selectedCategory)&&(selectedFormat==='All'||variants.some(v=>v.format===selectedFormat))&&(stockFilter==='All'||(stockFilter==='In Stock'?variants.some(available):!variants.some(available)))&&(!q||[p.name,p.slug,p.categories?.name,...variants.map(v=>`${v.strength_label} ${v.format} ${v.sku}`)].join(' ').toLowerCase().includes(q))&&(!featuredOnly||p.featured)});if(sortMode==='Name')a.sort((x,y)=>x.name.localeCompare(y.name));else if(sortMode==='Price Low')a.sort((x,y)=>Math.min(...x.variants.filter(v=>v.active).map(v=>Number(v.price)))-Math.min(...y.variants.filter(v=>v.active).map(v=>Number(v.price))));return a}
function productCard(p){const s=productSelection(p),v=selectedVariant(p),act=(p.variants||[]).filter(x=>x.active!==false),strengths=[...new Set(act.map(x=>x.strength_label))].sort(byStrength),forms=[...new Set(act.filter(x=>x.strength_label===s.strength).map(x=>x.format))],ok=available(v);return `<article class="product-card" data-format="${esc(v?.format||'Vial')}"><div class="product-media"><span class="category-badge">${esc(p.categories?.name||'Research')}</span><span class="format-badge">${esc(v?.format||'—')}</span><img src="${esc(imageFor(v))}" alt="${esc(p.name)}"></div><div class="product-body"><div class="product-name">${esc(p.name)}</div><div class="variant-row"><div><div class="mini-label">Strength</div><select class="select" onchange="changeStrength('${esc(p.id)}',this.value)">${strengths.map(x=>`<option ${x===s.strength?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div><div class="mini-label">Format</div><select class="select" onchange="changeFormat('${esc(p.id)}',this.value)">${forms.map(x=>`<option ${x===s.format?'selected':''}>${esc(x)}</option>`).join('')}</select></div></div><div class="price-row"><div class="price">${v?money(v.price):'—'}</div><div class="stock ${ok?'':'out'}">${ok?'● In Stock':'● Sold Out'}</div></div><div class="card-actions"><button class="add-btn" ${ok?'':'disabled'} onclick="addToCart('${esc(p.id)}')">${ok?'Add to Cart':'Sold Out'}</button></div></div></article>`}
function renderProducts(){const a=filtered();$('#catalogTitle').textContent=featuredOnly?'Featured Products':selectedCategory==='All'?'All Products':selectedCategory;$('#resultCount').textContent=`${a.length} product${a.length===1?'':'s'}`;$('#productGrid').innerHTML=a.length?a.map(productCard).join(''):'<div class="empty">No products match these filters.</div>';$('#viewAllBtn').hidden=!featuredOnly}
async function loadData(){if(!sb){$('#productGrid').innerHTML='<div class="empty">Staging database connection is unavailable.</div>';return}const [pr,cr]=await Promise.all([sb.from('products').select('id,name,slug,featured,published,status,category_id,categories(id,name,slug,color,description),variants(id,strength_label,format,sku,price,stock_quantity,reserved_quantity,image_url,active)').eq('published',true).eq('status','active'),sb.from('categories').select('id,name,slug,color,description,status').eq('status','active').order('name')]);if(pr.error){$('#productGrid').innerHTML='<div class="empty">Catalog could not be loaded.</div>';return}products=(pr.data||[]).map(p=>({...p,variants:(p.variants||[]).sort((a,b)=>byStrength(a.strength_label,b.strength_label))}));categories=cr.data||[];renderCategories();renderProducts();renderHeroAssets();$('#catalogSummary').textContent=`${products.length} products · ${products.reduce((n,p)=>n+p.variants.filter(v=>v.active!==false).length,0)} active catalog variants in staging`}
function saveCart(){localStorage.setItem('aibt_staging_cart',JSON.stringify(cart));const n=cart.reduce((s,x)=>s+x.qty,0);$$('[data-cart-count]').forEach(x=>x.textContent=n);renderCart()}
function renderCart(){const host=$('#cartItems');if(!host)return;host.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><img src="${esc(x.image)}"><div><b>${esc(x.name)}</b><small>${esc(x.strength)} · ${esc(x.format)} · ${money(x.price)}</small></div><button class="close-btn" onclick="removeCart(${i})">×</button></div>`).join(''):'<div class="empty">Your staging cart is empty.</div>';$('#cartTotal').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
window.addToCart=id=>{const p=products.find(x=>x.id===id),v=p&&selectedVariant(p);if(!p||!available(v))return;const hit=cart.find(x=>x.variantId===v.id);if(hit)hit.qty++;else cart.push({variantId:v.id,productId:p.id,name:p.name,strength:v.strength_label,format:v.format,price:Number(v.price),image:imageFor(v),qty:1});saveCart();toast('Added to cart')};window.removeCart=i=>{cart.splice(i,1);saveCart()};window.changeStrength=(id,strength)=>{const p=products.find(x=>x.id===id);if(!p)return;productSelection(p).strength=strength;renderProducts()};window.changeFormat=(id,format)=>{const p=products.find(x=>x.id===id);if(!p)return;productSelection(p).format=format;renderProducts()};window.setCategory=name=>{selectedCategory=name;featuredOnly=false;renderCategories();renderProducts();scrollToId('catalog')};window.showAllProducts=()=>{featuredOnly=false;renderProducts();scrollToId('catalog')};window.openCart=()=>{$('#cartOverlay').classList.add('show');renderCart()};window.closeCart=()=>$('#cartOverlay').classList.remove('show');window.toggleMobileMenu=()=>$('#mobileMenu').classList.toggle('show');function closeMobileMenu(){$('#mobileMenu').classList.remove('show')}window.closeMobileMenu=closeMobileMenu;window.openResearchCenter=()=>scrollToId('research');window.openGuides=()=>scrollToId('guides');window.openStageAccount=()=>location.href='/member.html';window.stageCheckout=()=>{localStorage.setItem('aibt_cart',JSON.stringify(cart));location.href='/checkout.html'};window.openPublishedPage=page=>location.href=`/${page}.html`;
document.addEventListener('DOMContentLoaded',()=>{$('#searchInput')?.addEventListener('input',()=>{featuredOnly=false;renderProducts()});$('#categoryFilter')?.addEventListener('change',e=>{selectedCategory=e.target.value;featuredOnly=false;renderCategories();renderProducts()});$('#formatFilter')?.addEventListener('change',e=>{selectedFormat=e.target.value;featuredOnly=false;renderProducts()});$('#stockFilter')?.addEventListener('change',e=>{stockFilter=e.target.value;featuredOnly=false;renderProducts()});$('#sortFilter')?.addEventListener('change',e=>{sortMode=e.target.value;featuredOnly=false;renderProducts()});saveCart();loadData()});
})();
