(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};
const sb=window.AIBTRuntime.createClient({access:'catalog'});
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const core=window.AIBTCore, money=core.money;
const MASTER={Vial:'/assets/vial-master-approved.webp',Pen:'/assets/pen-master-approved.webp',Cartridge:'/assets/cartridge-master-approved.webp'};
let products=[],categories=[],cart=core.cart.get();
let featuredOnly=true,selectedCategory='All',selectedFormat='All',stockFilter='All',sortMode='Featured';
const selections=new Map();
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});closeMobileMenu()} window.scrollToId=scrollToId;
function strengthNumber(v){const m=String(v||'').match(/([0-9]+(?:\.[0-9]+)?)/);return m?Number(m[1]):999999}
function byStrength(a,b){return strengthNumber(a)-strengthNumber(b)||String(a).localeCompare(String(b))}
function productSelection(p){let s=selections.get(p.id);const active=(p.variants||[]).filter(v=>core.validVariant(v));const strengths=[...new Set(active.map(v=>v.strength_label))].sort(byStrength);if(!s||!strengths.includes(s.strength)){const first=active.find(v=>v.format==='Vial')||active[0];s={strength:first?.strength_label||strengths[0],format:first?.format||'Vial'};selections.set(p.id,s)}let compatible=active.filter(v=>v.strength_label===s.strength);if(!compatible.some(v=>v.format===s.format))s.format=(compatible.find(v=>v.format==='Vial')||compatible[0])?.format||s.format;return s}
function selectedVariant(p){const s=productSelection(p);return (p.variants||[]).find(v=>v.strength_label===s.strength&&v.format===s.format&&core.validVariant(v))||null}
function available(v){return core.usableStock(v)>0}
function imageFor(v){return v?.image_url||MASTER[v?.format]||MASTER.Vial}
function renderHeroAssets(){for(const [id,f] of [['heroVial','Vial'],['heroPen','Pen'],['heroCartridge','Cartridge']]){const e=document.getElementById(id);if(e){const p=products.find(p=>p.variants.some(v=>core.validVariant(v)&&v.format===f));window.AIBTProductVisual.render(p,p?.variants.find(v=>core.validVariant(v)&&v.format===f)||{format:f},e)}}}
function renderCategories(){const all=[{name:'All',color:'#0d2e63'},...categories];$('#categoryChips').innerHTML=all.map(c=>`<button class="chip ${selectedCategory===c.name?'active':''}" onclick="setCategory('${esc(c.name)}')">${esc(c.name)}</button>`).join('');$('#sideCategories').innerHTML=all.map(c=>`<button class="side-cat ${selectedCategory===c.name?'active':''}" onclick="setCategory('${esc(c.name)}')"><span class="dot" style="background:${c.color||'#0d2e63'}"></span>${esc(c.name)}</button>`).join('');$('#categoryFilter').innerHTML=all.map(c=>`<option ${selectedCategory===c.name?'selected':''}>${esc(c.name)}</option>`).join('')}
function filtered(){const q=($('#searchInput')?.value||'').trim().toLowerCase();let a=products.filter(p=>{const variants=(p.variants||[]).filter(v=>core.validVariant(v));return (selectedCategory==='All'||p.categories?.name===selectedCategory)&&(selectedFormat==='All'||variants.some(v=>v.format===selectedFormat))&&(stockFilter==='All'||(stockFilter==='In Stock'?variants.some(available):!variants.some(available)))&&(!q||[p.name,p.slug,p.categories?.name,...variants.map(v=>`${v.strength_label} ${v.format} ${v.sku}`)].join(' ').toLowerCase().includes(q))&&(!featuredOnly||p.featured)});if(sortMode==='Name')a.sort((x,y)=>x.name.localeCompare(y.name));else if(sortMode==='Price Low')a.sort((x,y)=>Math.min(...x.variants.filter(v=>core.validVariant(v)).map(v=>Number(v.price)))-Math.min(...y.variants.filter(v=>core.validVariant(v)).map(v=>Number(v.price))));return a}
function productCard(p){const s=productSelection(p),v=selectedVariant(p),act=(p.variants||[]).filter(x=>core.validVariant(x)),strengths=[...new Set(act.map(x=>x.strength_label))].sort(byStrength),forms=[...new Set(act.filter(x=>x.strength_label===s.strength).map(x=>x.format))],ok=available(v);return `<article class="product-card" data-product-id="${esc(p.id)}" data-format="${esc(v?.format||'Vial')}"><div class="product-media"><span class="category-badge">${esc(p.categories?.name||'Research')}</span><span class="format-badge">${esc(v?.format||'—')}</span><img src="${esc(imageFor(v))}" alt="${esc(p.name)}"></div><div class="product-body"><button class="product-name" onclick="openProductDetail('${esc(p.id)}')">${esc(p.name)}</button><div class="variant-row"><div><div class="mini-label">Strength</div><select class="select" onchange="changeStrength('${esc(p.id)}',this.value)">${strengths.map(x=>`<option ${x===s.strength?'selected':''}>${esc(x)}</option>`).join('')}</select></div><div><div class="mini-label">Format</div><select class="select" onchange="changeFormat('${esc(p.id)}',this.value)">${forms.map(x=>`<option ${x===s.format?'selected':''}>${esc(x)}</option>`).join('')}</select></div></div><div class="price-row"><div class="price">${v?money(v.price):'—'}</div><div class="stock ${ok?'':'out'}">${ok?'● In Stock':'● Sold Out'}</div></div><div class="card-actions"><button class="add-btn" ${ok?'':'disabled'} onclick="addToCart('${esc(p.id)}')">${ok?'Add to Cart':'Sold Out'}</button></div></div></article>`}
function renderProducts(){const a=filtered();$('#catalogTitle').textContent=featuredOnly?'Featured Products':selectedCategory==='All'?'All Products':selectedCategory;$('#resultCount').textContent=`${a.length} product${a.length===1?'':'s'}`;$('#productGrid').innerHTML=a.length?a.map(productCard).join(''):'<div class="empty">No products match these filters.</div>';$('#viewAllBtn').hidden=!featuredOnly;$$('[data-product-id]').forEach(el=>{const p=products.find(x=>x.id===el.dataset.productId);window.AIBTProductVisual.render(p,selectedVariant(p),el.querySelector('.product-media img'))})}
async function loadData(){if(!sb){$('#productGrid').innerHTML='<div class="empty">Staging database connection is unavailable.</div>';return}const [pr,cr,mr]=await Promise.all([sb.from('products').select('id,name,slug,featured,published,status,category_id,categories(id,name,slug,color,description),variants(id,strength_label,format,sku,price,stock_quantity,reserved_quantity,image_url,active,archived_at)').eq('published',true).eq('status','active'),sb.from('categories').select('id,name,slug,color,description,status').eq('status','active').order('name'),sb.from('media_templates').select('format,master_image_url')]);window.AIBTProductVisual.setTemplates(mr.data||[]);if(pr.error){$('#productGrid').innerHTML='<div class="empty">Catalog could not be loaded.</div>';return}products=(pr.data||[]).map(p=>({...p,variants:(p.variants||[]).sort((a,b)=>byStrength(a.strength_label,b.strength_label))}));core.cart.setVariants(products.flatMap(p=>p.variants));saveCart();categories=cr.data||[];window.AIBTStoreData={products,selectedVariant};renderCategories();renderProducts();renderHeroAssets();window.resolveStoreDeepLink?.();$('#catalogSummary').textContent=`${products.length} products · ${products.reduce((n,p)=>n+p.variants.filter(v=>core.validVariant(v)).length,0)} active catalog variants in staging`}
function saveCart(){cart=core.cart.get();const n=cart.reduce((s,x)=>s+x.qty,0);$$('[data-cart-count]').forEach(x=>x.textContent=n);renderCart()}
function renderCart(){const host=$('#cartItems');if(!host)return;host.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><img src="${esc(x.image||MASTER[x.form]||MASTER.Vial)}"><div><b>${esc(x.name)}</b><small>${esc(x.strength)} · ${esc(x.form)} · ${money(x.price)} × ${x.qty}</small><button aria-label="Decrease quantity" onclick="changeCartQty(${i},-1)">−</button><span>${x.qty}</span><button aria-label="Increase quantity" onclick="changeCartQty(${i},1)">+</button></div><button class="close-btn" onclick="removeCart(${i})">×</button></div>`).join(''):'<div class="empty">Your staging cart is empty.</div>';$('#cartTotal').textContent=money(cart.reduce((s,x)=>s+x.price*x.qty,0))}
window.addToCart=id=>{const p=products.find(x=>x.id===id),v=p&&selectedVariant(p);if(!p||!available(v))return;if(!core.cart.add(p,v))return toast('Available stock already in cart');saveCart();toast('Added to cart')};window.removeCart=i=>{core.cart.remove(cart[i]?.variantId);saveCart()};window.changeCartQty=(i,delta)=>{core.cart.change(cart[i]?.variantId,delta);saveCart()};window.changeStrength=(id,strength)=>{const p=products.find(x=>x.id===id);if(!p)return;productSelection(p).strength=strength;renderProducts()};window.changeFormat=(id,format)=>{const p=products.find(x=>x.id===id);if(!p)return;productSelection(p).format=format;renderProducts()};window.setCategory=name=>{selectedCategory=name;featuredOnly=false;renderCategories();renderProducts();scrollToId('catalog')};window.showAllProducts=()=>{featuredOnly=false;renderProducts();scrollToId('catalog')};window.openCart=()=>{$('#cartOverlay').classList.add('show');renderCart()};window.closeCart=()=>$('#cartOverlay').classList.remove('show');window.toggleMobileMenu=()=>$('#mobileMenu').classList.toggle('show');function closeMobileMenu(){$('#mobileMenu').classList.remove('show')}window.closeMobileMenu=closeMobileMenu;window.openResearchCenter=()=>scrollToId('research');window.openStageAccount=()=>location.href='/member.html';window.stageCheckout=()=>{location.href='/checkout.html'};
document.addEventListener('DOMContentLoaded',()=>{$('#searchInput')?.addEventListener('input',()=>{featuredOnly=false;renderProducts()});$('#categoryFilter')?.addEventListener('change',e=>{selectedCategory=e.target.value;featuredOnly=false;renderCategories();renderProducts()});$('#formatFilter')?.addEventListener('change',e=>{selectedFormat=e.target.value;featuredOnly=false;renderProducts()});$('#stockFilter')?.addEventListener('change',e=>{stockFilter=e.target.value;featuredOnly=false;renderProducts()});$('#sortFilter')?.addEventListener('change',e=>{sortMode=e.target.value;featuredOnly=false;renderProducts()});saveCart();loadData()});
})();
