(function(){
  const faqs=[
    ['How do I choose a product?','Each catalog item can have multiple strengths and formats. The storefront displays the Vial option first by default; use the format selector to switch to Pen, then select the required strength. Price, stock status and the product image update with the selected variation.'],
    ['What is included in the Prefilled Pen Set?','The Pen format includes the selected prefilled disposable pen together with compatible pen needles. Device preparation and needle handling require more explanation than a short FAQ, so follow the illustrated guide below.','pen'],
    ['What is included in the Vial Set?','The Vial Set includes the selected vial, BAC water and a reconstitution syringe set. Reconstitution, aseptic handling and post-reconstitution stability are explained in the full guide below.','vial'],
    ['What does cold chain mean for delivery?','Cold-chain packaging is temperature-conscious protective packaging designed to slow heat transfer and reduce unnecessary thermal exposure while a parcel is in transit. It should not be interpreted as a guarantee that an ordinary courier parcel remains at one exact refrigerator temperature every minute.'],
    ['What should I do when my parcel arrives?','Inspect the outer parcel and internal packaging for damage or leakage, then follow the storage information supplied for the actual product promptly. Avoid leaving temperature-sensitive materials in a hot vehicle, direct sunlight or another unnecessarily warm environment.'],
    ['How do I track my order?','After an SPX tracking number is assigned, the number and available tracking status can be shown in the Member Area. Tracking information may take time to appear after a parcel is first handed to the carrier.'],
    ['Where can I learn about the compounds?','The Research Catalog / Peptide Insights section separates molecular identity, pathways, research areas and evidence context from the shopping interface. It is intended as an educational research reference rather than individualized medical advice.']
  ];
  function row(q,a,i,guide){
    const guideButton=guide==='pen'?'<button class="faqguide" onclick="openFaqGuide(\'pen\')">Prefilled Disposable Pen Set — illustrated guide →</button>':guide==='vial'?'<button class="faqguide" onclick="openFaqGuide(\'vial\')">Read the full Vial Set & Reconstitution guide →</button>':'';
    return `<article class="faqrow"><button class="faqquestion" aria-expanded="false" onclick="toggleFaq(this)"><span>${q}</span><b>+</b></button><div class="faqanswer"><p>${a}</p>${i===2?`<div class="faqvideo"><iframe src="https://www.youtube-nocookie.com/embed/b08QwxZW0Ig" title="Vial reconstitution video tutorial" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>`:''}${guideButton}</div></article>`
  }
  const penGuide=`<div class="guidehead"><button class="guideback" onclick="closeFaqGuide()">← Back to FAQ</button><span>PRODUCT FORMAT GUIDE</span><h1>Prefilled Disposable Pen Set</h1><p>Illustrated-style device and handling guidance for the supplied disposable pen format.</p></div><div class="guidegrid">
    <article><b>01</b><h2>Check your pen</h2><p>Confirm the product name and strength and inspect the pen body, cartridge area and dose window for visible damage or leakage before handling.</p></article>
    <article><b>02</b><h2>Attach a fresh compatible needle</h2><p>Use a new compatible pen needle each time. Avoid using a bent, damaged or previously used needle.</p></article>
    <article><b>03</b><h2>Prepare the device</h2><p>Follow the supplied device instructions for the flow-check or priming step. Priming is a device-preparation step and should not be confused with the product-specific instructed setting.</p></article>
    <article><b>04</b><h2>Verify the instructed setting</h2><p>After preparation, read the dose window carefully and use only the instructions supplied for that exact product and concentration. Do not copy settings from another product or another person's device.</p></article>
    <article><b>05</b><h2>After use</h2><p>Remove the used needle according to the device instructions, dispose of it in an appropriate sharps container, recap the pen and avoid storing it with a used needle attached.</p></article>
    <article><b>06</b><h2>Storage & handling</h2><p>Protect the pen from unnecessary heat, direct sunlight and physical damage. Follow the product-specific storage information supplied with the order.</p></article>
  </div><div class="guidewarning"><b>Important</b><p>This guide explains device handling only. Product-specific concentration and use instructions take priority over general website guidance.</p></div>`;

  const vialGuide=`<div class="guidehead"><button class="guideback" onclick="closeFaqGuide()">← Back to FAQ</button><span>LABORATORY HANDLING GUIDE</span><h1>Vial Set & Reconstitution</h1><p>A practical explanation of the vial format, aseptic handling and why stability requirements are product-specific.</p></div><div class="guidebody">
    <article><h2>What is included?</h2><p>The Vial Set includes the selected vial, BAC water and a reconstitution syringe set.</p></article>
    <article><h2>What does reconstitution mean?</h2><p>Reconstitution adds an appropriate liquid back to a dry, lyophilized material. The correct diluent, final volume and stability conditions depend on the exact compound and formulation.</p></article>
    <article><h2>General laboratory principles</h2><h3>1. Confirm the product documentation</h3><p>Do not assume every vial uses the same diluent volume or handling conditions.</p><h3>2. Protect aseptic technique</h3><p>Use a clean working area and appropriate sterile equipment. Disinfect vial stoppers and avoid touching cleaned contact surfaces.</p><h3>3. Introduce diluent gently</h3><p>Add the selected diluent slowly to reduce unnecessary foaming or mechanical stress.</p><h3>4. Mix gently</h3><p>Gentle swirling is generally preferable to vigorous shaking unless the product-specific instructions state otherwise.</p></article>
    <article><h2>How long does it last after reconstitution?</h2><p>There is no scientifically responsible universal answer for every compound. Stability depends on the molecule, formulation, concentration, diluent, sterility, temperature, light exposure and handling.</p></article>
    <article><h2>Storage and inspection</h2><p>Follow the storage conditions applicable to the actual formulation. Check for leakage, damaged closure, unexpected particulate matter or an appearance inconsistent with the supplied information.</p></article>
    <article><h2>Video tutorial</h2><p>Use the video below as an additional visual reference. Product-specific documentation remains the primary reference.</p><div class="faqvideo"><iframe src="https://www.youtube-nocookie.com/embed/b08QwxZW0Ig" title="Vial reconstitution video tutorial" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div></article>
  </div>`;

  window.openFAQ=function(){let p=document.getElementById('faqPage');if(!p){p=document.createElement('section');p.id='faqPage';p.className='faqpage';document.body.appendChild(p)}p.innerHTML=`<div class="faqinner"><button class="faqclose" onclick="closeFAQ()">×</button><div class="faqhero"><span>AI BIOTECH KNOWLEDGE CENTRE</span><h1>Frequently Asked Questions</h1><p>Practical information about product formats, handling, storage, cold-chain delivery, orders and research resources.</p></div><div class="faqintro"><b>Quick answers. Detailed guides when you need them.</b><p>Open a question for the short answer. Topics that need more explanation include a dedicated guide below.</p></div><div class="faqlist">${faqs.map((x,i)=>row(x[0],x[1],i,x[2])).join('')}</div><div id="faqGuidePane" class="faqguidepane"></div></div>`;p.classList.add('show');document.body.style.overflow='hidden'};
  window.closeFAQ=function(){const p=document.getElementById('faqPage');if(p)p.classList.remove('show');document.body.style.overflow=''};
  window.toggleFaq=function(btn){const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));btn.querySelector('b').textContent=open?'+':'−';btn.parentElement.classList.toggle('open',!open)};
  window.openFaqGuide=function(kind){const pane=document.getElementById('faqGuidePane');if(!pane)return;pane.innerHTML=kind==='pen'?penGuide:vialGuide;pane.classList.add('show');pane.scrollTop=0};
  window.closeFaqGuide=function(){const pane=document.getElementById('faqGuidePane');if(pane)pane.classList.remove('show')};
})();