(function(){
  const faqs=[
    ['How do I choose a product?','Start with the research area you want to understand, then open the product information and Research Center profile. Each product can have different strengths and formats, so always confirm the exact variant before adding it to cart.'],
    ['What is the difference between Vial, Cartridge and Pen?','Vial is a standalone container that uses separate preparation and handling equipment. Cartridge is a sealed container designed for a compatible reusable device. Prefilled Pen is a complete disposable device with the solution chamber already integrated into the pen body.'],
    ['What is included in the Prefilled Pen Set?','The Pen format includes the selected prefilled disposable pen together with compatible pen needles and the accessories supplied with the current pack. Device preparation, storage and needle handling are explained in the illustrated Pen Guide.','pen'],
    ['What is included in the Vial Set?','The Vial Set includes the selected vial, bacteriostatic water where applicable and the preparation accessories supplied with the current pack. Reconstitution, concentration concepts and storage are explained in the full Vial Guide.','vial'],
    ['What is included with the Cartridge format?','The Cartridge format includes the selected sealed cartridge. A compatible reusable device may be required depending on how the cartridge is intended to be handled. Always confirm device compatibility before installation.','cartridge'],
    ['How do I know which strength and format I selected?','The selected strength and format are shown directly on the product card before you add it to cart. The price, stock status and product visual update with the selected variant. Your cart also shows the exact strength and format again before checkout.'],
    ['Why does the price change when I change strength or format?','Each strength and format is a separate catalog variant with its own price and stock record. The storefront always displays the price for the exact variant currently selected.'],
    ['What does “Sold Out” mean?','Stock is tracked by exact product, strength and format. One variant can be sold out while another strength or format of the same product is still available. Sold out variants cannot be added to cart.'],
    ['What does cold chain mean for delivery?','Cold-chain packaging means temperature-conscious protective packaging designed to slow heat transfer and reduce unnecessary thermal exposure during transit. It does not mean an ordinary courier parcel is guaranteed to stay at one exact refrigerator temperature every minute.','coldchain'],
    ['What should I do when my parcel arrives?','Inspect the outer parcel and internal packaging, check the product containers for damage or leakage, confirm the correct product and strength arrived, then move the product promptly to the storage condition stated for the exact formulation.','coldchain'],
    ['What if my parcel feels warm?','A warm outer parcel or warmed coolant does not by itself show the exact temperature history of the product. Move the item to the stated storage condition, keep the packaging if you are concerned and contact support if the product condition or transit history is uncertain.','coldchain'],
    ['What should I do if the parcel is damaged?','Keep the packaging, photograph the outer parcel, internal packaging, product container, label and any visible leakage or breakage, then contact support with the order and tracking details.'],
    ['How do I track my order?','After a tracking number is assigned, the number and available shipment status can be shown in the Member Area. Courier tracking scans may take time to appear after handover.'],
    ['Where can I see my orders and invoices?','Sign in to the Member Area. Your order history, invoice access, payment status and shipment information are kept together there.'],
    ['Can I save my delivery address?','Yes. The Member Area includes Profile & Addresses so you can save and manage delivery details for checkout. Always review the selected address before placing an order.'],
    ['What does the checkout summary show?','The secure summary shows catalog subtotal, role or quantity savings where applicable, voucher discount, shipping, wallet usage, grand total and amount due. The server revalidates price, stock and checkout rules before order creation.'],
    ['How do vouchers and wallet work?','When those features are enabled, checkout can validate an eligible voucher and available wallet balance. The final usable amount is rechecked by the server before the order is created.'],
    ['Where can I learn about the compounds?','Open the Research Center. Each active catalog product has a research profile covering molecular identity, targets or pathways, research areas, evidence context, development status, catalog strengths and public literature links.'],
    ['What are Protocols?','Protocols are separate from public Research Center information. Access is controlled by the exact purchased product, strength and format where protocol entitlement is available. Public research pages do not automatically grant protocol access.'],
    ['What if I cannot find a guide or product detail?','Do not guess. Use the AI BioTech Assistant, open the Research Center or contact support. If a guide or product detail has not been approved yet, the website should say so clearly instead of showing a broken or placeholder action.'],
    ['Is the AI BioTech Assistant a human?','No. It is an AI assistant designed to answer catalog and research questions in a friendly, easy-to-understand way. It can make mistakes, so important research information should be checked against the referenced sources.'],
    ['Can I ask the AI in English, BM or Chinese?','Yes. You can use English, Bahasa Malaysia, 中文 or a natural mix. The assistant is designed to understand common Malaysian wording and keep the explanation simple and comfortable.'],
    ['What is Deep Search?','Deep Search is the slower research mode. It checks a broader set of sources, compares evidence and returns a more detailed answer. Public answers should show suitable research references while internal source discovery remains private.'],
    ['What does “Research Use Only” mean on this website?','The Research Center, calculator and guides are educational research tools. They do not diagnose a condition, prescribe treatment or replace individualized advice from a qualified healthcare professional.']
  ];
  function row(q,a,i,guide){
    const guideButton=guide==='pen'?'<button class="faqguide" onclick="closeFAQ();openGuides(\'pen\')">Open Prefilled Pen Guide →</button>':guide==='vial'?'<button class="faqguide" onclick="closeFAQ();openGuides(\'vial\')">Open Vial & Reconstitution Guide →</button>':guide==='cartridge'?'<button class="faqguide" onclick="closeFAQ();openGuides(\'cartridge\')">Open Cartridge Guide →</button>':guide==='coldchain'?'<button class="faqguide" onclick="closeFAQ();openGuides(\'coldchain\')">Open Cold Chain & Receiving Guide →</button>':'';
    return `<article class="faqrow"><button class="faqquestion" aria-expanded="false" onclick="toggleFaq(this)"><span>${q}</span><b>+</b></button><div class="faqanswer"><p>${a}</p>${i===3?`<div class="faqvideo"><iframe src="https://www.youtube-nocookie.com/embed/b08QwxZW0Ig" title="Vial reconstitution video tutorial" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" loading="lazy" allowfullscreen></iframe></div>`:''}${guideButton}</div></article>`
  }
  window.openFAQ=function(){let p=document.getElementById('faqPage');if(!p){p=document.createElement('section');p.id='faqPage';p.className='faqpage';document.body.appendChild(p)}p.innerHTML=`<div class="faqinner"><button class="faqclose" onclick="closeFAQ()">×</button><div class="faqhero"><span>AI BIOTECH KNOWLEDGE CENTRE</span><h1>Frequently Asked Questions</h1><p>Detailed answers about product formats, guides, cold-chain delivery, orders, Member Area, Research Center, calculator and AI support.</p></div><div class="faqintro"><b>Quick answer first, full guide when you need more.</b><p>Open any question below. Topics that need a full walkthrough link directly to the correct guide.</p></div><div class="faqlist">${faqs.map((x,i)=>row(x[0],x[1],i,x[2])).join('')}</div></div>`;p.classList.add('show');document.body.style.overflow='hidden';p.scrollTop=0};
  window.closeFAQ=function(){const p=document.getElementById('faqPage');if(p)p.classList.remove('show');document.body.style.overflow=''};
  window.toggleFaq=function(btn){const open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));btn.querySelector('b').textContent=open?'+':'−';btn.parentElement.classList.toggle('open',!open)};
})();