(function(){
  'use strict';
  const stepBase='https://simple-commerce-8rxct4.v2.appdeploy.ai/resources/pen-guide-step-';
  const reconstitutionVideo='https://www.youtube-nocookie.com/embed/b08QwxZW0Ig';
  const steps=[
    ['CHECK YOUR PEN','Confirm the product name, strength, label condition and device condition before handling.'],
    ['ATTACH A NEW NEEDLE','Use a fresh compatible needle and attach it securely without forcing the connection.'],
    ['PRIME THE PEN','Use the device priming step only as instructed. Priming is not the actual instructed setting.'],
    ['SET THE INSTRUCTED UNITS','After priming, set only the units specified for the exact product and protocol supplied to you.'],
    ['ADMINISTER AS DIRECTED','Follow the exact product and device instructions supplied for the selected variant.'],
    ['REMOVE THE NEEDLE','Remove the used needle after use and avoid storing the pen with a needle attached.'],
    ['DISPOSE AND STORE','Place used sharps into an appropriate sharps container, recap the device and follow product specific storage information.']
  ];

  const checklist=items=>`<ul class="guidechecklist">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
  const callout=(title,text,type='info')=>`<div class="guidecallout ${type}"><b>${title}</b><p>${text}</p></div>`;
  const nav=items=>`<nav class="guidejump" aria-label="On this page">${items.map(([id,label])=>`<a href="#${id}" onclick="document.getElementById('${id}')?.scrollIntoView({behavior:'smooth',block:'start'});return false">${label}</a>`).join('')}</nav>`;

  const pen=`
  <div class="guidehero penhero"><span>PRODUCT FORMAT GUIDE</span><h1>PREFILLED<br>DISPOSABLE PEN SET</h1><h2>COMPLETE HANDLING GUIDE</h2><p>A clearer visual walkthrough covering what to check, device parts, preparation, the seven illustrated steps, storage and common problems.</p></div>
  ${nav([['pen-contents','What comes in the set'],['pen-parts','Know your pen'],['pen-before','Before you begin'],['pen-steps','7 illustrated steps'],['pen-after','After use'],['pen-trouble','Troubleshooting']])}
  <div class="guidebody">
    <article id="pen-contents"><h2>What comes in the Prefilled Pen Set?</h2><p>The exact pack can vary by product, but the set is built around the selected prefilled disposable pen and the handling accessories supplied with that order.</p>${checklist(['Selected AI BioTech prefilled disposable pen','Compatible pen needles supplied with the set','Alcohol swabs and support accessories according to the current pack','Product specific information or protocol access where applicable'])}${callout('Check before using','Always match the product name and strength on the pen to the exact product you intended to handle. If the label is unclear or the device looks damaged, stop and confirm first.','caution')}</article>
    <article id="pen-parts"><h2>Know your pen</h2><div class="guideparts"><div><b>Pen cap</b><span>Protects the front of the device during storage.</span></div><div><b>Product label</b><span>Shows the compound identity and strength.</span></div><div><b>Cartridge or solution chamber</b><span>Contains the prepared formulation inside the device.</span></div><div><b>Needle connection</b><span>Where a compatible fresh needle is attached.</span></div><div><b>Dose window</b><span>Shows the selected device units.</span></div><div><b>Dose selector and button</b><span>Used according to the device instructions supplied for the exact product.</span></div></div></article>
    <article id="pen-before"><h2>Before you begin</h2>${checklist(['Wash and dry your hands','Prepare a clean working surface','Confirm product name and strength','Inspect the pen for cracks, leakage or obvious damage','Check the solution appearance against the supplied information','Prepare a fresh compatible needle','Keep the pen capped until you are ready to handle it'])}<p>Do not rely on label colour alone. Read the product name and strength directly.</p></article>
  </div>
  <div id="pen-steps" class="pensteps">${steps.map((s,i)=>{const n=i+1;return `<section class="penstep ${n===3?'prime':''}"><div class="pensteptitle"><b>${n}</b><div><h2>${s[0]}</h2><p>${s[1]}</p></div></div>${n===3?'<div class="primealert"><b>IMPORTANT:</b> PRIMING ONLY, NOT THE ACTUAL INSTRUCTED SETTING.</div>':''}<a href="${stepBase+n}.png" target="_blank" rel="noopener noreferrer"><img src="${stepBase+n}.png" data-guide-step="${n}" alt="Pen Guide Step ${n}, ${s[0]}" loading="${n>2?'lazy':'eager'}" decoding="async"></a></section>`}).join('')}</div>
  <div class="guidebody">
    <article id="pen-after"><h2>After use</h2>${checklist(['Remove the used needle carefully','Dispose of the used needle in an appropriate sharps container','Do not store the pen with the needle attached','Replace the pen cap','Return the pen to the storage condition stated for the exact formulation','Keep away from direct heat, strong light and children'])}<p>Storage conditions can differ between formulations. The product specific storage instruction takes priority over a generic guide.</p></article>
    <article id="pen-trouble"><h2>Common problems and what to check</h2><div class="guideissues"><div><b>Needle will not attach</b><p>Do not force it. Confirm needle compatibility and try a fresh needle.</p></div><div><b>Pen leaks</b><p>Stop using the device and inspect the connection and body. A damaged or leaking pen should be reviewed before further handling.</p></div><div><b>Label or strength cannot be read</b><p>Do not guess. Confirm the exact product before continuing.</p></div><div><b>Selector does not move normally</b><p>Do not force the mechanism. Review the device instructions or contact support.</p></div><div><b>Unexpected solution appearance</b><p>Do not assume it is normal. Compare with the product information and ask for review if uncertain.</p></div></div></article>
  </div>
  ${callout('Important','The illustrated pen guide explains device handling. It does not replace the exact product protocol or individualized medical advice.','caution')}`;

  const vial=`
  <div class="guidehero"><span>VIAL PREPARATION GUIDE</span><h1>Vial Set & Reconstitution</h1><p>A more complete visual and written guide covering the set contents, preparation sequence, concentration concepts, storage and the embedded reconstitution video you selected.</p></div>
  ${nav([['vial-contents','What comes in the set'],['vial-before','Before preparation'],['vial-steps','Reconstitution workflow'],['vial-concentration','Understanding concentration'],['vial-after','After reconstitution'],['vial-video','Video tutorial']])}
  <div class="guidebody">
    <article id="vial-contents"><h2>What comes in the Vial Set?</h2><p>The exact pack depends on the product, but the typical Vial Set contains the selected vial, bacteriostatic water and preparation accessories supplied with that order.</p>${checklist(['Selected product vial','Bacteriostatic water where included for that product','Reconstitution syringe and preparation accessory','Alcohol swabs and support accessories according to the current set','Product specific protocol or preparation information where applicable'])}${callout('Do not use one universal liquid volume','Different products and strengths can require different final preparation volumes. The exact product protocol takes priority over generic examples.','caution')}</article>
    <article id="vial-before"><h2>Before preparation</h2>${checklist(['Confirm the compound name and strength','Inspect the vial and stopper for damage','Inspect the diluent container and seal','Prepare a clean work area','Wash and dry your hands','Prepare the correct sterile equipment','Confirm the exact final volume from the approved product protocol'])}<p>If the vial, stopper, label or diluent is damaged or unclear, stop before preparation and confirm the product details.</p></article>
    <article id="vial-steps"><h2>Reconstitution workflow</h2><div class="guidesteps"><div><b>1</b><h3>Prepare the work area</h3><p>Use a clean, dry surface and arrange the vial, diluent, sterile equipment and swabs before starting.</p></div><div><b>2</b><h3>Confirm the exact product</h3><p>Read the product name, strength and supplied preparation information. Do not assume two different strengths use the same final volume.</p></div><div><b>3</b><h3>Clean contact surfaces</h3><p>Disinfect the vial stopper and any access surface according to appropriate aseptic practice, then allow it to dry.</p></div><div><b>4</b><h3>Prepare the specified liquid volume</h3><p>Use the volume stated for the exact product protocol. The calculator can help with arithmetic, but it should not invent a preparation volume.</p></div><div><b>5</b><h3>Introduce the liquid gently</h3><p>Allow the liquid to enter gently against the inside wall where practical, reducing unnecessary foaming or mechanical stress.</p></div><div><b>6</b><h3>Allow the material to dissolve</h3><p>Gentle swirling is generally preferable to aggressive shaking unless the product specific documentation says otherwise.</p></div><div><b>7</b><h3>Inspect the prepared solution</h3><p>Check for leakage, damaged closure, unexpected particles or an appearance inconsistent with the supplied information.</p></div><div><b>8</b><h3>Record and store</h3><p>Note the preparation information if required and move the vial promptly to the applicable product specific storage condition.</p></div></div></article>
    <article id="vial-concentration"><h2>Understanding concentration</h2><p>The final concentration depends on two things, the total amount of material in the vial and the final liquid volume.</p><div class="guideformula"><b>Concentration = total material ÷ final liquid volume</b><span>Example arithmetic belongs in the Peptide Calculator. This guide does not choose a target amount or dosing schedule.</span></div><p>Use the Calculator when you already know the verified vial amount, final liquid volume and target research amount from an approved protocol.</p><button class="faqguide" type="button" onclick="location.href='/peptide-calculator.html'">Open Peptide Calculator →</button></article>
    <article id="vial-after"><h2>After reconstitution</h2>${checklist(['Keep the stopper and access area clean','Minimize unnecessary repeated temperature exposure','Protect from strong light when required by the formulation','Follow the exact product storage information','Do not use a damaged or leaking vial','Review unexpected cloudiness, colour change or particles before continuing'])}<h3>How long does it last?</h3><p>There is no responsible universal answer for every compound. Stability depends on the molecule, formulation, concentration, diluent, sterility, temperature, light exposure and handling. Product specific information takes priority.</p></article>
    <article id="vial-video"><h2>How to reconstitute, video tutorial</h2><p>This embedded video is an additional visual reference. Always use the exact product protocol for the final preparation volume and product specific handling information.</p><div class="faqvideo"><iframe src="${reconstitutionVideo}" title="Peptide reconstitution instructions" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" loading="lazy" allowfullscreen></iframe></div></article>
  </div>`;

  const cartridge=`
  <div class="guidehero"><span>CARTRIDGE FORMAT GUIDE</span><h1>Cartridge Handling Guide</h1><p>Understand the cartridge format, how it differs from a vial or disposable pen, what to inspect and the general installation sequence for a compatible reusable device.</p></div>
  ${nav([['cart-what','What is a cartridge'],['cart-parts','Cartridge anatomy'],['cart-before','Before installation'],['cart-install','General installation'],['cart-after','After handling'],['cart-trouble','Troubleshooting']])}
  <div class="guidebody">
    <article id="cart-what"><h2>What is the Cartridge format?</h2><p>A cartridge is a sealed cylindrical container designed to sit inside a compatible reusable pen style device. It is different from a standalone vial and different from a complete disposable prefilled pen.</p><div class="guidecompare"><div><b>Vial</b><p>Standalone container used with separate preparation and handling equipment.</p></div><div><b>Cartridge</b><p>Sealed cartridge intended to be fitted into a compatible reusable device.</p></div><div><b>Prefilled Pen</b><p>Complete disposable device with the solution chamber already integrated into the pen body.</p></div></div>${callout('Compatibility matters','A cartridge should only be installed into a device that is designed for that cartridge size and connection. Never force a cartridge into an incompatible holder.','caution')}</article>
    <article id="cart-parts"><h2>Cartridge anatomy</h2><div class="guideparts"><div><b>Front closure</b><span>The sealed front end accessed by the compatible device and needle system.</span></div><div><b>Glass body</b><span>The main cartridge container. Inspect it for cracks or chips.</span></div><div><b>Product label</b><span>Should clearly show the compound and strength.</span></div><div><b>Solution area</b><span>The visible prepared formulation inside the cartridge.</span></div><div><b>Rear plunger</b><span>Moves forward when the compatible reusable device advances its drive mechanism.</span></div></div></article>
    <article id="cart-before"><h2>Before installation</h2>${checklist(['Confirm the product name and strength','Confirm the reusable device is compatible with the cartridge','Inspect the glass body for cracks or damage','Inspect the rear plunger and front closure','Check the solution appearance against the supplied information','Make sure the reusable device is clean and functioning normally','Use a fresh compatible needle when the device instructions call for it'])}</article>
    <article id="cart-install"><h2>General reusable device installation sequence</h2><p>Reusable pen designs vary, so the manufacturer instructions for the actual device always take priority. A common sequence is:</p><div class="guidesteps"><div><b>1</b><h3>Remove the device cap</h3><p>Expose the cartridge holder according to the reusable device instructions.</p></div><div><b>2</b><h3>Open the cartridge holder</h3><p>Detach or unscrew the holder without forcing the threads or locking mechanism.</p></div><div><b>3</b><h3>Reset the drive mechanism</h3><p>If the reusable device requires the internal drive rod to be returned before fitting a new cartridge, follow the manufacturer method exactly.</p></div><div><b>4</b><h3>Insert the cartridge in the correct orientation</h3><p>Place the cartridge straight into the holder. Do not drop it in or force it past resistance.</p></div><div><b>5</b><h3>Reattach the holder</h3><p>Align the holder with the device body and secure it fully according to the device instructions.</p></div><div><b>6</b><h3>Attach a fresh compatible needle</h3><p>Use the compatible needle system specified for the reusable device.</p></div><div><b>7</b><h3>Prime according to the device instructions</h3><p>Priming confirms the device and cartridge are delivering correctly. Priming is not the same as the actual instructed setting.</p></div></div></article>
    <article id="cart-after"><h2>After handling</h2>${checklist(['Remove the used needle according to the device instructions','Do not store the reusable device with a needle attached','Replace the device cap','Store according to the exact product and device requirements','Protect the cartridge from impact and unnecessary heat','Keep the cartridge label readable throughout use'])}</article>
    <article id="cart-trouble"><h2>Common cartridge problems</h2><div class="guideissues"><div><b>Cartridge does not seat correctly</b><p>Remove it and check orientation and compatibility. Do not force the holder closed.</p></div><div><b>Glass is cracked or chipped</b><p>Do not continue using the cartridge.</p></div><div><b>Leakage is visible</b><p>Stop and inspect the cartridge, needle connection and device holder.</p></div><div><b>Rear plunger looks damaged or displaced</b><p>Do not force the drive mechanism. Review the device and cartridge before further handling.</p></div><div><b>Label is unreadable</b><p>Do not guess the product or strength.</p></div><div><b>Unexpected solution appearance</b><p>Compare with the product information and request review if uncertain.</p></div></div></article>
  </div>`;

  const coldchain=`
  <div class="guidehero"><span>SHIPPING AND RECEIVING GUIDE</span><h1>Cold Chain, Packaging & Receiving</h1><p>A clear explanation of what temperature conscious packaging can and cannot do, how the parcel is protected and what to check when it arrives.</p></div>
  ${nav([['cold-meaning','What cold chain means'],['cold-pack','Packaging layers'],['cold-transit','During transit'],['cold-arrival','When it arrives'],['cold-damage','If there is damage'],['cold-warm','If the parcel feels warm']])}
  <div class="guidebody">
    <article id="cold-meaning"><h2>What “cold chain” means for ordinary courier delivery</h2><p>Insulated and cooled packaging is designed to slow heat transfer and reduce unnecessary thermal exposure during transit. It does not mean an ordinary courier parcel stays at one exact refrigerator temperature every minute until delivery.</p>${callout('Important distinction','A validated pharmaceutical cold chain with continuous temperature monitoring is different from ordinary insulated courier packaging. We should not promise a constant internal temperature unless the shipment is actually validated and monitored that way.','caution')}</article>
    <article id="cold-pack"><h2>How the parcel is protected</h2><div class="guidesteps"><div><b>1</b><h3>Internal product protection</h3><p>The selected product is protected against movement and direct impact.</p></div><div><b>2</b><h3>Accessory packing</h3><p>Accessories are separated and packed so they do not damage the primary product container.</p></div><div><b>3</b><h3>Protective box</h3><p>A rigid or semi rigid box adds another barrier against crushing and movement.</p></div><div><b>4</b><h3>Insulated layer</h3><p>Temperature conscious packaging slows heat transfer between the parcel interior and the surrounding environment where applicable.</p></div><div><b>5</b><h3>Outer discreet protection</h3><p>The final outer layer provides additional cushioning, sealing and discreet handling.</p></div></div></article>
    <article id="cold-transit"><h2>What happens during transit?</h2><p>Cooling material absorbs heat as the parcel travels. Its cooling capacity is finite and changes with transit duration, outside temperature, package size, coolant amount and courier conditions.</p>${checklist(['Tracking may not update at every physical movement','A delayed scan does not automatically mean the parcel is lost','Avoid unnecessary delivery delays where possible','Arrange collection promptly if the courier is holding the parcel','Move the product to the appropriate storage condition soon after receipt'])}</article>
    <article id="cold-arrival"><h2>When your parcel arrives</h2>${checklist(['Inspect the outer package before opening','Photograph obvious external damage before removing the contents','Open the parcel carefully and inspect the internal protective layers','Check the product container for cracks, leakage or compromised closure','Confirm the correct product and strength arrived','Move the product promptly to its applicable storage condition'])}</article>
    <article id="cold-damage"><h2>If the parcel is damaged</h2><p>Keep the packaging and document the condition before discarding anything.</p>${checklist(['Take a clear photo of the outer parcel','Take photos of the internal packaging','Photograph the product container and label','Show any leakage, crack, broken seal or obvious damage clearly','Keep the shipping label and tracking number available','Contact support with the photos and order details'])}</article>
    <article id="cold-warm"><h2>If the parcel feels warm</h2><p>A warm outer parcel or melted coolant does not, by itself, tell you the exact temperature history of the product. Review the exact product storage and stability information rather than guessing from how the outside of the package feels.</p>${callout('What to do','Move the product to the stated storage condition, keep the packaging if you are concerned, and contact support when the product condition or temperature exposure is uncertain.','info')}</article>
  </div>`;

  function installGuideImageFallback(host){
    host.querySelectorAll('img[data-guide-step]').forEach(img=>{
      img.addEventListener('error',()=>{
        const n=Number(img.dataset.guideStep||0),info=steps[n-1]||['PEN GUIDE','Visual temporarily unavailable.'];
        const fallback=document.createElement('div');fallback.className='guide-image-fallback';fallback.innerHTML='<b></b><h3></h3><p></p>';
        fallback.querySelector('b').textContent=`STEP ${n||''}`.trim();fallback.querySelector('h3').textContent=info[0];fallback.querySelector('p').textContent=info[1];
        const anchor=img.closest('a');if(anchor)anchor.replaceWith(fallback);else img.replaceWith(fallback);
      },{once:true});
    });
  }

  window.openGuides=function(kind='home'){
    let p=document.getElementById('guidesPage');if(!p){p=document.createElement('section');p.id='guidesPage';p.className='guidespage';document.body.appendChild(p)}
    const home=`<div class="guidehero"><span>AI BIOTECH KNOWLEDGE CENTRE</span><h1>Product & Handling Guides</h1><p>Detailed format, preparation, receiving and storage guidance in one place. Choose the guide that matches what you are handling.</p></div><div class="guidecards four"><button type="button" onclick="openGuides('pen')"><b>Prefilled Disposable Pen Set</b><p>Complete device handling, seven illustrated steps, storage and troubleshooting.</p><span>Open Pen Guide →</span></button><button type="button" onclick="openGuides('vial')"><b>Vial Set & Reconstitution</b><p>Preparation workflow, concentration concepts, storage and embedded video.</p><span>Open Vial Guide →</span></button><button type="button" onclick="openGuides('cartridge')"><b>Cartridge Handling</b><p>Cartridge anatomy, reusable device installation concepts and troubleshooting.</p><span>Open Cartridge Guide →</span></button><button type="button" onclick="openGuides('coldchain')"><b>Cold Chain & Receiving</b><p>Packaging layers, transit expectations, receiving checks and damage procedure.</p><span>Open Shipping Guide →</span></button></div>`;
    const content=kind==='pen'?pen:kind==='vial'?vial:kind==='cartridge'?cartridge:kind==='coldchain'?coldchain:home;
    p.innerHTML=`<div class="guidesinner"><button type="button" class="faqclose" onclick="closeGuides()" aria-label="Close guides">×</button>${kind!=='home'?'<button type="button" class="guideback" onclick="openGuides(\'home\')">← Back to Guides</button>':''}${content}</div>`;
    installGuideImageFallback(p);p.classList.add('show');document.body.style.overflow='hidden';p.scrollTop=0;
  };
  window.openGuide=function(kind){const map={cold:'coldchain',coldchain:'coldchain',pen:'pen',vial:'vial',cartridge:'cartridge',home:'home'};window.openGuides(map[kind]||'home')};
  window.closeGuides=function(){const p=document.getElementById('guidesPage');if(p)p.classList.remove('show');document.body.style.overflow=''};

  function ensureStyle(href,id){if(document.getElementById(id))return;const css=document.createElement('link');css.id=id;css.rel='stylesheet';css.href=href;document.head.appendChild(css)}
  function ensureScript(src,id){if(document.getElementById(id))return;const js=document.createElement('script');js.id=id;js.src=src;js.defer=true;document.body.appendChild(js)}
  function wireResearch(){
    const blend=[...document.querySelectorAll('.nav button')].find(b=>/BLENDS|RESEARCH/i.test(b.textContent||''));if(blend){blend.textContent='⌘ RESEARCH';blend.onclick=()=>window.openResearch&&window.openResearch()}
    const panel=[...document.querySelectorAll('.panels>div')].find(x=>/RESEARCH CATALOG/i.test(x.textContent||''));if(panel){panel.style.cursor='pointer';panel.onclick=()=>window.openResearch&&window.openResearch()}
    ensureScript('/research-enhance.js','aibtResearchEnhance');ensureScript('/research-detail-full.js','aibtResearchFull');
  }
  ensureStyle('/research.css','aibtResearchCss');if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wireResearch,{once:true});else wireResearch();
})();