(function(){
  const pen=`<div class="guidehero"><span>PRODUCT FORMAT GUIDE</span><h1>Prefilled Disposable Pen Set</h1><p>Illustrated-style device and handling guidance for the supplied disposable pen format.</p></div><div class="guidecards"><article><b>01</b><h2>Check your pen</h2><p>Confirm the product name and strength and inspect the pen body, cartridge area and dose window for visible damage or leakage before handling.</p></article><article><b>02</b><h2>Attach a fresh compatible needle</h2><p>Use a new compatible pen needle each time. Avoid using a bent, damaged or previously used needle.</p></article><article><b>03</b><h2>Prepare the device</h2><p>Follow the supplied device instructions for the flow-check or priming step. Priming is a device-preparation step and should not be confused with the product-specific instructed setting.</p></article><article><b>04</b><h2>Verify the instructed setting</h2><p>After preparation, read the dose window carefully and use only the instructions supplied for that exact product and concentration. Do not copy settings from another product or another person's device.</p></article><article><b>05</b><h2>After use</h2><p>Remove the used needle according to the device instructions, dispose of it in an appropriate sharps container, recap the pen and avoid storing it with a used needle attached.</p></article><article><b>06</b><h2>Storage & handling</h2><p>Protect the pen from unnecessary heat, direct sunlight and physical damage. Follow the product-specific storage information supplied with the order.</p></article></div><div class="guidewarning"><b>Important</b><p>This guide explains device handling only. Product-specific concentration and use instructions take priority over general website guidance.</p></div>`;
  const vial=`<div class="guidehero"><span>LABORATORY HANDLING GUIDE</span><h1>Vial Set & Reconstitution</h1><p>A practical explanation of the vial format, aseptic handling and why stability requirements are product-specific.</p></div><div class="guidebody"><article><h2>What is included?</h2><p>The Vial Set includes the selected vial, BAC water and a reconstitution syringe set.</p></article><article><h2>What does reconstitution mean?</h2><p>Reconstitution adds an appropriate liquid back to a dry, lyophilized material. The correct diluent, final volume and stability conditions depend on the exact compound and formulation.</p></article><article><h2>General laboratory principles</h2><h3>1. Confirm the product documentation</h3><p>Do not assume every vial uses the same diluent volume or handling conditions.</p><h3>2. Protect aseptic technique</h3><p>Use a clean working area and appropriate sterile equipment. Disinfect vial stoppers and avoid touching cleaned contact surfaces.</p><h3>3. Introduce diluent gently</h3><p>Add the selected diluent slowly to reduce unnecessary foaming or mechanical stress.</p><h3>4. Mix gently</h3><p>Gentle swirling is generally preferable to vigorous shaking unless the product-specific instructions state otherwise.</p></article><article><h2>How long does it last after reconstitution?</h2><p>There is no scientifically responsible universal answer for every compound. Stability depends on the molecule, formulation, concentration, diluent, sterility, temperature, light exposure and handling.</p></article><article><h2>Storage and inspection</h2><p>Follow the storage conditions applicable to the actual formulation. Check for leakage, damaged closure, unexpected particulate matter or an appearance inconsistent with the supplied information.</p></article><article><h2>Video tutorial</h2><p>Use the video below as an additional visual reference. Product-specific documentation remains the primary reference.</p><div class="faqvideo"><iframe src="https://www.youtube-nocookie.com/embed/b08QwxZW0Ig" title="Vial reconstitution video tutorial" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div></article></div>`;
  window.openGuides=function(kind='home'){
    let p=document.getElementById('guidesPage');if(!p){p=document.createElement('section');p.id='guidesPage';p.className='guidespage';document.body.appendChild(p)}
    const home=`<div class="guidehero"><span>AI BIOTECH GUIDES</span><h1>Product & Handling Guides</h1><p>Choose a guide below.</p></div><div class="guidecards"><button onclick="openGuides('pen')"><b>Prefilled Disposable Pen Set</b><span>Illustrated guide →</span></button><button onclick="openGuides('vial')"><b>Vial Set & Reconstitution</b><span>Full guide →</span></button></div>`;
    p.innerHTML=`<div class="guidesinner"><button class="faqclose" onclick="closeGuides()">×</button>${kind!=='home'?'<button class="guideback" onclick="openGuides(\'home\')">← Back to Guides</button>':''}${kind==='pen'?pen:kind==='vial'?vial:home}</div>`;
    p.classList.add('show');document.body.style.overflow='hidden';
  };
  window.closeGuides=function(){const p=document.getElementById('guidesPage');if(p)p.classList.remove('show');document.body.style.overflow=''};
})();