(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const routes=['/','/member.html','/checkout.html','/ops.html'];let last=[];
function head(){document.querySelector('#opsTitle').textContent='Website Health';document.querySelector('#opsSubtitle').textContent='Button, route, asset and staging-isolation QA';document.querySelectorAll('#opsNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='health'));document.querySelector('#opsSidebar')?.classList.remove('show')}
function row(name,status,detail,extra=''){return `<div class="scan-row"><b>${esc(name)}</b><span class="scan-status ${status}">${status==='ok'?'WORKING':status==='warn'?'WARNING':'BROKEN'}</span><div class="scan-detail">${esc(detail)}</div>${extra}</div>`}
function summary(){const ok=last.filter(x=>x.status==='ok').length,warn=last.filter(x=>x.status==='warn').length,bad=last.filter(x=>x.status==='bad').length,total=last.length,score=total?Math.round((ok+.5*warn)/total*100):100;return {ok,warn,bad,total,score}}
function render(){head();const s=summary();$('#opsContent').innerHTML=`<div class="health-hero"><section class="card"><div class="card-head"><div><h2>Button & Route QA Scanner</h2><p class="muted">Scans the active staging storefront, Member Area, Checkout and Operations Center. No production requests are made.</p></div><div class="health-actions"><button class="btn primary" onclick="runWebsiteHealthScan()">Run Full Scan</button><button class="btn" onclick="showWebsiteHealthContract()">View Release Contract</button></div></div><div class="health-grid"><div class="health-box"><small>Working</small><b>${s.ok}</b></div><div class="health-box"><small>Warnings</small><b>${s.warn}</b></div><div class="health-box"><small>Broken</small><b>${s.bad}</b></div><div class="health-box"><small>Checks</small><b>${s.total}</b></div></div></section><div class="health-score"><div><b>${s.score}%</b><small>INTERACTION HEALTH</small></div></div></div><section class="card health-section"><div class="card-head"><h2>Scan Results</h2><span class="badge ${s.bad?'red':s.warn?'amber':'green'}">${s.bad?'RELEASE BLOCKED':s.warn?'REVIEW REQUIRED':'GATE CLEAR'}</span></div><div id="healthRows">${last.length?last.map(x=>row(x.name,x.status,x.detail)).join(''):'<div class="empty">Run the scanner to test the current staging preview.</div>'}</div></section><section class="card health-section"><div class="card-head"><h2>Static CI Gates</h2></div><div class="scan-row"><b>GitHub CI</b><span class="scan-status ok">ENFORCED</span><div class="scan-detail">Route/asset check, interaction contract check, staging isolation, AI isolation and JavaScript syntax run on every staging commit.</div><div></div></div><div class="scan-row"><b>Supabase Security</b><span class="scan-status ok">CLEAN</span><div class="scan-detail">Public API uses invoker wrappers; privileged implementations remain in the private schema.</div><div></div></div><div class="scan-row"><b>Production Writes</b><span class="scan-status ok">BLOCKED</span><div class="scan-detail">Staging config targets only ${esc(cfg.supabaseUrl||'isolated staging')}.</div><div></div></div></section>`}
async function fetchText(url){const r=await fetch(url,{cache:'no-store',credentials:'same-origin'});return {ok:r.ok,status:r.status,text:await r.text()}}
function scriptPaths(doc){return [...doc.querySelectorAll('script[src]')].map(s=>s.getAttribute('src')).filter(x=>x&&x.startsWith('/')).map(x=>x.split('?')[0])}
function handlerNames(doc){const out=[];for(const el of doc.querySelectorAll('[onclick]')){const code=el.getAttribute('onclick')||'';for(const m of code.matchAll(/(?<!\.)\b([A-Za-z_$][\w$]*)\s*\(/g)){if(!['if','for','while','return'].includes(m[1]))out.push(m[1])}}return [...new Set(out)]}
async function scanRoute(route){try{const r=await fetchText(route);last.push({name:`Route ${route}`,status:r.ok?'ok':'bad',detail:r.ok?`HTTP ${r.status}`:`HTTP ${r.status}`});if(!r.ok)return;const doc=new DOMParser().parseFromString(r.text,'text/html');const buttons=doc.querySelectorAll('button,[role="button"]').length,links=doc.querySelectorAll('a[href]').length;last.push({name:`Controls ${route}`,status:buttons+links?'ok':'warn',detail:`${buttons} buttons / ${links} links discovered`});const scripts=scriptPaths(doc),parts=[];for(const src of scripts){try{const sr=await fetchText(src);if(sr.ok)parts.push(sr.text);else last.push({name:`Asset ${src}`,status:'bad',detail:`HTTP ${sr.status}`})}catch(e){last.push({name:`Asset ${src}`,status:'bad',detail:e.message})}}const joined=parts.join('\n');const handlers=handlerNames(doc),missing=handlers.filter(name=>!new RegExp(`window\\.${name}\\s*=|function\\s+${name}\\s*\\(`).test(joined));last.push({name:`Handlers ${route}`,status:missing.length?'bad':'ok',detail:missing.length?`Missing exports: ${missing.join(', ')}`:`${handlers.length} inline handler contracts resolved`});const dead=[...doc.querySelectorAll('a')].filter(a=>!a.getAttribute('href')||a.getAttribute('href')==='#'||/^javascript:/i.test(a.getAttribute('href')||''));last.push({name:`Links ${route}`,status:dead.length?'bad':'ok',detail:dead.length?`${dead.length} dead/placeholder links found`:`No dead placeholder links`});const leak=r.text.includes('yjauxyvtrmdriwtmckkl.supabase.co')||joined.includes('yjauxyvtrmdriwtmckkl.supabase.co');last.push({name:`Isolation ${route}`,status:leak?'bad':'ok',detail:leak?'Production Supabase reference detected':'No production Supabase reference in active page/scripts'});const natives=/\b(prompt|confirm|alert)\s*\(/.test(joined);last.push({name:`Dialogs ${route}`,status:natives?'bad':'ok',detail:natives?'Native browser dialog detected':'Professional in-page dialog pattern only'});}catch(e){last.push({name:`Route ${route}`,status:'bad',detail:e.message||String(e)})}}
window.runWebsiteHealthScan=async()=>{last=[];render();$('#healthRows').innerHTML='<div class="notice">Scanning active staging surfaces…</div>';for(const route of routes)await scanRoute(route);const configOk=cfg.environment==='staging'&&String(cfg.supabaseUrl||'').includes('rpnwssqvurpdennpzplx');last.push({name:'Environment Config',status:configOk?'ok':'bad',detail:configOk?'Isolated staging environment confirmed':'Staging isolation config mismatch'});render()};
window.showWebsiteHealthContract=()=>{const d=$('#opsDialog');$('#dialogTitle').textContent='Release Interaction Contract';$('#dialogSubtitle').textContent='A production release is blocked if any critical interaction fails.';$('#dialogBody').innerHTML=`<div class="health-log"><pre>${esc(['Every visible button has a real action','Every internal link resolves','Product Strength + Format selects exact variant','Cart add/update/remove preserves exact variant','Checkout recalculates price/stock/voucher/wallet server-side','Member orders/invoices/tracking/protocols use authenticated staging services','Admin writes use controlled RPCs with reason/audit','No prompt/confirm/alert native dialogs in active staging UI','No production Supabase references in staging UI','Mobile menu/drawers/back/close controls respond','Failed actions show an error and do not silently freeze','No merge/deploy to production without explicit approval'].map(x=>'✓ '+x).join('\n'))}</pre></div>`;$('#dialogFoot').innerHTML='<button class="btn primary" onclick="closeOpsDialog()">Close</button>';d.showModal()};
const prev=window.openOpsView;window.openOpsView=view=>view==='health'?(render()):prev(view);
})();