(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};
const db=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseKey);
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const baseOpenOpsView=window.openOpsView;
let site=null,pages=[],menus=[],templates=[],features=[],integrations=[],pending=null,currentModule='';

function note(text,type='info'){
  let n=q('#opsModuleNotice');
  if(!n){n=document.createElement('div');n.id='opsModuleNotice';n.className='notice show';q('#opsContent')?.prepend(n)}
  n.textContent=text;n.className='notice show';n.style.borderColor=type==='error'?'#efc6c9':'#cfe0f5';n.style.background=type==='error'?'#fff5f5':'#f4f9ff';n.style.color=type==='error'?'#9e343b':'#375578';
  clearTimeout(note.timer);note.timer=setTimeout(()=>n.remove(),3200);
}
window.opsControlNotice=note;

function setMeta(view,title,subtitle){
  currentModule=view;qa('#opsNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  if(q('#opsTitle'))q('#opsTitle').textContent=title;if(q('#opsSubtitle'))q('#opsSubtitle').textContent=subtitle;
  q('#opsSidebar')?.classList.remove('show');
}
function dialog(title,subtitle,body,foot=''){
  q('#dialogTitle').textContent=title;q('#dialogSubtitle').textContent=subtitle||'';q('#dialogBody').innerHTML=body;q('#dialogFoot').innerHTML=foot;q('#opsDialog').showModal();
}
function close(){pending=null;window.closeOpsDialog?.()}
function bool(v){return v===true||v==='true'}
function field(id){return q('#'+id)?.value??''}
function checked(id){return !!q('#'+id)?.checked}
function statusBadge(ok,on='Active',off='Inactive'){return `<span class="badge ${ok?'green':'red'}">${ok?on:off}</span>`}
function pretty(v){if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return JSON.stringify(v);return String(v)}
function diff(before,after){const keys=[...new Set([...Object.keys(before||{}),...Object.keys(after||{})])];const changed=keys.filter(k=>JSON.stringify(before?.[k]??null)!==JSON.stringify(after?.[k]??null));return changed.map(k=>`<div class="diff-row"><div class="key">${esc(k.replaceAll('_',' '))}</div><div class="old">${esc(pretty(before?.[k]))}</div><div class="arrow">→</div><div class="new">${esc(pretty(after?.[k]))}</div></div>`).join('')||'<div class="empty-state">No changes detected.</div>'}
function requireReason(id='ctlReason'){const r=field(id).trim();if(r.length<3){note('A reason of at least 3 characters is required.','error');return null}return r}
function safeJson(text){try{return {ok:true,value:JSON.parse(text||'{}')}}catch(e){return{ok:false,error:e.message}}}

async function loadControl(){
 if(!db)throw new Error('Staging database connection unavailable');
 const [s,p,m,t,f,i]=await Promise.all([
  db.from('site_control').select('*').eq('id','primary').maybeSingle(),
  db.from('content_pages').select('*').order('sort_order').order('title'),
  db.from('menu_items').select('*').order('menu_group').order('sort_order'),
  db.from('media_templates').select('*').order('format'),
  db.from('feature_modules').select('*').order('category').order('display_name'),
  db.from('integration_configs').select('*').order('display_name')
 ]);
 for(const x of [s,p,m,t,f,i])if(x.error)throw x.error;
 site=s.data||null;pages=p.data||[];menus=m.data||[];templates=t.data||[];features=f.data||[];integrations=i.data||[];
}
async function reloadAndRender(){await loadControl();await renderModule(currentModule)}

window.openOpsView=async function(view){
 const modules=['pages','media','themes','features','integrations'];
 if(!modules.includes(view))return baseOpenOpsView?.(view);
 try{await loadControl();await renderModule(view)}catch(e){setMeta(view,'Operations Module','Could not load staging control data');q('#opsContent').innerHTML=`<div class="card"><div class="empty">${esc(e.message||String(e))}</div></div>`}
};
async function renderModule(view){
 if(view==='pages')renderPagesMenus();
 else if(view==='media')renderMedia();
 else if(view==='themes')renderThemes();
 else if(view==='features')renderFeatures();
 else if(view==='integrations')renderIntegrations();
}

function renderPagesMenus(){
 setMeta('pages','Pages & Menus','Manage customer-facing structure with audited preview/confirm saves');
 const pageRows=pages.map(p=>`<div class="page-row"><div><b>${esc(p.title)}</b><div class="muted">/${esc(p.slug)}</div></div><div>${statusBadge(p.published,'Published','Draft')}</div><div>${p.show_in_footer?'Footer':'Not in footer'}</div><button class="btn" onclick="editControlPage('${p.id}')">Edit</button></div>`).join('');
 const menuRows=menus.map(m=>`<div class="menu-row"><div><b>${esc(m.label)}</b><div class="muted">${esc(m.menu_group)} · ${esc(m.target_type)} → ${esc(m.target)}</div></div><div>${statusBadge(m.active)}</div><div>Order ${m.sort_order}</div><button class="btn" onclick="editControlMenu('${m.id}')">Edit</button></div>`).join('');
 q('#opsContent').innerHTML=`<div class="grid2"><section class="card"><div class="card-head"><div><h2>Pages</h2><p class="muted">Drafts remain unavailable publicly until published.</p></div><button class="btn primary" onclick="newControlPage()">New Page</button></div><div class="page-list">${pageRows||'<div class="empty-state">No pages yet.</div>'}</div></section><section class="card"><div class="card-head"><div><h2>Menu Structure</h2><p class="muted">Main, footer, account and admin menus.</p></div><button class="btn primary" onclick="newControlMenu()">New Menu Item</button></div><div class="menu-list">${menuRows||'<div class="empty-state">No menu items yet.</div>'}</div></section></div><div class="policy-note" style="margin-top:16px">Publishing a page or changing navigation is an audited content change. Nothing here modifies production.</div>`;
}
function pageForm(p={}){return `<div class="control-form"><label>Title<input id="ctlPageTitle" class="field" value="${esc(p.title||'')}"></label><label>Slug<input id="ctlPageSlug" class="field" value="${esc(p.slug||'')}"></label><label class="wide">Content<textarea id="ctlPageContent" class="field" style="min-height:180px">${esc(p.content||'')}</textarea></label><label>Sort order<input id="ctlPageSort" class="field" type="number" value="${Number(p.sort_order||0)}"></label><label class="check"><input id="ctlPagePublished" type="checkbox" ${p.published?'checked':''}> Published</label><label class="check"><input id="ctlPageFooter" type="checkbox" ${p.show_in_footer?'checked':''}> Show in footer</label><label class="wide">Reason for change<input id="ctlReason" class="field" placeholder="Required"></label></div>`}
window.newControlPage=()=>{pending={kind:'page',id:null,before:{}};dialog('New Page','Create as draft or publish after preview.',pageForm(),`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewControlPage()">Preview Changes</button>`)};
window.editControlPage=id=>{const p=pages.find(x=>x.id===id);if(!p)return;pending={kind:'page',id,before:p};dialog(`Edit ${p.title}`,'Preview is required before save.',pageForm(p),`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewControlPage()">Preview Changes</button>`)};
window.previewControlPage=()=>{
 const reason=requireReason();if(!reason)return;const after={slug:field('ctlPageSlug').trim().toLowerCase(),title:field('ctlPageTitle').trim(),content:field('ctlPageContent'),published:checked('ctlPagePublished'),show_in_footer:checked('ctlPageFooter'),sort_order:Number(field('ctlPageSort')||0)};
 if(!after.slug||!after.title)return note('Title and slug are required.','error');pending={...pending,after,reason};q('#dialogBody').insertAdjacentHTML('beforeend',`<div class="preview-box"><h4>Change Preview</h4>${diff(pending.before,after)}</div>`);q('#dialogFoot').innerHTML=`<button class="btn" onclick="${pending.id?`editControlPage('${pending.id}')`:'newControlPage()'}">Back</button><button class="btn primary" onclick="confirmControlPage()">Confirm Save</button>`;
};
window.confirmControlPage=async()=>{if(!pending?.after)return;const a=pending.after;const {error}=await db.rpc('ops_save_page',{p_id:pending.id,p_slug:a.slug,p_title:a.title,p_content:a.content,p_published:a.published,p_show_in_footer:a.show_in_footer,p_sort_order:a.sort_order,p_reason:pending.reason});if(error)return note(error.message,'error');close();await loadControl();renderPagesMenus();note('Page saved with audit history.');};

function menuForm(m={}){return `<div class="control-form"><label>Menu group<select id="ctlMenuGroup" class="field">${['main','footer','account','admin'].map(x=>`<option ${m.menu_group===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Label<input id="ctlMenuLabel" class="field" value="${esc(m.label||'')}"></label><label>Target type<select id="ctlMenuType" class="field">${['section','page','url','action'].map(x=>`<option ${m.target_type===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Target<input id="ctlMenuTarget" class="field" value="${esc(m.target||'')}"></label><label>Sort order<input id="ctlMenuSort" class="field" type="number" value="${Number(m.sort_order||0)}"></label><label class="check"><input id="ctlMenuActive" type="checkbox" ${m.active!==false?'checked':''}> Active</label><label class="wide">Reason for change<input id="ctlReason" class="field" placeholder="Required"></label></div>`}
window.newControlMenu=()=>{pending={kind:'menu',id:null,before:{}};dialog('New Menu Item','Every menu target must resolve to a real section, page, URL or action.',menuForm(),`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewControlMenu()">Preview Changes</button>`)};
window.editControlMenu=id=>{const m=menus.find(x=>x.id===id);if(!m)return;pending={kind:'menu',id,before:m};dialog(`Edit ${m.label}`,'Navigation changes require preview and reason.',menuForm(m),`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewControlMenu()">Preview Changes</button>`)};
window.previewControlMenu=()=>{const reason=requireReason();if(!reason)return;const after={menu_group:field('ctlMenuGroup'),label:field('ctlMenuLabel').trim(),target_type:field('ctlMenuType'),target:field('ctlMenuTarget').trim(),active:checked('ctlMenuActive'),sort_order:Number(field('ctlMenuSort')||0)};if(!after.label||!after.target)return note('Label and target are required.','error');pending={...pending,after,reason};q('#dialogBody').insertAdjacentHTML('beforeend',`<div class="preview-box"><h4>Change Preview</h4>${diff(pending.before,after)}</div>`);q('#dialogFoot').innerHTML=`<button class="btn" onclick="${pending.id?`editControlMenu('${pending.id}')`:'newControlMenu()'}">Back</button><button class="btn primary" onclick="confirmControlMenu()">Confirm Save</button>`};
window.confirmControlMenu=async()=>{const a=pending?.after;if(!a)return;const {error}=await db.rpc('ops_save_menu_item',{p_id:pending.id,p_menu_group:a.menu_group,p_label:a.label,p_target_type:a.target_type,p_target:a.target,p_active:a.active,p_sort_order:a.sort_order,p_reason:pending.reason});if(error)return note(error.message,'error');close();await loadControl();renderPagesMenus();note('Menu item saved with audit history.');};

function renderMedia(){
 setMeta('media','Media & Placeholder Templates','Approved Vial, Pen and Cartridge masters with real-image priority');
 q('#opsContent').innerHTML=`<div class="module-grid">${templates.map(t=>`<article class="template-card"><header><h3>${esc(t.display_name)}</h3><span class="badge blue">v${t.version}</span></header><div class="template-preview"><img src="${esc(t.master_image_url)}" alt="${esc(t.display_name)}"></div><div class="module-meta">${statusBadge(t.active)}<span class="badge">${esc(t.format)}</span></div><p>${esc(t.notes||'')}</p><div class="actions"><button class="btn primary" onclick="editMediaTemplate('${esc(t.id)}')">Edit Template</button><button class="btn" onclick="window.open('${esc(t.master_image_url)}','_blank')">Open Master ↗</button></div></article>`).join('')}</div><div class="policy-note" style="margin-top:16px"><b>Placeholder rule:</b> real uploaded product image → matching approved format template → safe fallback. Template changes increase the template version and are audited.</div>`;
}
window.editMediaTemplate=id=>{const t=templates.find(x=>x.id===id);if(!t)return;pending={kind:'media',id,before:t};dialog(`Edit ${t.display_name}`,'This controls the approved fallback master, not real uploaded product images.',`<div class="control-form"><label class="wide">Master image URL<input id="ctlMediaUrl" class="field" value="${esc(t.master_image_url)}"></label><label class="check"><input id="ctlMediaActive" type="checkbox" ${t.active?'checked':''}> Active template</label><label class="wide">Label configuration (JSON)<textarea id="ctlMediaJson" class="field json-box">${esc(JSON.stringify(t.label_config,null,2))}</textarea></label><label class="wide">Notes<textarea id="ctlMediaNotes" class="field">${esc(t.notes||'')}</textarea></label><label class="wide">Reason for change<input id="ctlReason" class="field" placeholder="Required"></label></div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewMediaTemplate()">Preview Changes</button>`)};
window.previewMediaTemplate=()=>{const reason=requireReason();if(!reason)return;const j=safeJson(field('ctlMediaJson'));if(!j.ok)return note('Label configuration JSON is invalid: '+j.error,'error');const after={master_image_url:field('ctlMediaUrl').trim(),active:checked('ctlMediaActive'),label_config:j.value,notes:field('ctlMediaNotes')};if(!after.master_image_url)return note('Master image URL is required.','error');pending={...pending,after,reason};q('#dialogBody').insertAdjacentHTML('beforeend',`<div class="preview-box"><h4>Template Preview</h4>${diff(pending.before,after)}</div>`);q('#dialogFoot').innerHTML=`<button class="btn" onclick="editMediaTemplate('${esc(pending.id)}')">Back</button><button class="btn primary" onclick="confirmMediaTemplate()">Confirm Template Update</button>`};
window.confirmMediaTemplate=async()=>{const a=pending?.after;if(!a)return;const {error}=await db.rpc('ops_save_media_template',{p_id:pending.id,p_master_image_url:a.master_image_url,p_active:a.active,p_label_config:a.label_config,p_notes:a.notes,p_reason:pending.reason});if(error)return note(error.message,'error');close();await loadControl();renderMedia();note('Placeholder template updated and versioned.');};

function renderThemes(){
 setMeta('themes','Themes & Site Modes','Presentation controls stay separate from catalog and business data');
 const theme=site?.theme_key||'clean-store';
 q('#opsContent').innerHTML=`<section class="card"><div class="card-head"><div><h2>Default Storefront Theme</h2><p class="muted">Clean Store remains the production-direction default. Optional themes cannot mutate product data.</p></div><span class="badge blue">${esc(site?.site_mode||'staging').toUpperCase()}</span></div><div class="theme-choice"><div class="theme-tile ${theme==='clean-store'?'active':''}" onclick="chooseControlTheme('clean-store')"><div class="theme-swatch clean"></div><b>Clean Store</b><p>White / navy professional ecommerce.</p></div><div class="theme-tile ${theme==='dark-biotech'?'active':''}" onclick="chooseControlTheme('dark-biotech')"><div class="theme-swatch dark"></div><b>Dark Biotech</b><p>Optional dark scientific presentation.</p></div><div class="theme-tile ${theme==='animated-dna'?'active':''}" onclick="chooseControlTheme('animated-dna')"><div class="theme-swatch dna"></div><b>Animated DNA</b><p>Optional motion-heavy theme.</p></div></div><div class="control-form"><input id="ctlTheme" type="hidden" value="${esc(theme)}"><label>Site mode<select id="ctlSiteMode" class="field">${['staging','safe','maintenance','private','live'].map(x=>`<option ${site?.site_mode===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="check"><input id="ctlSafeMode" type="checkbox" ${site?.safe_mode!==false?'checked':''}> Safe Mode</label><label>Store name<input id="ctlStoreName" class="field" value="${esc(site?.store_name||'AI BioTech')}"></label><label>Tagline<input id="ctlTagline" class="field" value="${esc(site?.tagline||'')}"></label><label class="wide">Announcement<input id="ctlAnnouncement" class="field" value="${esc(site?.announcement||'')}"></label><label class="wide">Reason for change<input id="ctlReason" class="field" placeholder="Required"></label></div><div class="inline-actions" style="margin-top:16px"><button class="btn primary" onclick="previewSiteControl()">Preview Site Control Change</button></div></section><div class="policy-note" style="margin-top:16px">Dark Biotech and Animated DNA are optional modules. If their feature module is not marked staging/ready, selecting them will be blocked instead of producing a broken storefront.</div>`;
}
window.chooseControlTheme=key=>{const featureKey=key==='dark-biotech'?'dark_biotech':key==='animated-dna'?'animated_dna':'clean_store';const f=features.find(x=>x.feature_key===featureKey);if(key!=='clean-store'&&(!f||!f.enabled||!['staging','ready'].includes(f.status)))return note('That optional theme is not enabled and ready yet.','error');q('#ctlTheme').value=key;qa('.theme-tile').forEach(x=>x.classList.remove('active'));const idx=key==='clean-store'?0:key==='dark-biotech'?1:2;qa('.theme-tile')[idx]?.classList.add('active')};
window.previewSiteControl=()=>{const reason=requireReason();if(!reason)return;const after={theme_key:field('ctlTheme'),site_mode:field('ctlSiteMode'),safe_mode:checked('ctlSafeMode'),store_name:field('ctlStoreName').trim(),tagline:field('ctlTagline').trim(),announcement:field('ctlAnnouncement')};pending={kind:'site',before:site||{},after,reason};dialog('Preview Site Control Change','Review presentation and mode changes before confirmation.',`<div class="preview-box"><h4>Change Preview</h4>${diff(site||{},after)}</div><div class="danger-note policy-note" style="margin-top:12px">This is staging only. A future production release will require a separate explicit approval.</div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="confirmSiteControl()">Confirm Staging Change</button>`)};
window.confirmSiteControl=async()=>{const a=pending?.after;if(!a)return;const {error}=await db.rpc('ops_save_site_control',{p_patch:a,p_reason:pending.reason});if(error)return note(error.message,'error');close();await loadControl();renderThemes();note('Site control updated with audit history.');};

function renderFeatures(){
 setMeta('features','Plugins & Features','Versioned modules with explicit enable/disable state');
 const groups=[...new Set(features.map(f=>f.category))];q('#opsContent').innerHTML=groups.map(g=>`<section class="card" style="margin-bottom:16px"><div class="card-head"><h2>${esc(g)}</h2><span class="badge">${features.filter(x=>x.category===g).length} modules</span></div><div class="feature-grid">${features.filter(x=>x.category===g).map(f=>`<article class="feature-card"><header><div><h3>${esc(f.display_name)}</h3><div class="module-meta"><span class="badge blue">v${esc(f.version)}</span><span class="badge ${f.status==='ready'||f.status==='staging'?'green':'amber'}">${esc(f.status)}</span></div></div>${statusBadge(f.enabled,'Enabled','Disabled')}</header><p>${esc(Object.entries(f.config||{}).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`).join(' · ')||'No module configuration')}</p><div class="actions"><button class="btn" onclick="inspectFeature('${esc(f.feature_key)}')">Details</button><button class="btn ${f.enabled?'':'primary'}" onclick="toggleControlFeature('${esc(f.feature_key)}')">${f.enabled?'Disable':'Enable'}</button></div></article>`).join('')}</div></section>`).join('');
}
window.inspectFeature=key=>{const f=features.find(x=>x.feature_key===key);if(!f)return;dialog(f.display_name,'Feature manifest preview',`<div class="control-form"><label>Status<input class="field" value="${esc(f.status)}" readonly></label><label>Version<input class="field" value="${esc(f.version)}" readonly></label><label class="wide">Configuration<textarea class="field json-box" readonly>${esc(JSON.stringify(f.config,null,2))}</textarea></label><label class="wide">Permissions<textarea class="field json-box" readonly>${esc(JSON.stringify(f.permissions,null,2))}</textarea></label></div>`,`<button class="btn primary" onclick="closeOpsDialog()">Close</button>`)};
window.toggleControlFeature=key=>{const f=features.find(x=>x.feature_key===key);if(!f)return;if(!f.enabled&&f.status==='planned')return dialog(f.display_name,'This module is not ready to activate.',`<div class="empty-state">The module is registered, but its implementation status is still <b>planned</b>. It cannot be enabled until its staging tests exist.</div>`,`<button class="btn primary" onclick="closeOpsDialog()">Close</button>`);pending={kind:'feature',before:f,after:{enabled:!f.enabled,status:!f.enabled?'staging':'disabled'},key};dialog(`${f.enabled?'Disable':'Enable'} ${f.display_name}`,'Feature state changes are audited.',`<label>Reason for change<input id="ctlReason" class="field" placeholder="Required"></label><div class="preview-box"><h4>Change Preview</h4>${diff({enabled:f.enabled,status:f.status},pending.after)}</div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="confirmControlFeature()">Confirm</button>`)};
window.confirmControlFeature=async()=>{const reason=requireReason();if(!reason)return;const {error}=await db.rpc('ops_toggle_feature',{p_feature_key:pending.key,p_enabled:pending.after.enabled,p_status:pending.after.status,p_reason:reason});if(error)return note(error.message,'error');close();await loadControl();renderFeatures();note('Feature state updated.');};

function renderIntegrations(){
 setMeta('integrations','Integrations','External services stay disabled until configuration and health checks pass');
 q('#opsContent').innerHTML=`<div class="integration-grid">${integrations.map(i=>`<article class="integration-card"><header><div><h3>${esc(i.display_name)}</h3><div class="module-meta"><span class="badge">${esc(i.mode)}</span><span class="badge ${i.status==='healthy'?'green':i.status==='error'?'red':'amber'}">${esc(i.status)}</span></div></div>${statusBadge(i.enabled,'Enabled','Disabled')}</header><p>${esc(Object.entries(i.config||{}).map(([k,v])=>`${k.replaceAll('_',' ')}: ${v}`).join(' · ')||'No public configuration')}</p><div class="actions"><button class="btn primary" onclick="editIntegrationControl('${esc(i.integration_key)}')">Configure</button></div></article>`).join('')}</div><div class="policy-note danger-note" style="margin-top:16px"><b>Secret rule:</b> API keys, tokens, passwords and private keys are never stored in this browser-readable configuration table. They will be stored only in server-side secret storage when each connector is implemented.</div>`;
}
window.editIntegrationControl=key=>{const i=integrations.find(x=>x.integration_key===key);if(!i)return;pending={kind:'integration',key,before:i};dialog(`Configure ${i.display_name}`,'Public/non-secret connector settings only.',`<div class="control-form"><label>Mode<select id="ctlIntMode" class="field">${['disabled','sandbox','live'].map(x=>`<option ${i.mode===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Status<select id="ctlIntStatus" class="field">${['not_configured','configured','testing','healthy','error','disabled'].map(x=>`<option ${i.status===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="check"><input id="ctlIntEnabled" type="checkbox" ${i.enabled?'checked':''}> Enabled</label><label class="wide">Public configuration (JSON)<textarea id="ctlIntConfig" class="field json-box">${esc(JSON.stringify(i.config,null,2))}</textarea></label><label class="wide">Reason for change<input id="ctlReason" class="field" placeholder="Required"></label></div><div class="policy-note danger-note" style="margin-top:12px">Do not paste API keys, tokens, passwords or private keys here.</div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewIntegrationControl()">Preview Changes</button>`)};
window.previewIntegrationControl=()=>{const reason=requireReason();if(!reason)return;const j=safeJson(field('ctlIntConfig'));if(!j.ok)return note('Integration config JSON is invalid: '+j.error,'error');const text=JSON.stringify(j.value).toLowerCase();if(/"(secret|api_key|token|password|private_key)"\s*:/.test(text))return note('Secret-like fields are blocked from public integration config.','error');const after={enabled:checked('ctlIntEnabled'),mode:field('ctlIntMode'),status:field('ctlIntStatus'),config:j.value};if(after.enabled&&!['configured','testing','healthy'].includes(after.status))return note('An integration cannot be enabled until it is configured or testing/healthy.','error');pending={...pending,after,reason};q('#dialogBody').insertAdjacentHTML('beforeend',`<div class="preview-box"><h4>Change Preview</h4>${diff(pending.before,after)}</div>`);q('#dialogFoot').innerHTML=`<button class="btn" onclick="editIntegrationControl('${esc(pending.key)}')">Back</button><button class="btn primary" onclick="confirmIntegrationControl()">Confirm Save</button>`};
window.confirmIntegrationControl=async()=>{const a=pending?.after;if(!a)return;const {error}=await db.rpc('ops_save_integration',{p_integration_key:pending.key,p_enabled:a.enabled,p_mode:a.mode,p_status:a.status,p_config:a.config,p_reason:pending.reason});if(error)return note(error.message,'error');close();await loadControl();renderIntegrations();note('Integration configuration saved with audit history.');};

window.opsControlRefresh=reloadAndRender;
})();
