(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};
const sb=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseKey);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const money=v=>'RM'+Number(v||0).toFixed(2);
let me=null,admin=null,products=[],variants=[],categories=[],research=[],batches=[];
let currentView='dashboard',pendingAction=null;

function showLoginNotice(message,type='info'){
  const n=$('#loginNotice');n.textContent=message||'';n.classList.toggle('show',!!message);
  n.style.borderColor=type==='error'?'#efc6c9':'#cfe0f5';n.style.background=type==='error'?'#fff5f5':'#f4f9ff';n.style.color=type==='error'?'#9e343b':'#375578';
}
function btnBusy(btn,busy,label){if(!btn)return; if(busy){btn.dataset.label=btn.textContent;btn.textContent=label||'Working…';btn.disabled=true}else{btn.textContent=btn.dataset.label||btn.textContent;btn.disabled=false}}
function fieldVal(id){return document.getElementById(id)?.value??''}
function closeOpsDialog(){const d=$('#opsDialog');if(d?.open)d.close();pendingAction=null} window.closeOpsDialog=closeOpsDialog;
function openDialog(title,subtitle,body,actions=''){$('#dialogTitle').textContent=title;$('#dialogSubtitle').textContent=subtitle||'';$('#dialogBody').innerHTML=body;$('#dialogFoot').innerHTML=actions;$('#opsDialog').showModal()}
function messageCard(title,text){return `<div class="card"><div class="card-head"><h2>${esc(title)}</h2></div><div class="empty">${esc(text)}</div></div>`}

async function opsSignIn(){
  if(!sb)return showLoginNotice('Staging database connection is unavailable.','error');
  const email=fieldVal('loginEmail').trim(),password=fieldVal('loginPassword'),btn=$('#signInBtn');
  if(!email||!password)return showLoginNotice('Enter your staging email and password.','error');
  btnBusy(btn,true,'Signing in…');showLoginNotice('Signing in…');
  const {error}=await sb.auth.signInWithPassword({email,password});btnBusy(btn,false);
  if(error)return showLoginNotice(error.message,'error');
  await boot();
}
window.opsSignIn=opsSignIn;

async function opsCreateAccount(){
  if(!sb)return showLoginNotice('Staging database connection is unavailable.','error');
  const email=fieldVal('loginEmail').trim(),password=fieldVal('loginPassword');
  if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)return showLoginNotice('Enter a valid email and a staging password of at least 8 characters.','error');
  showLoginNotice('Creating staging account…');
  const {data,error}=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/ops.html'}});
  if(error)return showLoginNotice(error.message,'error');
  if(data.session){
    const claim=await sb.rpc('staging_claim_super_admin');
    if(claim.error)return showLoginNotice('Account created, but admin access was not approved: '+claim.error.message,'error');
    showLoginNotice('Staging admin account created. Opening Control Center…');await boot();
  }else showLoginNotice('Staging account created. Confirm the email if Supabase requests confirmation, then sign in.');
}
window.opsCreateAccount=opsCreateAccount;

async function opsResetPassword(){
  if(!sb)return showLoginNotice('Staging database connection is unavailable.','error');
  const email=fieldVal('loginEmail').trim();if(!email)return showLoginNotice('Enter your staging email first.','error');
  const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/ops.html?recovery=1'});
  showLoginNotice(error?error.message:'Staging password reset email sent.',error?'error':'info');
}
window.opsResetPassword=opsResetPassword;

async function saveRecoveredPassword(){
  const password=fieldVal('recoveryPassword');if(password.length<8)return $('#recoveryMsg').textContent='Use at least 8 characters.';
  const {error}=await sb.auth.updateUser({password});if(error)return $('#recoveryMsg').textContent=error.message;
  closeOpsDialog();showLoginNotice('Password updated. You can continue in staging.');await boot();
}
window.saveRecoveredPassword=saveRecoveredPassword;

async function opsSignOut(){if(sb)await sb.auth.signOut();location.reload()} window.opsSignOut=opsSignOut;

async function resolveAdmin(){
  const {data:{user}}=await sb.auth.getUser();if(!user)return false;me=user;
  let res=await sb.from('admin_users').select('user_id,role,active').eq('user_id',user.id).maybeSingle();
  if(!res.data){const claim=await sb.rpc('staging_claim_super_admin');if(!claim.error)res=await sb.from('admin_users').select('user_id,role,active').eq('user_id',user.id).maybeSingle()}
  if(res.error||!res.data?.active){await sb.auth.signOut();showLoginNotice('This staging account is not authorized for Operations Control Center access.','error');return false}
  admin=res.data;return true;
}

async function boot(){
  if(!sb)return;
  const ok=await resolveAdmin();
  if(!ok){$('#loginWrap').hidden=false;$('#opsApp').hidden=true;return}
  $('#loginWrap').hidden=true;$('#opsApp').hidden=false;$('#roleBadge').textContent=String(admin.role).replaceAll('_',' ').toUpperCase();
  await refreshData();openOpsView(currentView);
}

async function refreshData(){
  const [pr,vr,cr,rr,br]=await Promise.all([
    sb.from('products').select('id,name,slug,category_id,product_type,featured,published,short_description,long_description,main_image_url,seo_title,seo_description,tags,status,updated_at,categories(id,name,color)').order('name'),
    sb.from('variants').select('id,product_id,strength,strength_unit,strength_label,format,sku,price,compare_at_price,stock_quantity,reserved_quantity,sold_quantity,low_stock_threshold,image_url,barcode,weight_grams,active,archived_at,updated_at').order('product_id').order('strength').order('format'),
    sb.from('categories').select('id,name,slug,color,description,status').eq('status','active').order('name'),
    sb.from('research_entries').select('id,product_id,title,category,short_summary,full_content,references_json,published,updated_at').order('title'),
    sb.from('change_batches').select('id,source,actor_user_id,reason,status,metadata,created_at,completed_at,undone_at').order('created_at',{ascending:false}).limit(50)
  ]);
  if(pr.error)throw pr.error;if(vr.error)throw vr.error;
  products=pr.data||[];variants=vr.data||[];categories=cr.data||[];research=rr.data||[];batches=br.data||[];
}

function variantsFor(id){return variants.filter(v=>v.product_id===id)}
function productFor(id){return products.find(p=>p.id===id)}
function categoryFor(p){return categories.find(c=>c.id===p.category_id)||p.categories||null}
function activeVariants(){return variants.filter(v=>v.active&&!v.archived_at)}
function availableStock(v){return Math.max(0,Number(v.stock_quantity||0)-Number(v.reserved_quantity||0))}
function contentMissing(p){return !String(p.short_description||'').trim()||!String(p.long_description||'').trim()||!String(p.seo_title||'').trim()||!String(p.seo_description||'').trim()}

function openOpsView(view){
  currentView=view;$$('#opsNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  const titles={dashboard:['Dashboard','Safe manual operations in isolated staging'],products:['Products & Variants','Catalog editing through controlled service functions'],inventory:['Inventory','Stock visibility and audited adjustments'],research:['Research Insights','Public research layer in staging'],history:['Change History','Before/after audit batches from controlled writes'],health:['Website Health','Staging integrity and completeness checks']};
  $('#opsTitle').textContent=titles[view]?.[0]||'Operations';$('#opsSubtitle').textContent=titles[view]?.[1]||'';
  $('#opsSidebar').classList.remove('show');
  if(view==='dashboard')renderDashboard();else if(view==='products')renderProductsView();else if(view==='inventory')renderInventoryView();else if(view==='research')renderResearchView();else if(view==='history')renderHistoryView();else if(view==='health')renderHealthView();
}
window.openOpsView=openOpsView;

function renderDashboard(){
  const active=activeVariants(),low=active.filter(v=>availableStock(v)<=Number(v.low_stock_threshold||5)),missing=products.filter(contentMissing);
  $('#opsContent').innerHTML=`<div class="stats"><div class="stat"><small>Products</small><b>${products.length}</b></div><div class="stat"><small>Active Variants</small><b>${active.length}</b></div><div class="stat"><small>Low Stock</small><b>${low.length}</b></div><div class="stat"><small>Content Review</small><b>${missing.length}</b></div></div>
  <div class="grid2"><section class="card"><div class="card-head"><h2>Environment</h2><span class="badge green">ISOLATED STAGING</span></div><div class="health-list"><div class="health-row"><b>Supabase project</b><span class="status ok">● Connected</span></div><div class="health-row"><b>Production writes</b><span class="status ok">● Disabled</span></div><div class="health-row"><b>Catalog mirror</b><span class="status ok">● ${products.length} / ${variants.length}</span></div><div class="health-row"><b>Admin writes</b><span class="status ok">● Controlled RPC only</span></div></div></section>
  <section class="card"><div class="card-head"><h2>Recent Changes</h2><button class="btn" onclick="openOpsView('history')">View History</button></div>${batches.length?batches.slice(0,5).map(historyRow).join(''):'<div class="empty">No controlled staging changes yet.</div>'}</section></div>`;
}

function productFilters(){const q=fieldVal('productSearch').trim().toLowerCase(),cat=fieldVal('productCategory'),flag=fieldVal('productFlag');return products.filter(p=>{const pv=variantsFor(p.id);const hay=[p.name,p.slug,p.id,...pv.map(v=>`${v.sku} ${v.strength_label} ${v.format}`)].join(' ').toLowerCase();const c=!cat||p.category_id===cat;const f=flag==='missing'?contentMissing(p):flag==='featured'?p.featured:flag==='hidden'?!p.published:true;return (!q||hay.includes(q))&&c&&f})}
function renderProductsView(){
  $('#opsContent').innerHTML=`<section class="card"><div class="card-head"><h2>Products & Variants</h2><div class="toolbar"><input id="productSearch" class="field" placeholder="Search product / SKU" oninput="renderProductRows()"><select id="productCategory" class="field" onchange="renderProductRows()"><option value="">All categories</option>${categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><select id="productFlag" class="field" onchange="renderProductRows()"><option value="">All products</option><option value="featured">Featured</option><option value="missing">Missing content</option><option value="hidden">Hidden/unpublished</option></select></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Category</th><th>Variants</th><th>Formats</th><th>Content</th><th>Published</th><th>Actions</th></tr></thead><tbody id="productRows"></tbody></table></div></section>`;renderProductRows();
}
function renderProductRows(){const host=$('#productRows');if(!host)return;const rows=productFilters();host.innerHTML=rows.length?rows.map(p=>{const vv=variantsFor(p.id),formats=[...new Set(vv.filter(v=>v.active).map(v=>v.format))].join(', '),cat=categoryFor(p);return `<tr><td><b>${esc(p.name)}</b><br><span class="muted">${esc(p.slug)}</span></td><td><span class="badge" style="border-left:4px solid ${cat?.color||'#bbb'}">${esc(cat?.name||'—')}</span></td><td>${vv.filter(v=>v.active).length}</td><td>${esc(formats||'—')}</td><td><span class="badge ${contentMissing(p)?'amber':'green'}">${contentMissing(p)?'Needs content':'Complete'}</span></td><td><span class="badge ${p.published?'green':'red'}">${p.published?'Published':'Hidden'}</span></td><td><div class="row-actions"><button class="btn" onclick="openProductEditor('${esc(p.id)}')">Edit</button><button class="btn" onclick="openProductVariants('${esc(p.id)}')">Variants</button></div></td></tr>`}).join(''):`<tr><td colspan="7"><div class="empty">No products match the filters.</div></td></tr>`}
window.renderProductRows=renderProductRows;

function productForm(p){const cat=categoryFor(p);return `<div class="form form-grid"><label>Name<input id="pfName" class="field" value="${esc(p.name)}"></label><label>Slug<input id="pfSlug" class="field" value="${esc(p.slug)}"></label><label>Category<select id="pfCategory" class="field">${categories.map(c=>`<option value="${c.id}" ${c.id===p.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Status<select id="pfStatus" class="field"><option ${p.status==='active'?'selected':''}>active</option><option ${p.status==='inactive'?'selected':''}>inactive</option><option ${p.status==='archived'?'selected':''}>archived</option></select></label><label class="check"><input id="pfFeatured" type="checkbox" ${p.featured?'checked':''}> Featured product</label><label class="check"><input id="pfPublished" type="checkbox" ${p.published?'checked':''}> Published</label><label class="wide">Short description<textarea id="pfShort" class="field">${esc(p.short_description||'')}</textarea></label><label class="wide">Long product details<textarea id="pfLong" class="field">${esc(p.long_description||'')}</textarea></label><label>SEO title<input id="pfSeoTitle" class="field" value="${esc(p.seo_title||'')}"></label><label>SEO description<textarea id="pfSeoDescription" class="field">${esc(p.seo_description||'')}</textarea></label><label class="wide">Tags<input id="pfTags" class="field" value="${esc((p.tags||[]).join(', '))}"></label><label class="wide">Reason for change<input id="pfReason" class="field" placeholder="Required — explain why this change is needed"></label></div><div id="productPreview"></div>`}
function openProductEditor(id){const p=productFor(id);if(!p)return;pendingAction=null;openDialog(`Edit ${p.name}`,'All writes go through the controlled Operations service.',productForm(p),`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewProductSave('${esc(id)}')">Preview Changes</button>`)} window.openProductEditor=openProductEditor;
function buildProductPatch(p){const next={name:fieldVal('pfName').trim(),slug:fieldVal('pfSlug').trim().toLowerCase(),category_id:fieldVal('pfCategory'),status:fieldVal('pfStatus'),featured:$('#pfFeatured').checked,published:$('#pfPublished').checked,short_description:fieldVal('pfShort'),long_description:fieldVal('pfLong'),seo_title:fieldVal('pfSeoTitle').trim()||null,seo_description:fieldVal('pfSeoDescription').trim()||null,tags:fieldVal('pfTags').split(',').map(x=>x.trim()).filter(Boolean)};const patch={},diff=[];for(const [k,v] of Object.entries(next)){const old=k==='tags'?(p.tags||[]):p[k];if(JSON.stringify(old??null)!==JSON.stringify(v??null)){patch[k]=v;diff.push({field:k,old,new:v})}}return{patch,diff}}
function valueText(v){if(Array.isArray(v))return v.join(', ')||'—';if(v===null||v===undefined||v==='')return '—';return String(v)}
function previewProductSave(id){const p=productFor(id),reason=fieldVal('pfReason').trim();if(reason.length<3)return $('#productPreview').innerHTML='<div class="danger-note">Enter a meaningful reason before previewing the change.</div>';const {patch,diff}=buildProductPatch(p);if(!diff.length)return $('#productPreview').innerHTML='<div class="preview"><b>No changes detected.</b></div>';pendingAction={type:'product',id,patch,reason};$('#productPreview').innerHTML=`<div class="preview"><h4>Change Preview</h4>${diff.map(d=>`<div class="diff"><div><small>${esc(d.field)} — current</small>${esc(valueText(d.old))}</div><div><small>${esc(d.field)} — proposed</small>${esc(valueText(d.new))}</div></div>`).join('')}</div>`;$('#dialogFoot').innerHTML=`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn blue" onclick="confirmProductSave()">Confirm & Save</button>`} window.previewProductSave=previewProductSave;
async function confirmProductSave(){if(!pendingAction||pendingAction.type!=='product')return;const btn=$('#dialogFoot .blue');btnBusy(btn,true,'Saving…');const {error,data}=await sb.rpc('ops_update_product',{p_product_id:pendingAction.id,p_patch:pendingAction.patch,p_reason:pendingAction.reason,p_source:'manual'});btnBusy(btn,false);if(error)return $('#productPreview').innerHTML+=`<div class="danger-note">${esc(error.message)}</div>`;await refreshData();closeOpsDialog();renderProductsView();window.toast?.(`Product saved · Batch ${data?.batch_id||''}`)} window.confirmProductSave=confirmProductSave;

function openProductVariants(id){const p=productFor(id);if(!p)return;const vv=variantsFor(id);openDialog(`${p.name} — Variants`,`${vv.length} staging variants. Strength and format identity are preserved.`,`<div class="table-wrap"><table class="table"><thead><tr><th>Strength</th><th>Format</th><th>SKU</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr></thead><tbody>${vv.map(v=>`<tr><td><b>${esc(v.strength_label)}</b></td><td>${esc(v.format)}</td><td>${esc(v.sku)}</td><td>${money(v.price)}</td><td>${availableStock(v)}</td><td><span class="badge ${v.active?'green':'red'}">${v.active?'Active':'Inactive'}</span></td><td><div class="row-actions"><button class="btn" onclick="openVariantEditor('${esc(v.id)}')">Edit</button><button class="btn" onclick="openStockEditor('${esc(v.id)}')">Stock</button></div></td></tr>`).join('')}</tbody></table></div>`,`<button class="btn" onclick="closeOpsDialog()">Close</button>`)} window.openProductVariants=openProductVariants;

function openVariantEditor(id){const v=variants.find(x=>x.id===id),p=v&&productFor(v.product_id);if(!v)return;pendingAction=null;openDialog(`Edit ${p?.name||v.product_id} · ${v.strength_label} ${v.format}`,'Price/SKU/status changes are audited. Stock has its own controlled adjustment workflow.',`<div class="form form-grid"><label>SKU<input id="vfSku" class="field" value="${esc(v.sku)}"></label><label>Price<input id="vfPrice" class="field" type="number" min="0" step="0.01" value="${Number(v.price)}"></label><label>Low stock threshold<input id="vfLow" class="field" type="number" min="0" step="1" value="${Number(v.low_stock_threshold||5)}"></label><label class="check"><input id="vfActive" type="checkbox" ${v.active?'checked':''}> Active variant</label><label class="wide">Image URL<input id="vfImage" class="field" value="${esc(v.image_url||'')}"></label><label class="wide">Reason for change<input id="vfReason" class="field" placeholder="Required reason"></label></div><div id="variantPreview"></div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="previewVariantSave('${esc(id)}')">Preview Changes</button>`)} window.openVariantEditor=openVariantEditor;
function previewVariantSave(id){const v=variants.find(x=>x.id===id),reason=fieldVal('vfReason').trim();if(reason.length<3)return $('#variantPreview').innerHTML='<div class="danger-note">Enter a meaningful reason.</div>';const next={sku:fieldVal('vfSku').trim(),price:Number(fieldVal('vfPrice')),low_stock_threshold:Number(fieldVal('vfLow')),active:$('#vfActive').checked,image_url:fieldVal('vfImage').trim()||null};if(!next.sku||!Number.isFinite(next.price)||next.price<0||!Number.isInteger(next.low_stock_threshold)||next.low_stock_threshold<0)return $('#variantPreview').innerHTML='<div class="danger-note">Check SKU, price and stock-threshold values.</div>';const patch={},diff=[];for(const [k,val] of Object.entries(next)){const old=v[k];if(String(old??'')!==String(val??'')){patch[k]=val;diff.push({field:k,old,new:val})}}if(!diff.length)return $('#variantPreview').innerHTML='<div class="preview"><b>No changes detected.</b></div>';pendingAction={type:'variant',id,patch,reason};$('#variantPreview').innerHTML=`<div class="preview"><h4>Change Preview</h4>${diff.map(d=>`<div class="diff"><div><small>${esc(d.field)} — current</small>${esc(valueText(d.old))}</div><div><small>${esc(d.field)} — proposed</small>${esc(valueText(d.new))}</div></div>`).join('')}</div>`;$('#dialogFoot').innerHTML=`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn blue" onclick="confirmVariantSave()">Confirm & Save</button>`} window.previewVariantSave=previewVariantSave;
async function confirmVariantSave(){if(!pendingAction||pendingAction.type!=='variant')return;const btn=$('#dialogFoot .blue');btnBusy(btn,true,'Saving…');const {error,data}=await sb.rpc('ops_update_variant',{p_variant_id:pendingAction.id,p_patch:pendingAction.patch,p_reason:pendingAction.reason,p_source:'manual'});btnBusy(btn,false);if(error)return $('#variantPreview').innerHTML+=`<div class="danger-note">${esc(error.message)}</div>`;await refreshData();closeOpsDialog();currentView==='inventory'?renderInventoryView():renderProductsView();window.toast?.(`Variant saved · Batch ${data?.batch_id||''}`)} window.confirmVariantSave=confirmVariantSave;

const reasons=['New stock received','Manual stock count','Damaged stock','Expired / removed stock','Order correction','Returned stock','Sample / internal use','Inventory adjustment','Other'];
function openStockEditor(id){const v=variants.find(x=>x.id===id),p=v&&productFor(v.product_id);if(!v)return;openDialog(`Adjust Stock — ${p?.name||v.product_id}`,`${v.strength_label} · ${v.format} · ${v.sku}`,`<div class="form form-grid"><div class="preview"><small>Current stock</small><h2 style="margin:4px 0">${Number(v.stock_quantity)}</h2></div><div id="stockDelta" class="preview"><small>Difference</small><h2 style="margin:4px 0">0</h2></div><label>New stock quantity<input id="sfQty" class="field" type="number" min="0" step="1" value="${Number(v.stock_quantity)}" oninput="updateStockDelta('${esc(id)}')"></label><label>Reason<select id="sfReason" class="field"><option value="">Choose reason</option>${reasons.map(r=>`<option>${r}</option>`).join('')}</select></label><label class="wide">Internal note<textarea id="sfNote" class="field" placeholder="Optional, required when reason is Other"></textarea></label></div><div class="danger-note">This adjustment writes only to the isolated staging inventory and records a before/after change batch.</div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn blue" onclick="confirmStockSave('${esc(id)}')">Confirm Stock Update</button>`)} window.openStockEditor=openStockEditor;
function updateStockDelta(id){const v=variants.find(x=>x.id===id),n=Number(fieldVal('sfQty')),d=Number.isFinite(n)?n-Number(v?.stock_quantity||0):0;$('#stockDelta').innerHTML=`<small>Difference</small><h2 style="margin:4px 0;color:${d<0?'#c43e45':d>0?'#148a50':'#172742'}">${d>0?'+':''}${d}</h2>`} window.updateStockDelta=updateStockDelta;
async function confirmStockSave(id){const v=variants.find(x=>x.id===id),n=Number(fieldVal('sfQty')),reason=fieldVal('sfReason'),note=fieldVal('sfNote').trim();if(!Number.isInteger(n)||n<0)return window.toast?.('Enter a valid non-negative stock quantity.');if(n===Number(v.stock_quantity))return window.toast?.('Stock quantity did not change.');if(!reason)return window.toast?.('Choose a stock-change reason.');if(reason==='Other'&&note.length<3)return window.toast?.('Explain the Other stock-change reason.');const btn=$('#dialogFoot .blue');btnBusy(btn,true,'Updating…');const combined=note?`${reason} — ${note}`:reason;const {error,data}=await sb.rpc('ops_adjust_stock',{p_variant_id:id,p_new_stock:n,p_reason:combined,p_source:'manual'});btnBusy(btn,false);if(error)return window.toast?.(error.message);await refreshData();closeOpsDialog();currentView==='inventory'?renderInventoryView():renderProductsView();window.toast?.(`Stock updated ${data?.delta>0?'+':''}${data?.delta||''} · Batch ${data?.batch_id||''}`)} window.confirmStockSave=confirmStockSave;

function inventoryRows(){const q=fieldVal('inventorySearch').trim().toLowerCase(),format=fieldVal('inventoryFormat'),state=fieldVal('inventoryState');return variants.filter(v=>{const p=productFor(v.product_id),stock=availableStock(v),hay=[p?.name,v.sku,v.strength_label,v.format].join(' ').toLowerCase();const f=!format||v.format===format;const s=state==='low'?stock<=Number(v.low_stock_threshold||5)&&v.active:state==='out'?stock<=0&&v.active:state==='inactive'?!v.active:true;return(!q||hay.includes(q))&&f&&s})}
function renderInventoryView(){$('#opsContent').innerHTML=`<section class="card"><div class="card-head"><h2>Inventory</h2><div class="toolbar"><input id="inventorySearch" class="field" placeholder="Search product / SKU" oninput="renderInventoryRows()"><select id="inventoryFormat" class="field" onchange="renderInventoryRows()"><option value="">All formats</option><option>Vial</option><option>Cartridge</option><option>Pen</option></select><select id="inventoryState" class="field" onchange="renderInventoryRows()"><option value="">All status</option><option value="low">Low stock</option><option value="out">Out of stock</option><option value="inactive">Inactive</option></select></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Strength</th><th>Format</th><th>SKU</th><th>On Hand</th><th>Reserved</th><th>Available</th><th>Price</th><th>Action</th></tr></thead><tbody id="inventoryRows"></tbody></table></div></section>`;renderInventoryRows()}
function renderInventoryRows(){const host=$('#inventoryRows');if(!host)return;const a=inventoryRows();host.innerHTML=a.length?a.map(v=>{const p=productFor(v.product_id),stock=availableStock(v),state=!v.active?'red':stock<=0?'red':stock<=Number(v.low_stock_threshold||5)?'amber':'green';return `<tr><td><b>${esc(p?.name||v.product_id)}</b></td><td>${esc(v.strength_label)}</td><td>${esc(v.format)}</td><td>${esc(v.sku)}</td><td>${Number(v.stock_quantity)}</td><td>${Number(v.reserved_quantity||0)}</td><td><span class="badge ${state}">${stock}</span></td><td>${money(v.price)}</td><td><button class="btn" onclick="openStockEditor('${esc(v.id)}')">Adjust Stock</button></td></tr>`}).join(''):`<tr><td colspan="9"><div class="empty">No inventory rows match.</div></td></tr>`} window.renderInventoryRows=renderInventoryRows;

function renderResearchView(){const byProduct=new Map(products.map(p=>[p.id,p]));$('#opsContent').innerHTML=`<section class="card"><div class="card-head"><h2>Research Insights</h2><div class="toolbar"><input id="researchSearch" class="field" placeholder="Search Research Insight" oninput="renderResearchRows()"></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>Category</th><th>Summary</th><th>Published</th><th>Action</th></tr></thead><tbody id="researchRows"></tbody></table></div></section>`;window._researchProductMap=byProduct;renderResearchRows()}
function renderResearchRows(){const q=fieldVal('researchSearch').toLowerCase(),a=research.filter(r=>!q||`${r.title} ${r.category} ${r.short_summary}`.toLowerCase().includes(q));$('#researchRows').innerHTML=a.length?a.map(r=>`<tr><td><b>${esc(r.title)}</b></td><td>${esc(r.category)}</td><td>${esc(r.short_summary).slice(0,90)}${String(r.short_summary).length>90?'…':''}</td><td><span class="badge ${r.published?'green':'red'}">${r.published?'Published':'Draft'}</span></td><td><button class="btn" onclick="openResearchRecord('${r.id}')">View</button></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">No Research Insights match.</div></td></tr>`} window.renderResearchRows=renderResearchRows;
function openResearchRecord(id){const r=research.find(x=>x.id===id);if(!r)return;openDialog(r.title,'Public staging Research Insight',`<span class="badge blue">${esc(r.category)}</span><h3>Summary</h3><p>${esc(r.short_summary||'—')}</p><h3>Content</h3><p>${esc(r.full_content||'—')}</p><h3>Public references</h3><pre style="white-space:pre-wrap;background:#f7f9fc;border:1px solid #dde5ef;border-radius:10px;padding:12px">${esc(JSON.stringify(r.references_json||[],null,2))}</pre><div class="danger-note">Editing and source-visibility controls will be added through the dedicated Research/Source service layer; this view does not pretend to offer an unsafe direct edit.</div>`,`<button class="btn" onclick="closeOpsDialog()">Close</button>`)} window.openResearchRecord=openResearchRecord;

function historyRow(b){return `<div class="history-item"><header><b>${esc(String(b.source).toUpperCase())} · ${esc(b.status)}</b><button class="btn" onclick="openBatch('${b.id}')">Details</button></header><p>${esc(b.reason)}</p><code>${esc(new Date(b.created_at).toLocaleString())} · ${esc(b.id)}</code></div>`}
function renderHistoryView(){$('#opsContent').innerHTML=`<section class="card"><div class="card-head"><h2>Change History</h2><button class="btn" onclick="refreshHistory()">Refresh</button></div><div id="historyList">${batches.length?batches.map(historyRow).join(''):'<div class="empty">No controlled changes yet.</div>'}</div></section>`}
async function refreshHistory(){const br=await sb.from('change_batches').select('*').order('created_at',{ascending:false}).limit(50);if(!br.error)batches=br.data||[];renderHistoryView()} window.refreshHistory=refreshHistory;
async function openBatch(id){const b=batches.find(x=>x.id===id),it=await sb.from('change_items').select('*').eq('batch_id',id).order('id');if(it.error)return window.toast?.(it.error.message);openDialog('Change Batch',b?.reason||id,`<div class="preview"><div class="diff"><div><small>Batch ID</small>${esc(id)}</div><div><small>Status</small>${esc(b?.status||'—')}</div></div></div>${(it.data||[]).map(x=>`<div class="history-item"><header><b>${esc(x.entity_type)} · ${esc(x.action)}</b><span class="badge ${x.status==='changed'?'green':'amber'}">${esc(x.status)}</span></header><p>${esc(x.entity_id)}</p><details><summary>Before / After</summary><pre style="white-space:pre-wrap;font-size:10px;background:#f7f9fc;padding:10px;border-radius:8px">BEFORE\n${esc(JSON.stringify(x.before_value,null,2))}\n\nAFTER\n${esc(JSON.stringify(x.after_value,null,2))}</pre></details></div>`).join('')||'<div class="empty">No item records.</div>'}<div class="danger-note">Durable Batch Undo is the next service-layer step. No fake Undo button is shown until the reversal service exists and is verified.</div>`,`<button class="btn" onclick="closeOpsDialog()">Close</button>`)} window.openBatch=openBatch;

async function runHealth(){const btn=$('#runHealthBtn');btnBusy(btn,true,'Checking…');try{await refreshData();renderHealthView()}catch(e){window.toast?.(e.message)}finally{btnBusy(btn,false)}} window.runHealth=runHealth;
function renderHealthView(){const active=activeVariants(),missingPrice=active.filter(v=>!(Number(v.price)>=0)),negative=active.filter(v=>Number(v.stock_quantity)<0),orphan=active.filter(v=>!productFor(v.product_id)),noVariant=products.filter(p=>!variantsFor(p.id).some(v=>v.active)),missingContent=products.filter(contentMissing),formatCounts={Vial:active.filter(v=>v.format==='Vial').length,Cartridge:active.filter(v=>v.format==='Cartridge').length,Pen:active.filter(v=>v.format==='Pen').length};const rows=[['Staging database connection','Healthy',true],['Products',String(products.length),products.length===39],['Variants',String(variants.length),variants.length===224],['Active variants',String(active.length),active.length===222],['Vial / Cartridge / Pen',`${formatCounts.Vial} / ${formatCounts.Cartridge} / ${formatCounts.Pen}`,formatCounts.Vial===76&&formatCounts.Cartridge===72&&formatCounts.Pen===74],['Missing/invalid prices',String(missingPrice.length),missingPrice.length===0],['Negative stock',String(negative.length),negative.length===0],['Orphan variants',String(orphan.length),orphan.length===0],['Products without active variants',String(noVariant.length),noVariant.length===0],['Products needing content draft',String(missingContent.length),missingContent.length===0]];$('#opsContent').innerHTML=`<div class="grid2"><section class="card"><div class="card-head"><h2>Staging Health Checks</h2><button id="runHealthBtn" class="btn primary" onclick="runHealth()">Run Health Check</button></div><div class="health-list">${rows.map(r=>`<div class="health-row"><b>${esc(r[0])}</b><span class="status ${r[2]?'ok':'warn'}">${r[2]?'●':'▲'} ${esc(r[1])}</span></div>`).join('')}</div></section><section class="card"><div class="card-head"><h2>Safety Status</h2><span class="badge green">SAFE MODE</span></div><div class="health-list"><div class="health-row"><b>Environment</b><span class="status ok">● STAGING</span></div><div class="health-row"><b>Production DB writes</b><span class="status ok">● Not configured</span></div><div class="health-row"><b>Manual catalog writes</b><span class="status ok">● Controlled RPC</span></div><div class="health-row"><b>Audit batches</b><span class="status ok">● Enabled</span></div><div class="health-row"><b>Batch Undo</b><span class="status warn">▲ Not enabled yet</span></div></div></section></div>`}

function toggleOpsSidebar(){$('#opsSidebar').classList.toggle('show')} window.toggleOpsSidebar=toggleOpsSidebar;

sb?.auth.onAuthStateChange((event)=>{
  if(event==='PASSWORD_RECOVERY')openDialog('Set New Staging Password','This changes only the isolated staging account.',`<div class="form"><label>New password<input id="recoveryPassword" class="field" type="password" minlength="8"></label><p id="recoveryMsg" class="muted"></p></div>`,`<button class="btn" onclick="closeOpsDialog()">Cancel</button><button class="btn primary" onclick="saveRecoveredPassword()">Save Password</button>`);
});

document.addEventListener('DOMContentLoaded',async()=>{try{const {data:{user}}=await sb.auth.getUser();if(user)await boot()}catch(e){showLoginNotice(e.message,'error')}});
})();
