const SB_URL='https://yjauxyvtrmdriwtmckkl.supabase.co';
const SB_KEY='sb_publishable_xib7Xo5_y1G75gSAmkW9QQ__H5-mgZF';
const psb=supabase.createClient(SB_URL,SB_KEY);
let products=[],categories=[],category='All',showAll=false,cart=JSON.parse(localStorage.getItem('aibt_cart')||'[]');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtStrength=v=>v.strength_label||`${v.strength}${v.strength_unit||''}`;
const variantsFor=p=>(p.variants||[]).filter(v=>v.active!==false&&!v.archived_at);
const imageFor=(p,v)=>v?.image_url||p.main_image_url||'';
const pcolor=p=>p.category?.color||'#0b5eaa';
const catLabel=p=>p.category?.name||'Research';
function saveCart(){localStorage.setItem('aibt_cart',JSON.stringify(cart))}
function unique(arr){return [...new Set(arr.filter(Boolean))]}
function compatibleVariant(p,strength,format){return variantsFor(p).find(v=>fmtStrength(v)===strength&&String(v.format)===format)}
function firstVariant(p){return variantsFor(p).find(v=>Number(v.stock_quantity||0)>0)||variantsFor(p)[0]||null}
function selectedFromCard(id){const p=products.find(x=>x.id===id);if(!p)return null;const s=document.querySelector(`[data-strength="${id}"]`)?.value;const f=document.querySelector(`[data-format="${id}"]`)?.value;return compatibleVariant(p,s,f)}
function cardUpdate(id){const p=products.find(x=>x.id===id);if(!p)return;const sEl=document.querySelector(`[data-strength="${id}"]`),fEl=document.querySelector(`[data-format="${id}"]`);if(!sEl||!fEl)return;let v=compatibleVariant(p,sEl.value,fEl.value);if(!v){const candidates=variantsFor(p).filter(x=>fmtStrength(x)===sEl.value);if(candidates[0]){fEl.value=candidates[0].format;v=candidates[0]}}
const price=document.querySelector(`[data-price="${id}"]`),stock=document.querySelector(`[data-stock="${id}"]`),btn=document.querySelector(`[data-add="${id}"]`),img=document.querySelector(`[data-img="${id}"]`);const ok=v&&Number(v.stock_quantity||0)>0;if(price)price.textContent=v?`RM ${Number(v.price||0).toFixed(2)}`:'Unavailable';if(stock){stock.textContent=ok?`${v.stock_quantity} in stock`:'Out of stock';stock.className=ok?'pl-stock in':'pl-stock out'}if(btn)btn.disabled=!ok;if(img&&v){const u=imageFor(p,v);if(u)img.src=u}}
async function loadCatalog(){const [{data:p,error:pe},{data:c,error:ce}]=await Promise.all([psb.from('products').select('*,variants(*)').eq('published',true).is('archived_at',null).order('name'),psb.from('categories').select('*').eq('status','active').order('name')]);if(pe)throw pe;if(ce)console.warn(ce);categories=c||[];products=(p||[]).map(x=>({...x,category:categories.find(c=>c.id===x.category_id)||null,variants:(x.variants||[]).filter(v=>v.active!==false&&!v.archived_at)}));renderCats();renderProducts();renderCart()}
function renderCats(){const el=document.getElementById('cats');if(!el)return;el.innerHTML=`<button class="cat" onclick="category='All';showAll=true;renderProducts()"><b>ALL</b><small>Browse all products</small></button>`+categories.map(c=>`<button class="cat" onclick="category='${esc(c.id)}';showAll=true;renderProducts()"><b>${esc(c.name).toUpperCase()}</b><small>${esc(c.description||'')}</small></button>`).join('')}
function renderProducts(){const grid=document.getElementById('grid');if(!grid)return;const q=(document.getElementById('search')?.value||'').trim().toLowerCase();let list=products.filter(p=>(category==='All'||p.category_id===category)&&(!q||p.name.toLowerCase().includes(q)));if(category==='All'&&!q&&!showAll)list=list.filter(p=>p.featured);document.getElementById('catalogTitle').textContent=(showAll||q||category!=='All')?'PRODUCT CATALOG':'FEATURED PEPTIDES';grid.innerHTML=list.map(p=>{const v=firstVariant(p),strengths=unique(variantsFor(p).map(fmtStrength)),formats=unique(variantsFor(p).map(v=>v.format)),img=imageFor(p,v);return `<article class="product plain-product" style="--pc:${pcolor(p)}"><span class="tag">${esc(catLabel(p))}</span><button class="plain-info-link" onclick="openProductInfo('${esc(p.id)}')">Product info</button><div class="visual"><img data-img="${esc(p.id)}" src="${esc(img)}" alt="${esc(p.name)}" loading="lazy"></div><h3>${esc(p.name)}</h3><div class="plain-variant-grid"><label>Strength<select data-strength="${esc(p.id)}" onchange="cardUpdate('${esc(p.id)}')">${strengths.map(s=>`<option${s===fmtStrength(v)?' selected':''}>${esc(s)}</option>`).join('')}</select></label><label>Format<select data-format="${esc(p.id)}" onchange="cardUpdate('${esc(p.id)}')">${formats.map(f=>`<option${f===v?.format?' selected':''}>${esc(f)}</option>`).join('')}</select></label></div><div data-price="${esc(p.id)}" class="price">${v?'RM '+Number(v.price||0).toFixed(2):'Unavailable'}</div><div data-stock="${esc(p.id)}" class="pl-stock ${Number(v?.stock_quantity||0)>0?'in':'out'}">${Number(v?.stock_quantity||0)>0?`${v.stock_quantity} in stock`:'Out of stock'}</div><button data-add="${esc(p.id)}" class="plain-add" onclick="addDirect('${esc(p.id)}')" ${Number(v?.stock_quantity||0)>0?'':'disabled'}>ADD TO CART</button></article>`}).join('')||'<p>No products found.</p>'}
function addDirect(id){const p=products.find(x=>x.id===id),v=selectedFromCard(id);if(!p||!v||Number(v.stock_quantity||0)<=0)return;const e=cart.find(x=>x.variantId===v.id);if(e)e.qty++;else cart.push({id:p.id,variantId:v.id,name:p.name,strength:fmtStrength(v),form:v.format,price:Number(v.price),qty:1,image:imageFor(p,v)});saveCart();renderCart();document.getElementById('drawer')?.classList.add('show')}
function changeQty(id,d){const x=cart.find(i=>i.variantId===id);if(!x)return;x.qty=Math.max(0,x.qty+d);cart=cart.filter(i=>i.qty>0);saveCart();renderCart()}
function renderCart(){const n=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.price*x.qty,0);const cc=document.getElementById('cartCount'),ht=document.getElementById('headerTotal'),ci=document.getElementById('cartItems'),ct=document.getElementById('cartTotal');if(cc)cc.textContent=n;if(ht)ht.textContent='RM'+total.toFixed(2);if(ci)ci.innerHTML=cart.map(x=>`<div class="cartitem"><b>${esc(x.name)}</b><br><small>${esc(x.strength)} · ${esc(x.form)}</small><div>RM ${Number(x.price).toFixed(2)} × ${x.qty}</div><div class="cartqty"><button onclick="changeQty('${esc(x.variantId)}',-1)">−</button><button onclick="changeQty('${esc(x.variantId)}',1)">+</button></div></div>`).join('')||'<p>Your cart is empty.</p>';if(ct)ct.textContent='RM '+total.toFixed(2);const d=document.getElementById('drawer');if(d&&!d.querySelector('.checkout-link')){const b=document.createElement('button');b.className='plain-add checkout-link';b.textContent='CHECKOUT';b.onclick=()=>location.href='/checkout.html';d.appendChild(b)}}
function toggleCart(){document.getElementById('drawer')?.classList.toggle('show');renderCart()}
function openProductInfo(id){const p=products.find(x=>x.id===id);if(!p)return;let panel=document.getElementById('plainInfoPanel');if(!panel){panel=document.createElement('div');panel.id='plainInfoPanel';panel.className='plain-info-overlay';document.body.appendChild(panel)}const short=p.short_description||'Research information is being prepared for this catalog item.';const long=p.long_description||'Open Research Insight for a source-backed research summary, molecular context and references for this product.';panel.innerHTML=`<section class="plain-info-panel"><button class="plain-info-close" onclick="closeProductInfo()">×</button><span class="tag" style="background:${pcolor(p)}">${esc(catLabel(p))}</span><h2>${esc(p.name)}</h2><p class="plain-info-short">${esc(short)}</p><div class="plain-info-body">${esc(long)}</div><a class="plain-research-link" href="/research-insight.html?product=${encodeURIComponent(p.id)}">OPEN RESEARCH INSIGHT →</a><small>Research information only. Sources and AI-generated summaries should be reviewed before publication.</small></section>`;panel.classList.add('show')}
function closeProductInfo(){document.getElementById('plainInfoPanel')?.classList.remove('show')}
window.renderProducts=renderProducts;window.cardUpdate=cardUpdate;window.addDirect=addDirect;window.changeQty=changeQty;window.toggleCart=toggleCart;window.openProductInfo=openProductInfo;window.closeProductInfo=closeProductInfo;window.openAdmin=()=>location.href='/admin.html';
document.addEventListener('DOMContentLoaded',()=>loadCatalog().catch(e=>{console.error(e);document.getElementById('grid').innerHTML='<p>Catalog temporarily unavailable. Please refresh.</p>'}));