(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{};
const db=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseKey);
let products=[],loaded=false;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=s=>document.querySelector(s);
const P=(aliases,klass,identity,mechanism,areas,evidence,status,notes='')=>({aliases,klass,identity,mechanism,areas,evidence,status,notes});
function profile(name){const n=String(name||'').toUpperCase();
 if(n==='RETATRUTIDE')return P('LY3437943','Investigational multi-receptor peptide agonist','Retatrutide is an investigational peptide designed to activate GIP, GLP-1 and glucagon receptors in one molecule.','Coordinated GIPR, GLP-1R and GCGR signaling is being studied for effects on nutrient response, endocrine signaling, appetite pathways and energy expenditure.',['Triple agonist pharmacology','Incretin biology','Glucagon receptor biology','Energy expenditure','Metabolic homeostasis'],'Direct human clinical-trial evidence is available, but the molecule remains investigational and evidence continues to evolve.','Clinical-stage investigational','Do not present investigational trial findings as an approved indication or as proof of equivalence for a catalog formulation.');
 if(n==='TIRZEPATIDE')return P('LY3298176','Dual incretin receptor agonist','Tirzepatide is a synthetic peptide with agonist activity at GIP and GLP-1 receptors.','Dual incretin signaling influences glucose-dependent endocrine responses, appetite and nutrient-processing pathways.',['GIP receptor signaling','GLP-1 receptor signaling','Glycaemic biology','Appetite pathways','Cardiometabolic research'],'Large regulated clinical programs exist for approved tirzepatide medicines.','Established regulated medicine in specific indications','Research catalog material must not be represented as equivalent to an approved medicine.');
 if(n==='CAGRILINTIDE')return P('AM833','Long-acting amylin analogue','Cagrilintide is a long-acting amylin analogue developed for metabolic research.','It acts through amylin and calcitonin receptor-family signaling involved in satiety and nutrient-response biology.',['Amylin signaling','Satiety pathways','Gastric signaling','Metabolic regulation'],'Human clinical-development evidence exists, including combination programs.','Clinical-stage investigational','Distinguish molecule-level trial evidence from any specific research formulation.');
 if(n==='SEMAGLUTIDE + CAGRILINTIDE')return P('CagriSema research concept','GLP-1 agonist plus amylin analogue combination','This combination pairs semaglutide, a GLP-1 receptor agonist, with cagrilintide, a long-acting amylin analogue.','The research rationale combines GLP-1 receptor signaling with amylin receptor-family signaling.',['GLP-1 signaling','Amylin signaling','Satiety research','Metabolic outcomes','Combination pharmacology'],'The regulated combination development program has direct human trial data, but a separate catalog blend is not automatically equivalent.','Clinical-development combination','Keep evidence from regulated trial formulations separate from catalog formulation claims.');
 if(n==='RETATRUTIDE + CAGRILINTIDE')return P('Research combination','Triple agonist plus amylin analogue concept','This research stack combines retatrutide with cagrilintide.','The concept combines GIP, GLP-1 and glucagon receptor signaling with amylin receptor-family signaling.',['Multi-receptor signaling','Satiety pathways','Energy balance','Nutrient response'],'Each component has its own evidence base, but published evidence for the exact combined formulation is limited.','Experimental combination','Component evidence should not be treated as proof of a combined clinical effect.');
 if(n==='AOD-9604')return P('hGH fragment 176-191 analogue','Modified growth-hormone fragment','AOD-9604 is a modified fragment derived from the C-terminal region of human growth hormone.','Research has focused on metabolic and lipolytic pathways proposed to be separable from classical growth-promoting GH signaling.',['Adipose metabolism','Lipolysis research','Metabolic signaling'],'Human research exists, but efficacy evidence is mixed and development has been investigational.','Investigational','Avoid overstating weight-related outcomes beyond published evidence.');
 if(n==='5-AMINO-1MQ')return P('5-Amino-1-methylquinolinium','Small-molecule NNMT inhibitor, not a peptide','5-Amino-1MQ is a small-molecule research compound studied as an inhibitor of nicotinamide N-methyltransferase, NNMT.','NNMT participates in nicotinamide metabolism and methyl-donor balance, linking the compound to metabolic and NAD-related research.',['NNMT inhibition','Nicotinamide metabolism','Methyl-donor balance','Metabolic models'],'Evidence is predominantly preclinical.','Preclinical research compound','This product is not a peptide despite being listed in a peptide-focused catalog.');
 if(n==='SLU-PP-332')return P('SLU-PP-332','Experimental ERR agonist, not a peptide','SLU-PP-332 is an experimental small molecule studied as an estrogen-related receptor agonist.','ERR transcriptional signaling regulates oxidative metabolism and mitochondrial gene programs, which is why the compound appears in exercise-mimetic research.',['Estrogen-related receptors','Oxidative metabolism','Mitochondrial transcription','Exercise-mimetic models'],'Evidence is preclinical, mainly from animal and mechanistic research.','Preclinical research compound','Human efficacy and safety are not established.');
 if(n==='MOTS-C')return P('Mitochondrial ORF of the 12S rRNA-c','Mitochondrial-derived peptide','MOTS-C is a mitochondrial-derived peptide encoded within the mitochondrial 12S rRNA region.','Research explores mitochondria-to-nucleus signaling, AMPK-associated energy sensing and cellular adaptation to metabolic stress.',['Mitochondrial signaling','AMPK biology','Metabolic stress','Glucose metabolism','Exercise biology'],'Evidence is mainly mechanistic, preclinical and early translational research.','Experimental and translational','Human evidence is much smaller than the preclinical literature.');
 if(n==='SS-31')return P('Elamipretide, Bendavia, MTP-131','Mitochondria-targeting tetrapeptide','SS-31 is a mitochondria-targeting tetrapeptide widely discussed in research as elamipretide.','It is studied for interactions with mitochondrial inner-membrane and cardiolipin-associated biology, with downstream effects on energetics and oxidative stress.',['Cardiolipin biology','Mitochondrial energetics','Oxidative stress','Electron transport'],'Human clinical-development programs exist, with results varying by indication.','Clinical-development compound','Regulatory status and clinical results depend on indication and jurisdiction.');
 if(n==='NAD+')return P('Nicotinamide adenine dinucleotide','Cellular redox cofactor, not a peptide','NAD+ is a ubiquitous cellular cofactor central to redox reactions and energy metabolism.','It also serves as a substrate for NAD-dependent enzymes including sirtuins and PARPs.',['Redox biology','Mitochondrial metabolism','Sirtuins','PARP biology','Cellular energetics'],'Fundamental biochemistry is established, while health claims for specific supplementation routes require separate evidence.','Established endogenous cofactor','Do not generalize biochemical importance into route-specific clinical benefit.');
 if(n==='L-GLUTATHIONE')return P('GSH, reduced glutathione','Endogenous tripeptide redox buffer','Glutathione is an endogenous tripeptide and a major intracellular redox buffer.','The glutathione system participates in peroxide reduction, detoxification-associated enzyme systems and maintenance of cellular redox state.',['Oxidative stress','Glutathione redox cycle','Detoxification enzymes','Cellular antioxidant systems'],'Its biochemical role is established, while clinical outcomes depend on route, formulation and indication.','Established endogenous molecule','Route-specific claims require clinical evidence.');
 if(n==='EPITHALON')return P('Epitalon, Ala-Glu-Asp-Gly','Synthetic tetrapeptide','Epithalon is a short synthetic peptide investigated in aging-related experimental literature.','Proposed research areas include circadian, gene-regulatory and telomere-associated biology, though mechanisms and translation remain uncertain.',['Cellular aging','Circadian research','Gene regulation','Telomere-related models'],'Evidence is limited and largely experimental, with comparatively little internationally recognized high-quality clinical evidence.','Experimental','Present longevity-related claims as exploratory, not established.');
 if(n==='GHK-CU')return P('Copper tripeptide-1, glycyl-L-histidyl-L-lysine copper','Copper-binding tripeptide complex','GHK-Cu is a naturally occurring copper-binding tripeptide complex studied in extracellular-matrix, skin, hair and wound biology.','Research includes copper-dependent enzyme systems, matrix remodeling, fibroblast activity, collagen-associated pathways, cell migration and gene-expression responses.',['Skin biology','Hair and follicular models','Extracellular matrix','Fibroblast activity','Wound research'],'Mechanistic and preclinical literature is broad, while higher-quality clinical evidence is more limited and formulation-dependent.','Experimental and cosmetic research','Do not generalize topical or preclinical findings to systemic clinical effects.');
 if(n==='AHK-CU')return P('Copper-binding AHK tripeptide','Copper peptide analogue','AHK-Cu is a copper-binding tripeptide analogue used mainly in skin and hair research contexts.','Research focuses on copper-associated cellular and extracellular-matrix pathways, including follicular and dermal models.',['Hair follicle research','Dermal models','Copper signaling','Extracellular matrix'],'Evidence is limited compared with established therapeutic compounds.','Experimental and cosmetic research','Clinical evidence is relatively sparse.');
 if(n==='SNAP-8')return P('Acetyl octapeptide-3','Synthetic cosmetic octapeptide','SNAP-8 is a synthetic octapeptide commonly used in cosmetic formulation research.','It is discussed in relation to SNARE-associated neurotransmitter-release mechanisms in topical cosmetic models.',['Cosmetic peptide formulation','Skin appearance','SNARE-associated mechanisms'],'Evidence is formulation-dependent and largely cosmetic.','Cosmetic research compound','Topical cosmetic evidence should not be generalized to systemic use.');
 if(n==='BPC-157')return P('Body Protection Compound 157','Synthetic 15-amino-acid investigational peptide','BPC-157 is an experimental 15-amino-acid peptide whose literature is dominated by animal and mechanistic studies.','Proposed research mechanisms include nitric-oxide signaling, angiogenic pathways, growth-factor-associated responses and tissue-repair signaling.',['Gastrointestinal models','Tendon and muscle models','Angiogenesis','Nitric-oxide pathways','Tissue repair'],'Evidence is predominantly preclinical with limited high-quality human evidence.','Investigational, predominantly preclinical','There is no established approved formulation or validated universal dosing regimen.');
 if(n==='TB-500')return P('Thymosin beta-4 related fragment','Synthetic thymosin-beta-4 related research peptide','TB-500 is a synthetic research peptide associated with thymosin-beta-4 biology.','Research discussion centers on actin binding, cell migration, angiogenesis and tissue-remodeling pathways.',['Cell migration','Actin biology','Angiogenesis','Tissue remodeling'],'Human evidence is limited and TB-500 should not automatically be equated with full-length thymosin beta-4.','Investigational','Keep fragment identity distinct from full-length thymosin beta-4 evidence.');
 if(n==='BPC-157 + TB-500')return P('BPC-157 plus TB-500 research stack','Two-component repair research blend','This stack combines BPC-157 and TB-500, two compounds commonly discussed in repair-oriented research.','The proposed rationale combines BPC-157-associated nitric-oxide, angiogenic and repair signaling with TB-500-associated actin, migration and remodeling pathways.',['Tissue repair models','Cell migration','Angiogenesis','Tendon and muscle models'],'Evidence for the individual components is mainly preclinical or mechanistic, and direct evidence for the exact combination is limited.','Experimental combination','Component findings should not be presented as proof of the blend.');
 if(n==='KPV')return P('Lys-Pro-Val','Alpha-MSH-derived tripeptide','KPV is the C-terminal Lys-Pro-Val tripeptide sequence associated with alpha-MSH.','Experimental work explores inflammatory, epithelial and melanocortin-associated signaling.',['Inflammation models','Epithelial biology','Immune signaling','Melanocortin-associated pathways'],'Evidence is primarily preclinical.','Preclinical research','Human clinical evidence is limited.');
 if(n==='LL-37')return P('Human cathelicidin antimicrobial peptide','Endogenous antimicrobial peptide','LL-37 is the human cathelicidin antimicrobial peptide and a major subject of innate-immunity research.','It interacts with microbial membranes and also participates in host-defense, inflammatory, epithelial, angiogenic and wound-related signaling.',['Innate immunity','Antimicrobial mechanisms','Inflammatory signaling','Wound biology','Epithelial responses'],'Mechanistic biology is extensive, while therapeutic translation is context-dependent and experimental.','Experimental therapeutic research','LL-37 biology is complex and can differ by tissue and disease context.');
 if(n==='ARA-290')return P('Cibinetide, pyroglutamate helix B surface peptide','Erythropoietin-derived tissue-protective peptide','ARA-290, also known as cibinetide, is derived from erythropoietin and was designed to retain tissue-protective signaling without classical erythropoietic activity.','Research focuses on innate repair receptor-associated signaling, inflammation and tissue protection.',['Innate repair receptor','Inflammation','Tissue protection','Neuropathy-related models'],'Clinical research exists in selected indications, alongside preclinical work.','Clinical-development research','Evidence and status vary by indication.');
 if(n==='SEMAX')return P('ACTH(4-7)-Pro-Gly-Pro analogue','Synthetic neuroactive peptide','Semax is a synthetic ACTH-fragment-derived neuroactive peptide used in experimental neurobiology.','Research discusses neurotrophic, neuromodulatory and stress-response pathways.',['Neuroplasticity','Cognition research','Neurotrophic signaling','Stress response'],'Evidence quality and regulatory status vary substantially by jurisdiction.','Regional or investigational use depending on jurisdiction','Avoid presenting regional use as universal regulatory approval.');
 if(n==='SELANK')return P('Tuftsin-derived synthetic peptide','Synthetic neuroactive peptide','Selank is a synthetic tuftsin-related peptide studied in neurobiology and stress-response research.','Experimental work explores neurotransmitter, immune-neural and stress-related pathways.',['Stress signaling','Cognition research','Neurotransmitter systems','Neuroimmune biology'],'Internationally recognized high-quality clinical evidence is limited.','Investigational or regional research','Avoid established-treatment claims.');
 if(n==='DSIP')return P('Delta sleep-inducing peptide','Experimental neuropeptide','DSIP is an experimental peptide historically investigated in sleep and neuroendocrine research.','Its receptor mechanism remains incompletely defined, and proposed actions span sleep-related and stress-response systems.',['Sleep research','Stress response','Neuroendocrine models'],'Mechanism and clinical relevance remain uncertain.','Experimental','Evidence is heterogeneous and should be presented cautiously.');
 if(n==='PINEALON')return P('Glu-Asp-Arg','Short synthetic peptide','Pinealon is a short synthetic peptide investigated in neurobiology and aging-related experimental literature.','Proposed research discusses gene-regulatory, neuronal stress and neuroprotective pathways.',['Neuronal stress','Cognition models','Gene regulation','Aging research'],'Evidence is limited and largely experimental.','Experimental','High-quality independent human evidence is limited.');
 if(n==='TESAMORELIN')return P('TH9507','Synthetic GHRH analogue','Tesamorelin is a synthetic analogue of growth-hormone-releasing hormone.','It activates the GHRH receptor and downstream pituitary GH and IGF-1 signaling.',['GHRH receptor','GH and IGF-1 axis','Pituitary signaling','Body-composition research'],'A regulated tesamorelin medicine exists for a specific indication and substantial human data are available in that context.','Established regulated medicine in a specific indication','Catalog research material must not imply equivalence to the regulated medicine.');
 if(n==='CJC-1295 WITH DAC')return P('CJC-1295 DAC','Long-acting synthetic GHRH analogue','CJC-1295 with DAC is a synthetic GHRH analogue designed for extended exposure through a drug-affinity-complex strategy.','It targets the GHRH receptor and downstream pituitary GH and IGF-1 signaling.',['GHRH receptor','GH and IGF-1 axis','Peptide half-life engineering'],'Human research exists, but the compound is investigational.','Investigational','DAC and non-DAC forms are pharmacologically distinct and should not be conflated.');
 if(n==='CJC-1295 WITHOUT DAC')return P('Modified GRF 1-29, CJC no DAC terminology varies','Shorter-acting GHRH analogue terminology','Catalog terminology commonly uses CJC-1295 without DAC for a shorter-acting GHRH analogue, often discussed alongside modified GRF 1-29 terminology.','Research centers on GHRH receptor activation and downstream GH and IGF-1 signaling.',['GHRH receptor','GH and IGF-1 axis','Pituitary signaling'],'Evidence is investigational and exact molecular identity should be confirmed because naming conventions vary.','Investigational','Variant identity matters, avoid assuming all “no DAC” labels are chemically identical.');
 if(n==='IPAMORELIN')return P('Ipamorelin','Growth-hormone secretagogue peptide','Ipamorelin is a synthetic growth-hormone secretagogue peptide.','It acts through the ghrelin or GHSR-1a receptor pathway to influence pituitary GH release.',['Ghrelin receptor','Pituitary GH release','Neuroendocrine signaling'],'Investigational human research exists, but established clinical use is limited.','Investigational','Do not present experimental endocrine effects as established treatment outcomes.');
 if(n==='CJC-1295 WITHOUT DAC + IPAMORELIN')return P('GHRH analogue plus GHSR agonist stack','Two-pathway endocrine research combination','This stack combines a shorter-acting GHRH analogue with ipamorelin.','The rationale combines GHRH receptor signaling with ghrelin or GHSR-1a receptor signaling, converging on pituitary GH pathways.',['GHRH signaling','Ghrelin receptor signaling','GH and IGF-1 axis','Combination endocrine research'],'The biological rationale comes mainly from the two component pathways, while direct evidence for the exact combined formulation is limited.','Experimental combination','Component evidence should remain distinct from blend-level claims.');
 if(n==='IPAMORELIN + TESAMORELIN')return P('Tesamorelin plus ipamorelin research stack','GHRH analogue plus GHSR agonist combination','This research stack combines tesamorelin with ipamorelin.','The concept combines GHRH receptor signaling with ghrelin or GHSR-1a receptor signaling.',['Neuroendocrine signaling','GH and IGF-1 axis','Pituitary biology'],'Tesamorelin and ipamorelin have distinct evidence bases, while evidence for the exact combination is limited.','Experimental combination','Do not transfer tesamorelin medicine evidence to the combination automatically.');
 if(n==='VIP')return P('Vasoactive intestinal peptide','Endogenous neuropeptide','VIP is an endogenous neuropeptide with broad physiological roles.','It signals primarily through VPAC1 and VPAC2 class-B GPCRs and participates in neuroimmune, vascular, secretory and smooth-muscle biology.',['VPAC1','VPAC2','Neuroimmune signaling','Vasoregulation','Secretory biology'],'Physiological function is well characterized, while therapeutic applications depend on formulation and indication.','Endogenous peptide, therapeutic research ongoing','Do not infer efficacy for a catalog formulation from endogenous physiology alone.');
 if(n==='PT-141')return P('Bremelanotide','Melanocortin receptor agonist peptide','PT-141 is commonly known as bremelanotide, a melanocortin receptor agonist peptide.','Its central pharmacology is associated particularly with MC4R-linked melanocortin signaling.',['Melanocortin receptors','MC4R signaling','Neuroendocrine sexual-response research'],'A regulated bremelanotide medicine exists for a specific indication, providing direct human evidence in that formulation.','Established regulated medicine in a specific indication','Research catalog material should not imply equivalence to the regulated medicine.');
 if(n==='OXYTOCIN ACETATE')return P('Oxytocin','Endogenous peptide hormone and receptor ligand','Oxytocin is an endogenous peptide hormone and ligand for the oxytocin receptor, OXTR.','OXTR is a G-protein-coupled receptor involved in reproductive, smooth-muscle, social and neuroendocrine signaling.',['Oxytocin receptor','Reproductive biology','Social neurobiology','Smooth-muscle signaling'],'Oxytocin physiology and regulated medical uses are well established in specific settings.','Established endogenous hormone and medicine in specific settings','Claims outside established indications require separate evidence.');
 if(n==='KISSPEPTIN-10')return P('Kisspeptin-10, KISS1 fragment','Kisspeptin receptor peptide ligand','Kisspeptin-10 is a bioactive fragment of the kisspeptin system.','It activates KISS1R or GPR54 and participates in hypothalamic control of GnRH and reproductive endocrine signaling.',['KISS1R or GPR54','GnRH release','Reproductive endocrinology','Hypothalamic signaling'],'Specialist human research exists, but use remains research or development context dependent.','Clinical and translational research','Keep reproductive endocrine research distinct from individualized treatment advice.');
 if(n==='GLOW 70MG')return P('GHK-Cu 50mg + BPC-157 10mg + TB-500 10mg','Three-component research blend','GLOW 70mg combines GHK-Cu, BPC-157 and TB-500. Its scientific rationale is best understood from the components rather than as a separately validated molecule.','The blend concept brings together copper-peptide matrix biology, BPC-157-associated repair signaling and TB-500-associated migration and remodeling pathways.',['Extracellular matrix','Collagen biology','Cell migration','Angiogenesis','Tissue repair models'],'Evidence for the exact three-component blend is substantially more limited than evidence for the individual components.','Experimental blend','Do not present component findings as proof of a combined clinical effect.');
 if(n==='KLOW')return P('GHK-Cu 50mg + BPC-157 10mg + TB-500 10mg + KPV 10mg','Four-component research blend','KLOW combines GHK-Cu, BPC-157, TB-500 and KPV.','The research concept adds KPV-associated inflammatory and epithelial biology to the GLOW-style combination of matrix, repair and cell-migration pathways.',['Extracellular matrix','Inflammatory signaling','Epithelial biology','Cell migration','Tissue repair models'],'Evidence for the exact four-component blend is limited and primarily inferred from individual component literature.','Experimental blend','Component evidence should not be represented as direct proof of the blend.');
 if(n==='BACTERIOSTATIC WATER')return P('Preserved sterile water for compatible applications','Preserved diluent, not a peptide','Bacteriostatic water is a preserved diluent rather than a receptor-active peptide.','Its relevance is preparation and dilution workflow, including compatibility, sterility, preservative concentration and intended use.',['Laboratory preparation','Dilution workflow','Sterility and compatibility'],'The product should be understood through its specification and intended use, not peptide pharmacology.','Diluent or base product','Compatibility and intended use must be confirmed for the material being prepared.');
 return P('','Research catalog compound','This compound is included in the AI BioTech research catalog.','Its molecular target, mechanism and evidence level should be verified from compound-specific literature.',['Molecular identity','Mechanism','Experimental context','Evidence quality'],'Evidence quality varies by compound and research context.','Research reference','No therapeutic claim is implied.');
}
function sourceLinks(name){const x=encodeURIComponent(name);return [
 ['PubMed',`https://pubmed.ncbi.nlm.nih.gov/?term=${x}`,'Biomedical literature'],
 ['ClinicalTrials.gov',`https://clinicaltrials.gov/search?term=${x}`,'Registered clinical studies'],
 ['NIH / PMC',`https://pmc.ncbi.nlm.nih.gov/?term=${x}`,'Full-text biomedical articles'],
 ['Google Scholar',`https://scholar.google.com/scholar?q=${x}`,'Academic literature search'],
 ['FDA',`https://www.fda.gov/search?s=${x}`,'US regulator search'],
 ['EMA',`https://www.ema.europa.eu/en/search?search_api_fulltext=${x}`,'European regulator search']
]}
function strengthList(p){return [...new Set((p.variants||[]).filter(v=>v.active!==false).map(v=>v.strength_label))]}
function card(p){const x=profile(p.name),color=p.categories?.color||'#2F7BFF',tags=x.areas.slice(0,3);return `<article class="rc-card" style="--rc:${esc(color)}"><small>${esc(p.categories?.name||'Research')}</small><h2>${esc(p.name)}</h2><p>${esc(x.identity)}</p><div class="rc-tags">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><button type="button" onclick="openResearchDetailCenter('${esc(p.id)}')">Explore science →</button></article>`}
async function load(){if(loaded)return true;if(!db)return false;const {data,error}=await db.from('products').select('id,name,slug,published,status,category_id,categories(id,name,color),variants(id,strength_label,format,active)').eq('published',true).eq('status','active').order('name');if(error){console.warn(error);return false}products=data||[];loaded=true;return true}
function render(){const grid=q('#rcGrid');if(!grid)return;const term=(q('#rcSearch')?.value||'').trim().toLowerCase(),cat=q('#rcCategory')?.value||'All';const a=products.filter(p=>{const x=profile(p.name);return (cat==='All'||p.categories?.name===cat)&&(!term||[p.name,p.categories?.name,x.aliases,x.klass,x.identity,x.mechanism,...x.areas].join(' ').toLowerCase().includes(term))});q('#rcCount').textContent=`${a.length} research profile${a.length===1?'':'s'}`;grid.innerHTML=a.length?a.map(card).join(''):'<div class="rc-empty">No research profile matches this search.</div>'}
window.openResearchCenter=async function(){let page=q('#researchCenterPage');if(!page){page=document.createElement('section');page.id='researchCenterPage';page.className='research-center-page';document.body.appendChild(page)}const ok=await load();if(!ok){page.innerHTML='<div class="rc-shell"><button class="rc-close" onclick="closeResearchCenter()">×</button><div class="rc-empty">Research Center could not load the staging catalog.</div></div>';page.classList.add('show');return}const cats=['All',...new Set(products.map(p=>p.categories?.name).filter(Boolean))];page.innerHTML=`<div class="rc-shell"><button class="rc-close" type="button" onclick="closeResearchCenter()" aria-label="Close Research Center">×</button><section class="rc-hero"><div class="rc-kicker">AI BIOTECH RESEARCH CENTER</div><h1>Explore the science behind the catalog</h1><p>Browse every active AI BioTech catalog compound by molecular identity, mechanism, research pathway, evidence context and development status. Public literature links are provided for independent research. Private discovery sources remain internal.</p><div class="rc-stats"><span>${products.length} catalog products</span><span>Live category colours</span><span>Evidence-aware profiles</span><span>Public literature links</span></div></section><div class="rc-tools"><input id="rcSearch" type="search" placeholder="Search compound, receptor, pathway or research area…"><select id="rcCategory">${cats.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="rcCount" class="rc-count"></div><div id="rcGrid" class="rc-grid"></div></div>`;page.classList.add('show');document.body.style.overflow='hidden';q('#rcSearch').addEventListener('input',render);q('#rcCategory').addEventListener('change',render);render();page.scrollTop=0};
window.closeResearchCenter=function(){q('#researchCenterPage')?.classList.remove('show');document.body.style.overflow=''};
window.openResearchDetailCenter=async function(id){if(!loaded)await load();const p=products.find(x=>x.id===id);if(!p)return;const x=profile(p.name),color=p.categories?.color||'#2F7BFF',strengths=strengthList(p),links=sourceLinks(p.name);let back=q('#researchDetailCenter');if(!back){back=document.createElement('div');back.id='researchDetailCenter';back.className='rc-detail-back';document.body.appendChild(back)}back.innerHTML=`<article class="rc-detail" style="--rc:${esc(color)}"><button class="rc-detail-close" type="button" onclick="document.getElementById('researchDetailCenter').classList.remove('show')" aria-label="Close research detail">×</button><span class="rc-badge">${esc(p.categories?.name||'Research')}</span><h1>${esc(p.name)}</h1>${x.aliases?`<div class="rc-alias">Also known as: ${esc(x.aliases)}</div>`:''}<section class="rc-section"><h3>Molecular class</h3><p>${esc(x.klass)}</p></section><section class="rc-section"><h3>Molecular identity</h3><p>${esc(x.identity)}</p></section><section class="rc-section"><h3>Primary targets and pathways</h3><p>${esc(x.mechanism)}</p></section><section class="rc-section"><h3>Research areas</h3><div class="rc-areas">${x.areas.map(a=>`<span>${esc(a)}</span>`).join('')}</div></section><section class="rc-section"><h3>Evidence context</h3><p>${esc(x.evidence)}</p><div class="rc-evidence"><div><small>Research status</small><b>${esc(x.status)}</b></div><div><small>Catalog category</small><b>${esc(p.categories?.name||'Research')}</b></div><div><small>Interpretation</small><b>Compound-level evidence only</b></div></div></section>${x.notes?`<section class="rc-section"><h3>Important context</h3><p>${esc(x.notes)}</p></section>`:''}<section class="rc-section"><h3>Catalog strengths</h3><div class="rc-strengths">${strengths.map(s=>`<span>${esc(s)}</span>`).join('')||'<span>See live catalog</span>'}</div></section><section class="rc-section"><h3>Research and literature links</h3><div class="rc-sources">${links.map(l=>`<a href="${esc(l[1])}" target="_blank" rel="nofollow noreferrer"><b>${esc(l[0])} ↗</b><small>${esc(l[2])}, search ${esc(p.name)}</small></a>`).join('')}</div></section><div class="rc-note"><b>Research reference:</b> This page summarizes molecule-level scientific context. It does not establish identity, purity, equivalence, safety, efficacy or regulatory status of a specific supplied batch, and it is not individualized medical advice.</div></article>`;back.classList.add('show');back.scrollTop=0};
window.openResearch=function(id){return window.openResearchDetailCenter(id)};
})();