(()=>{
'use strict';
const cfg=window.AIBT_CONFIG||{},db=window.supabase?.createClient(cfg.supabaseUrl,cfg.supabaseKey);if(!db)return;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c])),money=v=>'RM '+Number(v||0).toFixed(2),dt=v=>v?new Date(v).toLocaleString():'—';
let me=null,profile=null,wallet=null,orders=[],addresses=[],txs=[],payments=[],shipments=[],invoices=[];
function note(m,e=false){const n=$('#memberMessage');n.textContent=m||'';n.className='notice'+(e?' error':'');n.hidden=!m}
function status(v){const s=String(v||'—'),c=/paid|active|delivered|completed|issued/.test(s)?'good':/pending|processing|partial|in_transit/.test(s)?'warn':/cancel|refund|failed|exception/.test(s)?'bad':'';return `<span class="status ${c}">${esc(s.replaceAll('_',' '))}</span>`}
function dialog(title,body,foot=''){const d=$('#memberDialog');$('#memberDialogTitle').textContent=title;$('#memberDialogBody').innerHTML=body;$('#memberDialogFoot').innerHTML=foot;d.showModal()}window.closeMemberDialog=()=>{$('#memberDialog')?.close()};
async function ensure(name=null,phone=null){const {error}=await db.rpc('member_ensure_profile',{p_name:name,p_phone:phone});if(error)throw error}
async function load(){const {data:{user}}=await db.auth.getUser();if(!user){me=null;$('#memberLogin').hidden=false;$('#memberApp').hidden=true;$('#memberSignOut').hidden=true;return}me=user;await ensure();$('#memberLogin').hidden=true;$('#memberApp').hidden=false;$('#memberSignOut').hidden=false;
 const rs=await Promise.all([db.from('customer_profiles').select('*').eq('user_id',user.id).maybeSingle(),db.from('wallet_accounts').select('*').eq('user_id',user.id).maybeSingle(),db.from('orders').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),db.from('addresses').select('*').eq('user_id',user.id).order('is_default',{ascending:false}),db.from('wallet_transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}),db.from('payments').select('*').order('created_at',{ascending:false}),db.from('shipments').select('*').order('updated_at',{ascending:false}),db.from('invoices').select('*').order('issued_at',{ascending:false})]);
 profile=rs[0].data;wallet=rs[1].data;orders=rs[2].data||[];addresses=rs[3].data||[];txs=rs[4].data||[];payments=(rs[5].data||[]).filter(p=>orders.some(o=>o.id===p.order_id));shipments=(rs[6].data||[]).filter(s=>orders.some(o=>o.id===s.order_id));invoices=(rs[7].data||[]).filter(i=>orders.some(o=>o.id===i.order_id));renderStats();openMemberTab('overview')}
window.memberSignIn=async()=>{try{note('Signing in…');const {error}=await db.auth.signInWithPassword({email:$('#memberEmail').value.trim(),password:$('#memberPassword').value});if(error)throw error;note('');await load()}catch(e){note(e.message||String(e),true)}};
window.showRegister=()=>{$('#registerBox').hidden=!$('#registerBox').hidden};
window.memberRegister=async()=>{try{const email=$('#registerEmail').value.trim(),password=$('#registerPassword').value;if(!/^\S+@\S+\.\S+$/.test(email)||password.length<8)throw new Error('Use a valid email and password of at least 8 characters.');note('Creating staging account…');const {data,error}=await db.auth.signUp({email,password,options:{data:{name:$('#registerName').value.trim(),phone:$('#registerPhone').value.trim()},emailRedirectTo:location.origin+'/member.html'}});if(error)throw error;if(data.session){await ensure($('#registerName').value.trim(),$('#registerPhone').value.trim());await load()}else note('Staging account created. Confirm the email if Supabase requests it, then sign in.')}catch(e){note(e.message||String(e),true)}};
window.memberForgot=async()=>{try{const email=$('#memberEmail').value.trim();if(!email)throw new Error('Enter your email first.');const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/member.html?recovery=1'});if(error)throw error;note('Staging password reset email sent.')}catch(e){note(e.message||String(e),true)}};
window.memberSignOutFn=async()=>{await db.auth.signOut();location.reload()};
function renderStats(){$('#walletBalance').textContent=money(wallet?.balance);$('#orderCount').textContent=orders.length;$('#invoiceCount').textContent=invoices.length;$('#trackingCount').textContent=shipments.filter(s=>s.tracking_number).length}
function orderCard(o){const sh=shipments.find(s=>s.order_id===o.id);return `<div class="order"><div class="order-head"><div><b>${esc(o.order_number)}</b><div class="muted">${dt(o.created_at)}</div></div><div>${status(o.status)} ${status(o.payment_status)}</div></div><div class="line"><span>Total</span><b>${money(o.grand_total)}</b></div><div class="line"><span>Amount due</span><b>${money(o.amount_due)}</b></div>${sh?.tracking_number?`<div class="muted">Tracking: ${esc(sh.tracking_number)}</div>`:''}<div class="row-actions"><button class="btn" onclick="openMemberOrder('${o.id}')">Open order</button>${invoices.some(i=>i.order_id===o.id)?`<button class="btn" onclick="openMemberInvoice('${o.id}')">Invoice</button>`:''}</div></div>`}
function openMemberTab(tab){document.querySelectorAll('.tabs .btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const p=$('#memberPanel');if(tab==='overview')p.innerHTML=`<h2>Welcome ${esc(profile?.name||me?.email||'Member')}</h2><p class="muted">${esc(profile?.email||me?.email||'')}</p><div class="row-actions"><a class="btn primary" href="/">Shop products</a><a class="btn" href="/checkout.html">Checkout</a></div><h3>Recent orders</h3>${orders.slice(0,4).map(orderCard).join('')||'<div class="empty">No staging orders yet.</div>'}`;else if(tab==='orders')p.innerHTML=`<h2>Order History</h2>${orders.map(orderCard).join('')||'<div class="empty">No staging orders yet.</div>'}`;else if(tab==='wallet')p.innerHTML=`<h2>Wallet</h2><div class="notice">Current balance: <b>${money(wallet?.balance)}</b></div>${txs.length?txs.map(t=>`<div class="ledger-row"><div><b>${esc(t.transaction_type)}</b><div class="muted">${esc(t.reason)} · ${dt(t.created_at)}</div></div><div class="${Number(t.amount)>=0?'money-positive':'money-negative'}">${Number(t.amount)>=0?'+':''}${money(t.amount)}</div></div>`).join(''):'<div class="empty">No staging wallet transactions.</div>'}`;else if(tab==='profile')renderProfile();else if(tab==='protocols')p.innerHTML='<h2>Private Protocols</h2><div class="notice">The staging protocol entitlement service is not enabled yet. This tab is intentionally read-only until exact Product + Strength + Format entitlements are connected.</div>';}
window.openMemberTab=openMemberTab;
function renderProfile(){$('#memberPanel').innerHTML=`<h2>Profile</h2><div class="form-grid"><label>Name<input id="mpName" class="field" value="${esc(profile?.name||'')}"></label><label>Phone<input id="mpPhone" class="field" value="${esc(profile?.phone||'')}"></label></div><div class="row-actions"><button class="btn primary" onclick="saveMemberProfile()">Save Profile</button></div><h2 style="margin-top:26px">Addresses</h2><button class="btn" onclick="editMemberAddress()">Add Address</button>${addresses.map(a=>`<div class="address ${a.is_default?'default':''}"><b>${esc(a.label)}</b> ${a.is_default?'<span class="status good">Default</span>':''}<p>${esc(a.recipient_name)} · ${esc(a.phone)}<br>${esc(a.line1)} ${esc(a.line2||'')}<br>${esc(a.postcode)} ${esc(a.city)}, ${esc(a.state)}</p><div class="row-actions"><button class="btn" onclick="editMemberAddress('${a.id}')">Edit</button><button class="btn danger" onclick="deleteMemberAddress('${a.id}')">Delete</button></div></div>`).join('')||'<div class="empty">No saved addresses.</div>'}`}
window.saveMemberProfile=async()=>{try{const {error}=await db.rpc('member_save_profile',{p_name:$('#mpName').value,p_phone:$('#mpPhone').value});if(error)throw error;await load();openMemberTab('profile')}catch(e){note(e.message||String(e),true)}};
window.editMemberAddress=id=>{const a=addresses.find(x=>x.id===id)||{};dialog(id?'Edit Address':'Add Address',`<div class="form-grid"><label>Label<input id="maLabel" class="field" value="${esc(a.label||'Home')}"></label><label>Recipient<input id="maRecipient" class="field" value="${esc(a.recipient_name||profile?.name||'')}"></label><label>Phone<input id="maPhone" class="field" value="${esc(a.phone||profile?.phone||'')}"></label><label>Postcode<input id="maPostcode" class="field" value="${esc(a.postcode||'')}"></label><label class="wide">Address line 1<input id="maLine1" class="field" value="${esc(a.line1||'')}"></label><label class="wide">Address line 2<input id="maLine2" class="field" value="${esc(a.line2||'')}"></label><label>City<input id="maCity" class="field" value="${esc(a.city||'')}"></label><label>State<input id="maState" class="field" value="${esc(a.state||'')}"></label><label class="wide"><input id="maDefault" type="checkbox" ${a.is_default?'checked':''}> Set as default address</label></div>`,`<button class="btn" onclick="closeMemberDialog()">Cancel</button><button class="btn primary" onclick="saveMemberAddress('${id||''}')">Save Address</button>`)};
window.saveMemberAddress=async id=>{try{const {error}=await db.rpc('member_save_address',{p_id:id||null,p_label:$('#maLabel').value,p_recipient_name:$('#maRecipient').value,p_phone:$('#maPhone').value,p_line1:$('#maLine1').value,p_line2:$('#maLine2').value,p_postcode:$('#maPostcode').value,p_city:$('#maCity').value,p_state:$('#maState').value,p_is_default:$('#maDefault').checked});if(error)throw error;closeMemberDialog();await load();openMemberTab('profile')}catch(e){dialog('Address not saved',`<div class="notice error">${esc(e.message||String(e))}</div>`,`<button class="btn" onclick="closeMemberDialog()">Close</button>`)}};
window.deleteMemberAddress=id=>dialog('Delete Address','<div class="notice error">Remove this staging address? This cannot be undone.</div>',`<button class="btn" onclick="closeMemberDialog()">Cancel</button><button class="btn danger" onclick="commitDeleteMemberAddress('${id}')">Delete</button>`);
window.commitDeleteMemberAddress=async id=>{try{const {error}=await db.rpc('member_delete_address',{p_id:id});if(error)throw error;closeMemberDialog();await load();openMemberTab('profile')}catch(e){dialog('Delete failed',`<div class="notice error">${esc(e.message||String(e))}</div>`,`<button class="btn" onclick="closeMemberDialog()">Close</button>`)}};
window.openMemberOrder=async oid=>{const o=orders.find(x=>x.id===oid);const {data:items,error}=await db.from('order_items').select('*').eq('order_id',oid);if(error)return dialog('Order error',`<div class="notice error">${esc(error.message)}</div>`);const sh=shipments.find(s=>s.order_id===oid),ps=payments.filter(p=>p.order_id===oid);dialog(o.order_number,`<div class="detail-pairs"><div class="detail-pair"><small>Status</small><b>${esc(o.status)}</b></div><div class="detail-pair"><small>Payment</small><b>${esc(o.payment_status)}</b></div><div class="detail-pair"><small>Total</small><b>${money(o.grand_total)}</b></div><div class="detail-pair"><small>Due</small><b>${money(o.amount_due)}</b></div></div><h3>Items</h3>${(items||[]).map(i=>`<div class="line"><span>${esc(i.product_name)} · ${esc(i.strength_label)} · ${esc(i.format)} × ${i.quantity}</span><b>${money(i.line_total)}</b></div>`).join('')}<h3>Payment records</h3>${ps.length?ps.map(p=>`<div class="line"><span>${esc(p.provider)} · ${esc(p.status)}</span><b>${money(p.amount)}</b></div>`).join(''):'<div class="muted">No captured payment records.</div>'}<h3>Shipping</h3><div class="notice">${sh?.tracking_number?`Tracking ${esc(sh.tracking_number)} · ${esc(sh.status)}`:'Not booked yet.'}</div>`,`<button class="btn" onclick="closeMemberDialog()">Close</button>`)};
window.openMemberInvoice=async oid=>{const inv=invoices.find(i=>i.order_id===oid),o=orders.find(x=>x.id===oid);const {data:items}=await db.from('order_items').select('*').eq('order_id',oid);dialog(inv?.invoice_number||'Invoice',`<div class="invoice-box"><h3>AI BioTech — STAGING INVOICE</h3><div class="muted">${esc(inv?.invoice_number||'')} · ${dt(inv?.issued_at)}</div><div class="line"><span>Order</span><b>${esc(o?.order_number||'')}</b></div>${(items||[]).map(i=>`<div class="line"><span>${esc(i.product_name)} ${esc(i.strength_label)} ${esc(i.format)} × ${i.quantity}</span><b>${money(i.line_total)}</b></div>`).join('')}<div class="line"><span>Discount</span><b>−${money(o?.discount_total)}</b></div><div class="line"><span>Shipping</span><b>${money(o?.shipping_fee)}</b></div><div class="line"><span>Grand total</span><b>${money(o?.grand_total)}</b></div></div>`,`<button class="btn" onclick="closeMemberDialog()">Close</button><button class="btn primary" onclick="window.print()">Print / Save PDF</button>`)};
window.addEventListener('DOMContentLoaded',()=>{if(new URLSearchParams(location.search).get('recovery')==='1')dialog('Set New Password',`<div class="form-grid"><label class="wide">New password<input id="recoveryPassword" class="field" type="password" minlength="8"></label></div>`,`<button class="btn" onclick="closeMemberDialog()">Cancel</button><button class="btn primary" onclick="saveRecoveryPassword()">Update Password</button>`);$('#memberSignOut').onclick=window.memberSignOutFn;load()});
window.saveRecoveryPassword=async()=>{try{const p=$('#recoveryPassword').value;if(p.length<8)throw new Error('Use at least 8 characters.');const {error}=await db.auth.updateUser({password:p});if(error)throw error;closeMemberDialog();note('Password updated.')}catch(e){dialog('Password update failed',`<div class="notice error">${esc(e.message||String(e))}</div>`,`<button class="btn" onclick="closeMemberDialog()">Close</button>`)}};
})();