const {runtimeSupabase,requireServiceRuntime}=require('./runtime-supabase');

const OPEN_API='https://api.easyparcel.com/open_api/2026-06';
const TOKEN_URL='https://api.easyparcel.com/oauth/token';
const STATE_CODES={'Johor':'MY-01','Kedah':'MY-02','Kelantan':'MY-03','Melaka':'MY-04','Negeri Sembilan':'MY-05','Pahang':'MY-06','Penang':'MY-07','Pulau Pinang':'MY-07','Perak':'MY-08','Perlis':'MY-09','Selangor':'MY-10','Terengganu':'MY-11','Sabah':'MY-12','Sarawak':'MY-13','Kuala Lumpur':'MY-14','Labuan':'MY-15','Putrajaya':'MY-16'};

function config(){
  const mode=String(process.env.EASYPARCEL_MODE||'sandbox').trim().toLowerCase();
  return {
    mode:mode==='live'?'live':'sandbox',
    clientId:String(process.env.EASYPARCEL_CLIENT_ID||'').trim(),
    clientSecret:String(process.env.EASYPARCEL_CLIENT_SECRET||'').trim(),
    redirectUri:String(process.env.EASYPARCEL_REDIRECT_URI||'').trim(),
    weight:Math.max(0.1,Number(process.env.EASYPARCEL_DEFAULT_WEIGHT_KG||0.5)),
    pickName:String(process.env.EASYPARCEL_PICK_NAME||'AI BioTech').trim(),
    pickCompany:String(process.env.EASYPARCEL_PICK_COMPANY||'AI BioTech').trim(),
    pickContact:String(process.env.EASYPARCEL_PICK_CONTACT||process.env.EASYPARCEL_PICK_PHONE||'').trim(),
    pickMobile:String(process.env.EASYPARCEL_PICK_MOBILE||process.env.EASYPARCEL_PICK_PHONE||'').trim(),
    pickAddr1:String(process.env.EASYPARCEL_PICK_ADDR1||process.env.EASYPARCEL_PICK_ADDRESS1||'').trim(),
    pickAddr2:String(process.env.EASYPARCEL_PICK_ADDR2||process.env.EASYPARCEL_PICK_ADDRESS2||'').trim(),
    pickCity:String(process.env.EASYPARCEL_PICK_CITY||'').trim(),
    pickPostcode:String(process.env.EASYPARCEL_PICK_POSTCODE||'').trim(),
    pickState:stateCode(process.env.EASYPARCEL_PICK_STATE||'')
  };
}
function stateCode(name){const raw=String(name||'').trim();if(!raw)return'';if(/^MY-\d{2}$/i.test(raw))return raw.toUpperCase();return STATE_CODES[raw]||STATE_CODES[Object.keys(STATE_CODES).find(k=>k.toLowerCase()===raw.toLowerCase())]||raw}
async function jsonFetch(url,options={}){const r=await fetch(url,options);const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}if(!r.ok){const e=new Error(`Request failed (${r.status}).`);e.status=502;e.body=body;throw e}return body}
async function requireUser(req){require('./preview-safety').previewSafety();const auth=String(req.headers?.authorization||'');if(!/^Bearer\s+.+/i.test(auth)){const e=new Error('Sign in required.');e.status=401;throw e}const r=await fetch(`${runtimeSupabase().url}/auth/v1/user`,{headers:{apikey:runtimeSupabase().publishableKey,Authorization:auth}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body=text}if(!r.ok){const e=new Error(body?.message||'Could not verify member session.');e.status=r.status;throw e}return body}
function requireConfig(full=false){require('./preview-safety').previewSafety();const cfg=config();if(!cfg.clientId||!cfg.clientSecret){const e=new Error('EasyParcel OAuth is not configured yet.');e.code='EASYPARCEL_OAUTH_NOT_CONFIGURED';e.status=503;throw e}if(!cfg.pickPostcode||!cfg.pickState){const e=new Error('EasyParcel pickup postcode/state is not configured yet.');e.code='EASYPARCEL_PICKUP_NOT_CONFIGURED';e.status=503;throw e}if(full&&(!cfg.pickContact||!cfg.pickAddr1||!cfg.pickCity)){const e=new Error('EasyParcel pickup profile is incomplete.');e.code='EASYPARCEL_PICKUP_INCOMPLETE';e.status=503;throw e}return cfg}
async function serviceRest(path,{method='GET',body,prefer}={}){require('./preview-safety').previewSafety();const key=String(requireServiceRuntime().serviceKey||'').trim();if(!key){const e=new Error('Server database key is not configured.');e.status=503;throw e}const headers={apikey:key,Authorization:`Bearer ${key}`};if(body!==undefined)headers['Content-Type']='application/json';if(prefer)headers.Prefer=prefer;return jsonFetch(`${runtimeSupabase().url}/rest/v1/${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)})}
async function serviceRpc(name,body={}){return serviceRest(`rpc/${name}`,{method:'POST',body})}
async function requireAdmin(req){const user=await requireUser(req);const rows=await serviceRest(`admin_users?user_id=eq.${encodeURIComponent(user.id)}&active=eq.true&select=user_id,role,active`);if(!Array.isArray(rows)||!rows.length){const e=new Error('Administrator access required.');e.status=403;throw e}return {user,admin:rows[0]}}
async function getOauthTokens(){const t=await serviceRpc('easyparcel_get_oauth_tokens',{});if(!t?.access_token){const e=new Error('EasyParcel OAuth is not connected. Use Connect EasyParcel in Admin.');e.code='EASYPARCEL_OAUTH_NOT_CONNECTED';e.status=409;throw e}return t}
async function storeOauthTokens(t){return serviceRpc('easyparcel_store_oauth_tokens',{p_access_token:t.access_token,p_refresh_token:t.refresh_token||null,p_expires_at:t.expires_at||isoFromSeconds(t.expires_in),p_refresh_expires_at:t.refresh_token_expires_at||isoFromSeconds(t.refresh_token_expires_in)})}
async function refreshOauthTokens(cfg,refreshToken){if(!refreshToken){const e=new Error('EasyParcel session expired. Reconnect EasyParcel in Admin.');e.status=401;throw e}const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshToken});if(cfg.redirectUri)body.set('redirect_uri',cfg.redirectUri);const basic=Buffer.from(`${cfg.clientId}:${cfg.clientSecret}`).toString('base64');const r=await fetch(TOKEN_URL,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body});const t=await r.json().catch(()=>null);if(!r.ok||!t?.access_token){const e=new Error('EasyParcel OAuth refresh failed. Reconnect EasyParcel in Admin.');e.status=401;throw e}await storeOauthTokens(t);return t}
async function openApiPost(path,payload){const cfg=requireConfig();let tokens=await getOauthTokens();let r=await epFetch(path,payload,tokens.access_token);if(r.response.status===401){tokens=await refreshOauthTokens(cfg,tokens.refresh_token);r=await epFetch(path,payload,tokens.access_token)}if(!r.response.ok||Number(r.json?.status_code||r.response.status)>=400){const e=new Error(r.json?.message||`EasyParcel ${path} failed.`);e.status=r.response.status||502;e.body=r.json;throw e}return r.json}
async function epFetch(path,payload,accessToken){const response=await fetch(`${OPEN_API}${path}`,{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload||{})});const text=await response.text();let json;try{json=JSON.parse(text)}catch{const e=new Error('EasyParcel returned invalid JSON.');e.status=502;throw e}return {response,json}}
function isoFromSeconds(seconds){const n=Number(seconds||0);return n>0?new Date(Date.now()+n*1000).toISOString():null}
async function quoteRates({postcode,state,parcelValue=0,weight}){const cfg=requireConfig();const sendState=stateCode(state);if(!/^\d{5}$/.test(String(postcode||''))||!/^MY-\d{2}$/.test(sendState)){const e=new Error('A valid Malaysia postcode and state are required.');e.status=400;throw e}const raw=await openApiPost('/shipment/quotations',{shipment:[{sender:{postcode:cfg.pickPostcode,subdivision_code:cfg.pickState,country:'MY'},receiver:{postcode:String(postcode),subdivision_code:sendState,country:'MY'},parcel_value:Number(parcelValue||0),weight:Math.max(0.1,Number(weight||cfg.weight)),width:0,length:0,height:0}]});const entry=Array.isArray(raw?.data)?raw.data.find(x=>String(x?.status||'').toLowerCase()==='success'):null;const quotes=Array.isArray(entry?.quotations)?entry.quotations:[];const rates=quotes.map(x=>({rateId:'',serviceId:String(x?.courier?.service_id||''),serviceName:String(x?.courier?.service_name||''),courierName:String(x?.courier?.courier_name||''),courierLogo:String(x?.courier?.courier_logo||''),delivery:String(x?.courier?.delivery_duration||''),serviceDetail:Array.isArray(x?.courier?.service_tag)?x.courier.service_tag.join(', '):'',price:Number(x?.pricing?.total_amount||0),shipmentPrice:Number(x?.pricing?.total_amount||0),codAvailable:Boolean(x?.features?.some?.(f=>/cod/i.test(String(f?.name||f))))})).filter(x=>x.serviceId&&Number.isFinite(x.price)&&x.price>=0).sort((a,b)=>a.price-b.price);if(!rates.length){const e=new Error('No EasyParcel rates available.');e.status=422;throw e}return {mode:cfg.mode,rates}}
function selectedServiceFromNotes(notes){const m=String(notes||'').match(/EasyParcel\s+service=([^;\]]+);\s*rate=([^;\]]*);\s*courier=([^;\]]*);\s*price=([0-9.]+)/i);return m?{serviceId:m[1].trim(),rateId:m[2].trim(),courierName:m[3].trim(),price:Number(m[4])}:null}
async function getOrderForShipping(orderId){const rows=await serviceRest(`orders?id=eq.${encodeURIComponent(orderId)}&select=id,order_number,status,grand_total,subtotal,shipping_fee,shipping_address,customer_email,customer_phone,notes`);const order=Array.isArray(rows)?rows[0]:null;if(!order){const e=new Error('Order not found.');e.status=404;throw e}return order}
async function bookAndPayOrder(order){return require('./easyparcel-fulfillment').bookPaidOrder(order.id)}
async function trackAwb(awb){const e=new Error('EasyParcel OAuth tracking adapter is not yet wired in White Clean.');e.code='EASYPARCEL_TRACKING_PENDING';e.status=503;throw e}

module.exports={requireUser,requireAdmin,requireConfig,quoteRates,stateCode,serviceRest,getOrderForShipping,bookAndPayOrder,trackAwb,selectedServiceFromNotes,getOauthTokens,storeOauthTokens,openApiPost};
