const crypto=require('crypto');
const TP='https://dev.toyyibpay.com';
function env(){const e={sbUrl:process.env.STAGING_SUPABASE_URL,pub:process.env.STAGING_SUPABASE_PUBLISHABLE_KEY,service:process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY,tpKey:process.env.TOYYIBPAY_SANDBOX_SECRET_KEY,category:process.env.TOYYIBPAY_STAGING_CATEGORY_CODE||''};if(!e.sbUrl||!e.pub||!e.service)throw new Error('Staging Supabase server credentials are not configured');if(!e.tpKey)throw new Error('ToyyibPay sandbox secret is not configured');return e}
function denyProduction(){if(process.env.VERCEL_ENV==='production')throw Object.assign(new Error('Staging wallet adapter is disabled in production'),{statusCode:403})}
function baseUrl(req){const host=req.headers['x-forwarded-host']||req.headers.host,proto=req.headers['x-forwarded-proto']||'https';if(!host)throw new Error('Request host unavailable');return `${proto}://${host}`}
function parseBody(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return Object.fromEntries(new URLSearchParams(req.body));return{}}
async function postForm(url,data){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)});const t=await r.text();let j=t;try{j=JSON.parse(t)}catch{}if(!r.ok)throw new Error(`ToyyibPay HTTP ${r.status}: ${String(t).slice(0,240)}`);return j}
async function authUser(req,e){const h=String(req.headers.authorization||'');const m=/^Bearer\s+(.+)$/i.exec(h);if(!m)throw Object.assign(new Error('Authenticated staging member required'),{statusCode:401});const r=await fetch(`${e.sbUrl}/auth/v1/user`,{headers:{apikey:e.pub,authorization:`Bearer ${m[1]}`}});const j=await r.json();if(!r.ok||!j?.id)throw Object.assign(new Error('Invalid staging member session'),{statusCode:401});return j}
async function serviceGet(e,path){const r=await fetch(`${e.sbUrl}/rest/v1/${path}`,{headers:{apikey:e.service,authorization:`Bearer ${e.service}`}});const j=await r.json();if(!r.ok)throw new Error(j?.message||'Staging Supabase read failed');return j}
async function serviceRpc(e,name,body){const r=await fetch(`${e.sbUrl}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:e.service,authorization:`Bearer ${e.service}`,'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j?.message||j?.error||`Staging RPC ${name} failed`);return j}
function externalRef(id){return `WT${String(id).replace(/-/g,'')}`}
function intentIdFromRef(ref){const m=/^WT([0-9a-fA-F]{32})$/.exec(String(ref||''));if(!m)return null;const x=m[1].toLowerCase();return `${x.slice(0,8)}-${x.slice(8,12)}-${x.slice(12,16)}-${x.slice(16,20)}-${x.slice(20)}`}
function expectedHash(key,status,orderId,refno){return crypto.createHash('md5').update(String(key)+String(status)+String(orderId)+String(refno)+'ok').digest('hex')}
async function ensureCategory(e){if(e.category)return e.category;const j=await postForm(`${TP}/index.php/api/createCategory`,{catname:'AI BioTech Wallet Staging',catdescription:'AI BioTech staging wallet top ups',userSecretKey:e.tpKey});const code=Array.isArray(j)&&j[0]?.CategoryCode;if(!code)throw new Error('Unable to create ToyyibPay sandbox category');return String(code)}
module.exports={TP,env,denyProduction,baseUrl,parseBody,postForm,authUser,serviceGet,serviceRpc,externalRef,intentIdFromRef,expectedHash,ensureCategory};