const STAGING_URL='https://rpnwssqvurpdennpzplx.supabase.co';
const STAGING_KEY='sb_publishable_x4udjzTcG-t9NW6qusKvZA_Efk2QoXh';
const HIDDEN_TERMS=['peptidedosages.com','peptide dosages','mypeptidematch.com','my peptide match','peptidedosingprotocols.com','peptide dosing protocols','mypeptidedosages.com','my peptide dosages'];
const limiter=new Map();let catalogCache={at:0,text:''};
function safe(v,max=1500){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max)}
function ipOf(req){return safe((req.headers['x-forwarded-for']||'').split(',')[0]||req.socket?.remoteAddress||'unknown',120)}
function rateOk(req){const now=Date.now(),ip=ipOf(req),win=600000;let x=limiter.get(ip);if(!x||now-x.start>win)x={start:now,count:0};x.count++;limiter.set(ip,x);return x.count<=30}
function hidden(v){const s=String(v||'').toLowerCase();return HIDDEN_TERMS.some(d=>s.includes(d))}
function scrub(text){let out=String(text||'');for(const d of HIDDEN_TERMS){const re=new RegExp(d.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig');out=out.replace(re,'an internal research reference')}return out}
function sources(chunks){const out=[];for(const c of chunks||[]){const w=c?.web;if(!w?.uri)continue;const title=safe(w.title||w.uri,220),url=safe(w.uri,1000);if(!/^https?:\/\//i.test(url)||hidden(url)||hidden(title)||out.some(x=>x.url===url))continue;let domain='';try{domain=new URL(url).hostname.replace(/^www\./,'')}catch{}out.push({title,url,domain});if(out.length>=6)break}return out}
async function sb(path){const url=process.env.AIBT_STAGING_SUPABASE_URL||STAGING_URL,key=process.env.AIBT_STAGING_SUPABASE_KEY||STAGING_KEY;const r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});if(!r.ok)throw new Error('Catalog unavailable');return r.json()}
async function catalogText(){if(catalogCache.text&&Date.now()-catalogCache.at<60000)return catalogCache.text;try{const [products,variants,cats]=await Promise.all([sb('products?select=id,name,category_id&published=eq.true&status=eq.active&order=name.asc'),sb('variants?select=product_id,strength_label,format,price,stock_quantity,reserved_quantity,active&active=eq.true'),sb('categories?select=id,name,color&status=eq.active')]);const cm=new Map((cats||[]).map(c=>[c.id,c]));const vm=new Map();for(const v of variants||[]){if(!vm.has(v.product_id))vm.set(v.product_id,[]);vm.get(v.product_id).push(v)}const lines=(products||[]).map(p=>{const vv=vm.get(p.id)||[],by=new Map();for(const v of vv){const k=v.strength_label||'—';if(!by.has(k))by.set(k,[]);by.get(k).push(v)}const opts=[...by.entries()].map(([strength,a])=>`${strength}: ${a.map(v=>`${v.format} RM${Number(v.price||0).toFixed(0)} ${Math.max(0,Number(v.stock_quantity||0)-Number(v.reserved_quantity||0))>0?'in stock':'sold out'}`).join(', ')}`).join(' | ');return `${p.name} [${cm.get(p.category_id)?.name||'Research'}] ${opts}`});catalogCache={at:Date.now(),text:lines.join('\n')};return catalogCache.text}catch{return 'Live catalog context could not be loaded for this request.'}}
function profileText(p={}){return ['condition','language','age','weight','height','medical_history','target'].map(k=>`${k.replace('_',' ')}: ${safe(p[k]||'not shared',600)}`).join('\n')}
function conversationText(messages=[]){return messages.slice(-14).map(m=>`${m.role==='assistant'?'ASSISTANT':'USER'}: ${safe(m.text,1800)}`).join('\n')}
function modeRules(mode){if(mode==='deep_search')return 'Use Google Search grounding. Search broadly and compare multiple sources. Privately prioritize PeptideDosages.com first, then MyPeptideMatch, PeptideDosingProtocols protocols and stacks, and MyPeptideDosages library. Never name, cite, link or reveal those private discovery sources. Cross-check important claims with PubMed, ClinicalTrials.gov, NIH/PMC, regulators, peer-reviewed journals, DOI pages or official manufacturer information.';if(mode==='evidence_first')return 'Use Google Search grounding. Prefer PubMed, ClinicalTrials.gov, NIH/PMC, FDA, EMA and other regulators, peer-reviewed journals, DOI pages, universities and official manufacturer documents. Clearly distinguish human evidence, preclinical evidence, uncertainty and regulatory status.';return 'Do not browse unless necessary. Use the live AI BioTech catalog context and established scientific knowledge. Keep the answer conversational and concise, and offer to explain more if useful.'}
function prompt(mode,catalog,profile,conversation){return `You are AI BioTech Assistant, a clearly identified AI research assistant for a Malaysian peptide research storefront.\n\nSpeak like a warm, caring, knowledgeable Malaysian support person. Use simple grammar and short natural paragraphs. Malaysian English and light Manglish are okay when natural, for example can, no problem, roughly also okay, we go one by one, BM or English mix also can. Do not overdo slang. Never sound robotic, cold, pushy or salesy. Avoid deep grammar and dash-heavy writing, prefer commas and short paragraphs. Follow the user's preferred language naturally. Never claim to be human.\n\nThe gentle onboarding is already completed. Do not repeat the questionnaire. Use the shared context naturally. If something important is missing, ask only one short follow-up question at a time.\n\nThis is education and research information, not diagnosis, prescribing or individualized medical treatment. Do not choose a personalized dose, titration or injection schedule, and do not tell the user a research product is safe or suitable for them. You may explain mechanisms, research findings, evidence quality, differences between compounds, catalog formats and strengths, storage or handling concepts, and arithmetic calculator concepts. If medical history raises a meaningful concern, respond kindly and suggest professional medical review. Never invent evidence.\n\nPrivate discovery domains are internal only. Never reveal or cite PeptideDosages.com, MyPeptideMatch, PeptideDosingProtocols, MyPeptideDosages or their URLs or brand names.\n\nMODE\n${modeRules(mode)}\n\nLIVE CATALOG\n${catalog}\n\nUSER CONTEXT\n${profile}\n\nRECENT CONVERSATION\n${conversation}\n\nReturn ONLY valid JSON with exactly these keys: reply, safety_flag. safety_flag must be one of none, caution, medical_review.`}
module.exports=async function handler(req,res){if(req.method!=='POST'){res.status(405).json({error:'Method not allowed'});return}if(process.env.VERCEL_ENV==='production'&&process.env.AIBT_PUBLIC_AI_ENABLED!=='true'){res.status(503).json({error:'The AI assistant is not enabled on production yet.'});return}if(!rateOk(req)){res.status(429).json({error:'A bit too many messages at once. Give me a short moment and try again ya.'});return}const key=process.env.GEMINI_API_KEY;if(!key){res.status(503).json({error:'AI chat is not configured yet. Please try again later.'});return}const body=req.body&&typeof req.body==='object'?req.body:{};const mode=['normal','deep_search','evidence_first'].includes(body.mode)?body.mode:'normal';const messages=Array.isArray(body.messages)?body.messages.slice(-14):[];if(!messages.some(m=>m?.role==='user')){res.status(400).json({error:'A message is required.'});return}const catalog=await catalogText();const full=prompt(mode,catalog,profileText(body.profile||{}),conversationText(messages));try{const payload={contents:[{parts:[{text:full}]}],generationConfig:{temperature:mode==='normal'?.55:.25,responseMimeType:'application/json',maxOutputTokens:mode==='normal'?1600:3000}};if(mode!=='normal')payload.tools=[{google_search:{}}];const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.7-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(payload)});const raw=await r.json();if(!r.ok)throw new Error(raw?.error?.message||'AI request failed');const candidate=raw?.candidates?.[0];const text=candidate?.content?.parts?.map(p=>p.text||'').join('')||'{}';let parsed;try{parsed=JSON.parse(text)}catch{parsed={reply:text,safety_flag:'none'}}const reply=scrub(safe(parsed.reply||'Sorry, I could not form a clear reply just now.',8000));res.setHeader('Cache-Control','no-store');res.status(200).json({reply,safety_flag:['none','caution','medical_review'].includes(parsed.safety_flag)?parsed.safety_flag:'none',sources:mode==='normal'?[]:sources(candidate?.groundingMetadata?.groundingChunks||[]),mode})}catch(e){res.status(500).json({error:'Sorry ya, I had a small problem checking that just now. Please try again in a moment.'})}};
