const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
for(const f of ['admin-research.js','admin-research.css','research-staging-target.js'])assert.ok(fs.existsSync(path.join(root,f)),`${f} missing`);
const js=read('admin-research.js'),html=read('admin.html'),css=read('admin-research.css'),target=read('research-staging-target.js');
for(const text of ['Fetch New Research','Review Draft','Version History','Manual Draft','Published','Draft','Evidence Gate','High-quality sources','Warnings','verification_note','admin_publish_research_version','admin_reject_research_version','Approve & Publish','Reject'])assert.match(js,new RegExp(text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),`missing admin research contract: ${text}`);
assert.match(js,/research_entry_versions/);
assert.match(js,/Authorization/);
assert.match(js,/window\.view/,'research module must safely wrap the existing admin navigation');
assert.doesNotMatch(js,/\.from\(['"]research_entries['"]\)\.update\(/i,'admin UI must publish through RPC only');
assert.match(target,/rpnwssqvurpdennpzplx/,'preview target must use AI BioTech Staging Supabase');
assert.ok(target.includes('git-(?:feature|review|staging)-'),'preview/staging host detection must be explicit');
assert.match(target,/createClient/,'preview target must intercept Supabase client creation');
assert.match(html,/research-staging-target\.js/,'admin must load staging Supabase target shim');
assert.ok(html.indexOf('research-staging-target.js')<html.indexOf('/admin.js'),'staging target shim must load before admin.js');
assert.match(html,/admin-research\.css/);
assert.match(html,/admin-research\.js/);
assert.match(css,/\.ar-modal-card\{[^}]*color:\s*#(?:1e293b|0f172a|243447)/i,'research modal must set an explicit readable dark text color');
assert.match(css,/\.ar-field\{[^}]*line-height:\s*(?:1\.5|1\.6|1\.65|1\.7)/i,'research review fields must use readable line height');
assert.match(css,/\.ar-product-card h3\{[^}]*color:\s*#(?:0f172a|1e293b|243447)/i,'research product names must set an explicit readable dark text color');
console.log('admin research UI contract passed');
