const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const insight=read('research-insight.js'),html=read('research-insight.html');
assert.doesNotMatch(insight,/api\/ai-product-insight/,'customer insight must not call AI');
assert.doesNotMatch(insight,/admin-research-refresh/,'customer insight must not call admin AI');
assert.doesNotMatch(insight,/localStorage/,'customer insight must not cache AI drafts locally');
assert.match(insight,/research_entries/);
assert.match(insight,/profile_json/);
assert.match(insight,/published_version_id/);
for(const raw of ['GEMINI_API_KEY','OPENAI_API_KEY','AI_QUOTA_EXHAUSTED','Vercel environment'])assert.ok(!insight.includes(raw)&&!html.includes(raw),`public UI must not expose ${raw}`);
assert.match(insight,/Research profile is being prepared/);
assert.match(insight,/temporarily unavailable/i);
const catalogPath=path.join(root,'research-approved-catalog.js');
assert.ok(fs.existsSync(catalogPath),'approved research catalog adapter must exist');
const catalog=read('research-approved-catalog.js');
assert.match(catalog,/research_entries/);
assert.match(catalog,/published_version_id/);
assert.match(catalog,/short_summary/);
assert.match(catalog,/Research profile is being prepared/);
assert.doesNotMatch(catalog,/research_entry_versions/,'public catalog must never query private research versions');
assert.match(catalog,/research-insight\.html\?product=/);
console.log('public research contract passed');
