const fs=require('fs');
const assert=require('assert');
const required=['lib/toyyibpay.js','api/toyyibpay-create.js','api/toyyibpay-callback.js','api/toyyibpay-reconcile.js','payment-return.html','payment-return.js'];
for(const f of required)assert(fs.existsSync(f),`missing ${f}`);
const helper=fs.readFileSync('lib/toyyibpay.js','utf8');
const create=fs.readFileSync('api/toyyibpay-create.js','utf8');
const callback=fs.readFileSync('api/toyyibpay-callback.js','utf8');
const reconcile=fs.readFileSync('api/toyyibpay-reconcile.js','utf8');
const checkout=fs.readFileSync('checkout.js','utf8');
const ret=fs.readFileSync('payment-return.js','utf8');
for(const src of [helper,create,callback,reconcile])assert(!src.includes('https://toyyibpay.com/index.php/api/createBill'),'sandbox code must not use live createBill URL');
assert(helper.includes('TOYYIBPAY_MODE')&&helper.includes("mode!=='sandbox'"),'server helper must fail closed unless explicit sandbox mode is configured');
assert(helper.includes('TOYYIBPAY_SECRET_KEY')&&helper.includes('TOYYIBPAY_CATEGORY_CODE'),'server helper must use dedicated main-store ToyyibPay credentials');
assert(helper.includes('SUPABASE_SERVICE_ROLE_KEY'),'payment persistence must require server-side Supabase service credentials');
assert(helper.includes('https://dev.toyyibpay.com/index.php/api/createBill'),'sandbox helper must use ToyyibPay sandbox createBill');
assert(helper.includes('https://dev.toyyibpay.com/index.php/api/getBillTransactions'),'sandbox helper must verify transactions with ToyyibPay');
assert(helper.includes('createHash')&&helper.includes("'md5'")&&helper.includes('ok'),'shared callback verifier must implement ToyyibPay MD5 hash validation');
assert(helper.includes("s==='1'")&&helper.includes("payment:'successful'")&&helper.includes("order:'paid'"),'verified successful transaction must map payment successful and order paid');
for(const endpoint of [create,callback,reconcile])assert(endpoint.includes('requireSandboxConfig'),'every payment endpoint must pass through sandbox configuration guard');
assert(callback.includes('callbackHash')&&callback.includes('safeEqualHex'),'callback endpoint must reject invalid ToyyibPay hashes');
assert(callback.includes('getBillTransactions'),'callback must confirm the transaction with ToyyibPay after validating the hash');
assert(reconcile.includes('getBillTransactions'),'return reconciliation must verify payment with ToyyibPay, not trust query parameters');
assert(checkout.includes('/api/toyyibpay-create'),'checkout must initiate ToyyibPay payment after order creation');
assert(checkout.includes("method:'GET'")&&checkout.includes('ensureSandboxPaymentReady'),'checkout must preflight sandbox configuration before creating an order');
assert(!checkout.includes("localStorage.removeItem('aibt_cart');cart=[];renderCart();msg('Order created successfully."),'checkout must not clear cart before verified payment');
assert(ret.includes('/api/toyyibpay-reconcile'),'return page must reconcile payment server-side');
assert(ret.includes('AIBTCore.cart.clear()'),'payment success must clear the same scoped cart');
console.log('ToyyibPay sandbox contract: ok');
