const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..');
const rendererPath=path.join(root,'visual-renderer.js');
assert.ok(fs.existsSync(rendererPath),'visual-renderer.js must exist');
const source=fs.readFileSync(rendererPath,'utf8');
const sandbox={window:{}};
vm.runInNewContext(source,sandbox,{filename:'visual-renderer.js'});
const R=sandbox.window.AIBTVisualRenderer;
assert.ok(R,'AIBTVisualRenderer must be exposed');
assert.deepStrictEqual(JSON.parse(JSON.stringify(R.PEN_FIELDS.name)),{x:720,y:674,w:362,h:122,pad:18,max:44,min:16,weight:900});
assert.deepStrictEqual(JSON.parse(JSON.stringify(R.PEN_FIELDS.strength)),{x:1128,y:680,w:126,h:118,pad:12,max:28,min:14,weight:900});
const measure=(text,size)=>String(text).length*size*0.62;
const longSize=R.fitFontSize(measure,'CAGRILINTIDE',R.PEN_FIELDS.name);
const shortSize=R.fitFontSize(measure,'GHK-CU',R.PEN_FIELDS.name);
assert.ok(longSize<shortSize,`long names should shrink (${longSize} < ${shortSize})`);
assert.ok(longSize>=R.PEN_FIELDS.name.min,'fit size must not go below minimum');
assert.match(source,/1536/,'renderer must target a 1536 square canvas');
assert.match(source,/reference-only/,'Cartridge must expose reference-only mode in Phase 1');
for(const forbidden of ['.insert(','.update(','.upsert(','.delete(','.upload('])assert.ok(!source.includes(forbidden),`renderer must be mutation-free: ${forbidden}`);
console.log('visual composer renderer contract passed');
