const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const html=read('index.html');
const cfg=read('staging-config.js');
const store=read('clean-store.js');
const safety=read('white-clean-safety.js');
for(const token of ['STAGING PREVIEW — ISOLATED FROM PRODUCTION WRITES','class="site-header"','class="hero-inner"','class="trust-strip"','id="productGrid"','class="mobile-sticky-cart"']) assert(html.includes(token),`missing White Clean contract: ${token}`);
for(const css of ['/clean-store.css','/storefront-control.css','/storefront-visual-fix.css','/mobile-product-reference-fix.css','/category-visual-accent.css']) assert(html.includes(css),`missing White Clean layer: ${css}`);
assert(html.includes('/visual-renderer.js'),'current visual renderer must remain loaded');
assert(!html.includes('SCIENCE.<br>PRECISION.'),'Dark Biotech hero must not replace White Clean Core v1');
assert(cfg.includes("environment: 'staging'"),'staging environment flag missing');
assert(cfg.includes('checkoutEnabled: false'),'staging checkout must remain gated until isolated checkout is verified');
assert(cfg.includes('memberEnabled: false'),'staging member routing must remain gated until isolated member flow is verified');
assert(html.includes('/white-clean-safety.js'),'deterministic staging safety layer missing');
assert(/no production order, payment, member, wallet or inventory write/i.test(safety),'safety layer must explicitly block production writes');
assert(store.includes("localStorage.setItem('aibt_cart'"),'cart must hand off to shared checkout key');
for(const path of ['lib/toyyibpay.js','api/toyyibpay-create.js','api/toyyibpay-callback.js','api/toyyibpay-reconcile.js','api/toyyibpay-duitnow-status.js','lib/easyparcel.js','lib/easyparcel-fulfillment.js','api/easyparcel-rates.js','api/easyparcel-quote.js','api/easyparcel-book.js','api/easyparcel-track.js','api/easyparcel-status.js','lib/preview-safety.js']) assert(fs.existsSync(path),`missing current integration: ${path}`);
console.log('white-clean-reintegration-gate: ok');
