const fs=require('fs');
const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('clean-store.js','utf8');
assert(html.includes('id="productGrid"'));
assert(js.includes('variant') || js.includes('variants'),'White Clean renderer must use variant data');
assert(!js.includes('const PRODUCTS = ['),'catalog must not be a hard-coded product table');
assert(js.includes('core.cart.add(')&&js.includes('core.cart.get()'),'White Clean must consume the shared cart API');
assert(!js.includes('aibt_staging_cart')&&!js.includes("localStorage.setItem('aibt_cart'"),'theme must not own a separate cart');
assert(js.includes('AIBTProductVisual.render'),'active cards and hero must call the shared visual adapter');
assert(html.includes('/visual-renderer.js'),'current visual renderer must remain loaded by White Clean');
console.log('white-clean-current-core: ok');
